src/dashboard/apigateway/apigateway/editions/ee/apps/docs/gateway/resource_doc/constants.py
- Add examples of using the `X-Bkapi-Authorization` header for the common API documentation template.
=> Add examples of using the X-Bkapi-Authorization header for the common API documentation template

.pre-commit-config.yaml, src/dashboard/Makefile, src/dashboard/apigateway/apigateway/editions/ee/apps/docs/gateway/resource_doc/constants.py, src/dashboard/pyproject.toml
修复`make lint`命令, 确保对所有文件生效(之前调用pre-commit实际上是没有运行的)
其中 `no_implicit_optional = false` 已录单, 需要单独修复
=> style(lints): fix make lint for src/dashboard

src/dashboard/apigateway/apigateway/apps/support/api_sdk/views.py, src/dashboard/apigateway/apigateway/common/error_codes.py, src/dashboard/pyproject.toml
Use 500 as the error code if there is an error generating SDKs
=> Use 500 as the error code if there is an error generating SDKs

src/dashboard/apigateway/apigateway/apps/access_log/helpers.py, src/dashboard/apigateway/apigateway/apps/support/resource_doc/import_doc/docs.py, src/dashboard/apigateway/apigateway/controller/crds/v1beta1/convertor.py, src/dashboard/apigateway/apigateway/controller/registry/dict.py, src/dashboard/apigateway/apigateway/editions/ee/apps/esb/status/es_client.py, src/dashboard/apigateway/apigateway/tests/apps/docs/esb/component/test_views.py, src/dashboard/apigateway/apigateway/tests/apps/docs/esb/doc/test_views.py, src/dashboard/apigateway/apigateway/tests/apps/docs/esb/system/test_views.py, src/dashboard/apigateway/apigateway/tests/apps/docs/gateway/gateway/test_views.py, src/dashboard/apigateway/apigateway/tests/apps/docs/gateway/resource/test_views.py, src/dashboard/apigateway/apigateway/tests/apps/docs/gateway/resource_doc/test_constants.py, src/dashboard/apigateway/apigateway/tests/apps/docs/gateway/resource_doc/test_views.py, src/dashboard/apigateway/apigateway/tests/apps/docs/gateway/sdk/test_views.py, src/dashboard/apigateway/apigateway/tests/apps/docs/gateway/stage/test_views.py
- 修复项目根目录的 __init__.py
- 修复 lint，tests
=> fix project root __init__.py; fix lint, tests

src/dashboard/apigateway/apigateway/apis/open/resource_version/views.py, src/dashboard/apigateway/apigateway/apis/web/release/serializers.py, src/dashboard/apigateway/apigateway/apis/web/release/urls.py, src/dashboard/apigateway/apigateway/apis/web/release/views.py, src/dashboard/apigateway/apigateway/biz/release.py, src/dashboard/apigateway/apigateway/biz/releaser.py, src/dashboard/apigateway/apigateway/biz/stage.py, src/dashboard/apigateway/apigateway/common/release/publish.py, src/dashboard/apigateway/apigateway/controller/tasks/release.py, src/dashboard/apigateway/apigateway/controller/tasks/syncing.py, src/dashboard/apigateway/apigateway/core/admin.py, src/dashboard/apigateway/apigateway/core/constants.py, src/dashboard/apigateway/apigateway/core/managers.py, src/dashboard/apigateway/apigateway/core/models.py, src/dashboard/apigateway/apigateway/editions/ee/apps/esb/component/release.py, src/dashboard/apigateway/apigateway/tests/apis/open/resource_version/test_views.py, src/dashboard/apigateway/apigateway/tests/apis/web/release/test_serializers.py, src/dashboard/apigateway/apigateway/tests/apis/web/release/test_views.py, src/dashboard/apigateway/apigateway/tests/biz/test_release.py, src/dashboard/apigateway/apigateway/tests/biz/test_releaser.py, src/dashboard/apigateway/apigateway/tests/core/test_managers.py, src/dashboard/apigateway/apigateway/tests/utils/test_redis_lock.py, src/dashboard/apigateway/apigateway/utils/redis_utils.py
- 修复release相关api测试问题
- 修改aip层发布历史统一为release_history
- 去除批量发布逻辑，发布历史和stage一对一关联
=> feat: release  fix cr and test api

src/dashboard/apigateway/apigateway/apis/web/resource/serializers.py, src/dashboard/apigateway/apigateway/biz/resource/importer/swagger.py, src/dashboard/apigateway/apigateway/tests/apis/web/resource/test_serializers.py, src/dashboard/apigateway/apigateway/tests/apis/web/resource/test_views.py, src/dashboard/apigateway/apigateway/tests/biz/resource/importer/test_swagger.py
=> 资源创建/更新/获取时，后端数据放到 backend 中

.pre-commit-config.yaml, src/dashboard/apigateway/apigateway/editions/ee/apps/esb/component/serializers.py, src/esb/esb/esb/management/utils/channel_tools.py
=> fix get_msg_type

src/dashboard/apigateway/apigateway/biz/access_log/constants.py
=> fix(apis/web/access_log): change log fields order

src/dashboard/apigateway/apigateway/conf/default.py
fix:
- apisix 后端配置的 `local DEFAULT_JWT_ISSUER = "APIGW"`
=> fix(conf/default.py): default JWT_ISSUER should be `APIGW` while the apisix jwt set it as default

src/dashboard/apigateway/apigateway/apps/metrics/prometheus/dimension.py, src/dashboard/apigateway/apigateway/tests/apps/metrics/prometheus/test_dimension.py
- 新版产品图表中失败请求代表 >=500的请求，而非proxy_error
=> fix(apps/metrics): prometheus proxy_error only means proxy fail, use status>=500 instead

src/dashboard-front/src/components/auth/index.vue, src/dashboard-front/src/http/fetch/error-interceptor.ts
- 【APIgateway1.13 】导入资源文档-点击模板示例及Swagger说明文档跳转地址不符合预期
- 环境概览-新建环境：前端需要校验权重必填 
- 环境页面问题 
- Tag 连载一起了 
- 环境概览：添加插件，确认按钮需要添加二次确认弹框 
- 【APIgateway1.13 】点击Swagger说明文档无反应
- 资源配置-生成版本：最新版本没有的时候直接不展示出来 
- 这个 编辑图标紧跟
- 资源配置：修改名称后鼠标失焦就保存 
- 【APIgateway1.13 】无法编辑组件
- 这里的yaml配置demo有个版本字段需要更新一下，后端导出已经更新
- 这里标签编辑离标签感觉有点远NIT
=> feat: 修复前端问题

src/dashboard-front/src/views/resource/setting/comps/back-config.vue
- feat: 修复 新建资源页面，环境配置中的超时时间是 30 秒，但添加资源时变成了 0 秒，数据未同步
=> feat: 修复 新建资源页面，环境配置中的超时时间是 30 秒，但添加资源时变成了 0 秒，数据未同步

src/dashboard/apigateway/apigateway/biz/plugin/plugin_synchronizers.py, src/dashboard/apigateway/apigateway/biz/resource/importer/validate.py
=> fix(openapi): fix resource plugin import

src/dashboard/apigateway/apigateway/editions/ee/data/apigw-definitions/bk-apigateway-definition.yaml, src/dashboard/apigateway/apigateway/editions/ee/data/apigw-definitions/bk-apigateway-resources.yaml
feat(apigw/definition): upgrade bk-apigateway backend
=> feat(apigw/definition): upgrade bk-apigateway backend

src/dashboard/apigateway/apigateway/apis/web/permission/views.py
=> 修改为从配置文件中获取这个app_code

src/dashboard/apigateway/apigateway/apis/web/docs/gateway/gateway_sdk/serializers.py, src/dashboard/apigateway/apigateway/apis/web/docs/gateway/gateway_sdk/views.py, src/dashboard/apigateway/apigateway/apis/web/release/views.py, src/dashboard/apigateway/apigateway/apps/docs/templatetags/__init__.py, src/dashboard/apigateway/apigateway/apps/docs/templatetags/json_filters.py, src/dashboard/apigateway/apigateway/biz/resource_version.py, src/dashboard/apigateway/apigateway/biz/sdk/models.py, src/dashboard/apigateway/apigateway/conf/default.py, src/dashboard/apigateway/apigateway/templates/api_sdk/zh-hans/python_sdk_usage_example_bkapi.md, src/dashboard/apigateway/apigateway/tests/utils/test_openapi.py, src/dashboard/apigateway/apigateway/utils/openapi.py
=> feat(api/web/doc): doc example add schema example

src/esb/esb/conf/default.py, src/esb/esb/esb/management/commands/sync_system_and_channel_data.py
修复ESB 执行 sync_system_and_channel_data 后，自定义的CMSI通道不可见问题
https://github.com/TencentBlueKing/legacy-bk-paas/issues/1152
=> fix ：custom channel in CMSI will be hidden when exec sync

src/dashboard/apigateway/apigateway/apis/open/permission/helpers.py, src/dashboard/apigateway/apigateway/tests/apis/open/permission/test_helpers.py
=> fix:approval bug

src/dashboard/apigateway/apigateway/apis/web/resource_version/serializers.py, src/dashboard/apigateway/apigateway/tests/apis/web/resource_version/test_serializers.py
=> fix(api/web/resource_version): fix stage plugins

src/dashboard-front/src/views/resource/setting/comps/table-res-to-action.vue, src/dashboard-front/src/views/resource/setting/import.vue
更改资源配置确认页表格空状态 [TAPD](https://tapd.woa.com/tapd_fe/69995498/bug/detail/1069995498130084473)
=> fix: 更改资源配置确认页表格空状态

src/dashboard-front/src/components/ag-editor.vue, src/dashboard-front/src/views/resource/setting/import.vue
=> feat: 新增编辑器错误添加下划波浪线的功能

src/dashboard-front/src/language/lang.ts, src/dashboard-front/src/router/index.ts, src/dashboard-front/src/views/apiDocs/components/component-searcher.vue, src/dashboard-front/src/views/apiDocs/components/doc-detail-main-content.vue, src/dashboard-front/src/views/apiDocs/components/sdk-instruction-content.vue, src/dashboard-front/src/views/apiDocs/doc-detail.vue, src/dashboard-front/src/views/apiDocs/index.vue
=> fix: 修复新版导航体验问题

src/dashboard/apigateway/apigateway/apps/plugin/constants.py, src/dashboard/apigateway/apigateway/common/plugin/plugin_convertors.py, src/dashboard/apigateway/apigateway/fixtures/plugins.yaml, src/dashboard/apigateway/apigateway/tests/common/plugin/test_plugin_convertors.py
=> feat:mock plugin

src/dashboard/apigateway/apigateway/data/version_log/CHANGELOG_en.md
=> fix(release_log): release_log en

src/dashboard-front/src/components/ag-editor.vue, src/dashboard-front/src/views/online-debug/components/doc.vue
=> fix: 全屏状态下复制功能修复&资源文档取值字段修改

src/dashboard/apigateway/apigateway/fixtures/plugins.yaml
修复问题如下：
插件中文名： api 熔断  改成 熔断
插件英文名： API Breaker 改成  Circuit Breaker
熔断响应状态码：默认填  502
熔断响应体： 改成 多行文本框
最大熔断时间： 说明需要补充，最小 3 秒
=> fix:api-breaker yaml

src/dashboard/apigateway/apigateway/apis/web/resource_version/serializers.py
fix(api/web): fix get stage plugins
=> fix(api/web): fix get stage plugins

src/dashboard-front/src/language/lang.ts, src/dashboard-front/src/views/home.vue
=> fix: 修复新建网关时名称校验错误的提示文本不匹配的问题

src/dashboard-front/src/components/resource-detail/index.vue, src/dashboard-front/src/views/components/plugin-manage/index.vue
=> fix: 修复点击删除插件时会触发面板折叠的问题

src/dashboard/apigateway/apigateway/apis/open/resource/serializers.py, src/dashboard/apigateway/apigateway/apis/open/resource/views.py, src/dashboard/apigateway/apigateway/biz/resource/importer/openapi.py, src/dashboard/apigateway/apigateway/tests/apis/open/resource/test_views.py, src/dashboard/apigateway/apigateway/tests/conftest.py
fix(api/open): fix resource sync delete param
=> fix(api/open): fix resource sync delete param

src/dashboard/apigateway/apigateway/apps/support/managers.py, src/dashboard/apigateway/apigateway/biz/resource/importer/openapi.py, src/dashboard/apigateway/apigateway/biz/resource/importer/parser.py, src/dashboard/apigateway/apigateway/core/managers.py, src/dashboard/apigateway/apigateway/tests/apis/web/resource/test_views.py
- 修复1.14  openapi 3.1导入不兼容性问题
- 修复发布异步更新冲突问题
=> fix(openapi): fix doc import and publish update(1.14)

src/dashboard-front/src/views/resource/setting/comps/version-sideslider.vue
=> fix(version-diff): 修复新建的网关在生成版本时差异对比无内容的问题

src/dashboard/apigateway/apigateway/apis/web/resource_version/views.py, src/dashboard/apigateway/apigateway/tests/apis/web/release/test_views.py
fix(api/web): fix resource_version diff
=> fix(api/web): fix resource_version diff

src/dashboard/apigateway/apigateway/biz/backend.py, src/dashboard/apigateway/apigateway/tests/apis/web/backend/test_views.py, src/dashboard/apigateway/apigateway/tests/biz/test_backend.py
fix(biz/backend): 修复后端服务未关联资源但触发环境发布问题
=> fix(biz/backend): 修复后端服务未关联资源但触发环境发布问题

src/dashboard-front/src/components/version-diff/index.vue, src/dashboard-front/src/language/lang.ts, src/dashboard-front/src/views/resource/setting/comps/version-sideslider.vue, src/dashboard-front/src/views/resource/setting/index.vue
=> fix(version-diff): 修复未生成任何版本时版本对比无内容的问题

src/dashboard-front/src/views/apiDocs/doc-detail.vue
=> feat(doc-detail): 新增文档详情页右区折叠按钮

src/dashboard-front/src/components/ag-icon.vue, src/dashboard-front/src/language/lang.ts, src/dashboard-front/src/views/operate-data/access-log/index.vue
=> fix(access-log)：流水日志体验问题修复

src/dashboard-front/src/views/operate-data/statistics-report/components/line-chart.vue, src/dashboard-front/src/views/operate-data/statistics-report/index.vue
=> fix(statistics-report): 统计报表图表修改

src/dashboard/apigateway/apigateway/apis/web/plugin/views.py, src/dashboard/apigateway/apigateway/tests/apis/web/plugin/test_views.py, src/dashboard/apigateway/apigateway/tests/conftest.py
=> fix(apis/web/resource/view): 修复资源绑定插件未修改但触发更新问题

src/dashboard/apigateway/apigateway/apis/web/metrics/views.py, src/dashboard/apigateway/apigateway/tests/apis/web/metrics/test_views.py
1. 统计图表中排查 metrics=app_requests 的接口数据时，偶尔有些时间段查询出来的数据会有target为空的情况。
2. 其他图表数据也会走这个查询接口，也可能存在target为空的问题。
3. 统一对该接口的查询结果进行target过滤。
=> fix(apis/web/metrics): 修复统计图表target为空问题

src/dashboard/apigateway/apigateway/apis/web/metrics/views.py, src/dashboard/apigateway/apigateway/tests/apis/web/metrics/test_views.py
1. 修复读取series层级错误，将 data.data.series 修改为 data.series 。
2. ingress / egress 接口返回的 target 格式调整为 name=xxx ，符合前端 target.split('=')[1] 解析。
=> fix(apis/web/metrics): 修复统计图表series读取问题

src/dashboard-front/src/views/components-access/manage/components/sync-access.vue
=> fix(sync-access.vue): 修复组件同步popover不弹出的问题

src/dashboard/apigateway/apigateway/apis/web/permission/filters.py, src/dashboard/apigateway/apigateway/apis/web/permission/views.py, src/dashboard/apigateway/apigateway/tests/apis/web/permission/test_views.py
问题1：搜索不存在的授权维度
1.1 校验 grant_dimension 是否在 api/resource 范围内，未在范围内直接返回空。
问题2：搜索不存在的资源名称
2.1 如果 resource_id 为数字，则直接查询对应ID的数据。
2.2 如果 resource_id 为字符串，则模糊匹配资源表中 name 字段，将查询结果的 resource_ids 再反查最终数据。
=> fix(apis/web/permission): 修复应用权限的授权维度搜索问题

src/dashboard/apigateway/apigateway/apps/metrics/prometheus/dimension.py
fix(apps/metrics/prometheus): 修复统计报表请求负数问题
=> fix(apps/metrics/prometheus): 修复统计报表请求数为负数问题

src/dashboard-front/src/views/permission/app/index.vue
=> fix(permission/app): 去掉授权记录的“授权类型”列过滤器

src/dashboard/apigateway/apigateway/apis/open/urls.py, src/dashboard/apigateway/apigateway/apis/web/docs/urls.py, src/dashboard/apigateway/apigateway/apis/web/plugin/serializers.py, src/dashboard/apigateway/apigateway/biz/access_log/constants.py, src/dashboard/apigateway/apigateway/biz/gateway/gateway.py, src/dashboard/apigateway/apigateway/components/bk_log.py, src/dashboard/apigateway/apigateway/components/bkapi_client/bkmonitorv3.py, src/dashboard/apigateway/apigateway/components/bkapi_client/log_search.py, src/dashboard/apigateway/apigateway/components/prometheus.py, src/dashboard/apigateway/apigateway/conf/celery_conf.py, src/dashboard/apigateway/apigateway/conf/default.py, src/dashboard/apigateway/apigateway/controller/crds/v1beta1/convertors/stage.py, src/dashboard/apigateway/apigateway/urls.py, src/dashboard/bin/on_migrate, src/dashboard/bin/post_migrate
变更点：
- default.py: 增加 ENABLE_MULTI_TENANT_MODE 变量，从环境变量中获取，默认False
- 多租户模式下，所有 esb 相关的模型/url 不注册
- 返回 feature_flag: ENABLE_MULTI_TENANT_MODE 给到前端 【用户展示差异化的开关】
- bin脚本
- bin/on_migrate: ENABLE_MULTI_TENANT_MODE 开启则不初始化 bk-esb
- bin/post_migrate: ENABLE_MULTI_TENANT_MODE 开启则不初始化 bk-esb
- 多租户模式环境默认插件: bk-tenant-verify， 否则环境默认插件: bk-default-tenant
- 增加 EDITION 环境变量用于区分内外部版（后续逐步合并内外部版代码文件差异）
- bk-monitor 和 bk-log 内外部版使用不同的网关名
- 多租户版本：不再兼容非标准化调用 【直接 allow_auth_from_params 默认值强制设置为 False】
- 多租户版本： 禁用掉免用户认证应用白名单  【直接在slz校验时强校验报错，不允许绑定该插件】
- 多租户版本：日志增加 bk_tenant_id 字段
=> feat(default.py): add ENABLE_MULTI_TENANT_MODE

src/dashboard/apigateway/apigateway/apps/metrics/prometheus/dimension.py, src/dashboard/apigateway/apigateway/tests/apps/metrics/prometheus/test_dimension.py
status 为字符串，改为正则匹配 3xx，4xx，5xx 的 status
=> fix(apps/metrics/prometheus): 修复统计报表非 200 请求 status 条件匹配问题

src/dashboard/apigateway/apigateway/apis/web/metrics/serializers.py, src/dashboard/apigateway/apigateway/apis/web/metrics/views.py, src/dashboard/apigateway/apigateway/apps/metrics/admin.py, src/dashboard/apigateway/apigateway/apps/metrics/management/__init__.py, src/dashboard/apigateway/apigateway/apps/metrics/management/commands/__init__.py, src/dashboard/apigateway/apigateway/apps/metrics/management/commands/fake_stats.py, src/dashboard/apigateway/apigateway/tests/apis/web/metrics/test_serializers.py, src/dashboard/apigateway/apigateway/tests/apis/web/metrics/test_views.py
1. 增加历史请求统计缺少调用方接口
2. 增加批量生成30天的假统计数据的 command
3. 调整请求总量接口的返回数据格式："series": {"datapoints": datapoints}  -> "series": [{"datapoints": datapoints}]
=> fix(api/web/metrics): 修复历史请求统计缺少调用方接口

src/dashboard/apigateway/apigateway/common/plugin/convertor.py, src/dashboard/apigateway/apigateway/fixtures/plugins.yaml, src/dashboard/apigateway/apigateway/tests/common/plugin/test_convertors.py
1. 修改插件注释
2. 调整 headers add 格式改为 dict
3. 该配置会导致 apisix 加载失败："headers":{"remove":\[\],"set":{"a":"2"},"add":\["a:1"\]}，原因为 remove/set/add 为空时不可传递该参数，已调整 convertor 方法
=> fix(common/plugin): fix response-rewrite plugin

src/dashboard/apigateway/apigateway/apps/mcp_server/managers.py
mcp server 权限审批时会更新授权应用，此时 grant_type 类型为申请，如果已经有了主动授权记录，这里会由于 grant_type 不一样导致更新报错
=> fix(apis/web): 修复 mcp server 授权应用问题
