src/dashboard-front/src/App.vue
src/dashboard-front/src/components/user/index.vue
src/dashboard-front/src/views/index.vue
src/dashboard-front/src/views/resource/index.vue
src/dashboard-front/src/views/system/index.vue

- 网关搜索框-输入不存在的网关，跳转页面404修复
- 浏览器全屏改缩屏，显示不出编辑等按钮修复
- 抽屉框-添加负责人时，取消后内容不消失
- 组件文档详情再跳转我的网关，出现报错
- 网关名对齐滚动处理

Fix experience repair

---

src/dashboard-front/src/css/app.css
src/dashboard-front/src/language/lang/en.js
src/dashboard-front/src/language/lang/zh.js
src/dashboard-front/src/views/runtime-data/list.vue

fix: 国际化处理、nav问题

---

src/dashboard-front/package.json

fix: delete bk-icon-apigateway package

fix: delete bk-icon-apigateway package

---

src/dashboard-front/.eslintignore
src/dashboard-front/.eslintrc.js
src/dashboard-front/package.json
src/dashboard-front/postcss.config.js
src/dashboard-front/src/language/lang/en.js

Fix eslint

---

src/dashboard/apigateway/apigateway/controller/helm/values_generator.py
src/dashboard/apigateway/apigateway/tests/controller/helm/test_values_generator.py

bugfix: helm values generate

---

src/core-api/Makefile
src/core-api/cmd/root.go
src/core-api/cmd/version.go
src/core-api/pkg/version/version.go

doc: fix desc
fix: fix go version

feat: add version subcommand

---

src/dashboard/apigateway/apigateway/apis/open/gateway/views.py
src/dashboard/apigateway/apigateway/apps/resource/mixins.py
src/dashboard/apigateway/apigateway/apps/resource/views.py
src/dashboard/apigateway/apigateway/biz/gateway.py
src/dashboard/apigateway/apigateway/conf/default.py
src/dashboard/apigateway/apigateway/controller/helm/values_generator.py
src/dashboard/apigateway/apigateway/core/managers.py
src/dashboard/apigateway/apigateway/core/models.py
src/dashboard/apigateway/apigateway/tests/apps/resource/test_importer.py
src/dashboard/apigateway/apigateway/tests/apps/resource/test_mixins.py
src/dashboard/apigateway/apigateway/tests/controller/helm/test_values_generator.py
src/dashboard/apigateway/apigateway/tests/core/test_managers.py

add app gateway related limit, gateway resource limit check

---

src/dashboard/apigateway/apigateway/fixtures/plugins.yaml

hide plugin bk-verified-user-exempted-apps

---

src/esb/esb/components/esb_conf.py
src/esb/esb/esb/management/utils/api_docs.py
src/esb/esb/esb/management/utils/component_tools.py

- fe_update_user_language 方法改为 GET，以支持 jsonp
- 修复 markdown 版本升级导致的扩展 smart_strong 不存在问题
- 修复内置组件文档未翻译的问题

fe_update_user_language method change to GET, to support jsonp

---

src/dashboard-front/src/views/resource/index.vue

fix: 查看资源无法点击问题

---

src/core-api/Dockerfile

优化dockerfile，分阶段构建，第一和第二阶段的ARG没有办法复用，只能各自单独定义，最后通过
docker build ---build-arg 参数来覆盖

chore:opt dockerfile

---

src/dashboard-front/src/api/index.js
src/dashboard-front/src/components/version-diff/index.vue
src/dashboard-front/src/views/resource/import-doc.vue
src/dashboard-front/src/views/resource/index.vue

- APIGW提示字符显示问题
- sdk错误500处理
- 英文状态文档导入对比不正确修复
- 版本对比无法根据资源名称搜索

Fix experience problem two

---

src/dashboard-front/src/App.vue

fix；组件API文档根据FeatureFlag控制

---

src/dashboard-front/src/App.vue
src/dashboard-front/src/language/lang/en.js
src/dashboard-front/src/language/lang/zh.js
src/dashboard-front/src/main.js
src/dashboard-front/src/views/resource/index.vue

fix: 6-14国际化处理

---

src/core-api/Dockerfile
src/dashboard/bin/on_migrate

…om golang:1.20 to golang:1.20.4
- 修复添加 esb 免用户认证白名单
- lock core-api golang:1.20 to golang:1.20.4

修复添加 esb 免用户认证白名单； lock core-api golang:1.20 to golang:1.20.4

---

src/dashboard-front/src/App.vue
src/dashboard-front/src/common/util.js

fix: 语言切换规则

---

src/dashboard-front/src/views/resource/import-doc.vue

fix: 导入资源文档文件选择限制

---

src/core-api/Dockerfile

chore: remove dockerfile clean the sensitive

---

src/dashboard-front/src/App.vue
src/dashboard-front/src/components/resource-detail/index.vue
src/dashboard-front/src/store/modules/components.js
src/dashboard-front/src/views/base/create-apigw.vue
src/dashboard-front/src/views/component-manager/index.vue
src/dashboard-front/src/views/component-manager/sync-access/index.vue
src/dashboard-front/src/views/doc-category/index.vue
src/dashboard-front/src/views/index.vue
src/dashboard-front/src/views/permission/permission-apply.vue
src/dashboard-front/src/views/resource/import-doc.vue
src/dashboard-front/src/views/runtime-data/chart.vue
src/dashboard-front/src/views/runtime-data/index.vue
src/dashboard-front/src/views/runtime-data/list.vue
src/dashboard-front/src/views/stage/index.vue
src/dashboard-front/src/views/strategy/index.vue
src/dashboard-front/src/views/system/index.vue
src/dashboard-front/src/views/version/create-version.vue

- 组件管理->同步网关、网关发布历史高亮丢失修复
- 翻译JSON文件引号统一
- 控制台log清除
- 冗余代码删除(v1)

fix: 控制台log清除，冗余代码删除(v1)

---

src/dashboard/apigateway/apigateway/controller/crds/v1beta1/convertor.py
src/dashboard/apigateway/apigateway/controller/distributor/etcd.py
src/dashboard/apigateway/apigateway/controller/distributor/helm.py
src/dashboard/apigateway/apigateway/controller/tasks/release.py
src/dashboard/apigateway/apigateway/tests/controller/distributor/test_etcd.py
src/dashboard/apigateway/apigateway/tests/controller/tasks/test_release.py

feat: dashboard distributor remove include_stage

---

src/dashboard-front/src/language/lang/en.js
src/dashboard-front/src/language/lang/zh.js
src/dashboard-front/src/views/resource/import-doc.vue

fix: 资源文档压缩包增加未变更状态

---

src/dashboard-front/src/App.vue

fix: 导航切换逻辑处理

---

src/dashboard/bin/post_migrate

grant permissions for gateway bk-apigatway

---

src/core-api/pkg/api/microgateway/publish_event.go
src/core-api/pkg/server/router.go
src/core-api/pkg/service/publish_event.go

fix: fix core-api publish event report

---

.pre-commit-config.yaml
src/core-api/Dockerfile
src/dashboard/apigateway/apigateway/controller/constants.py
src/dashboard/apigateway/apigateway/controller/crds/v1beta1/convertor.py
src/dashboard/apigateway/apigateway/controller/crds/v1beta1/convertors/resource.py
src/dashboard/apigateway/apigateway/controller/distributor/combine.py
src/dashboard/apigateway/apigateway/controller/management/commands/sync_releases_to_shared_micro_gateway.py
src/dashboard/apigateway/apigateway/controller/management/commands/sync_releases_to_shared_micro_gateway_parallel.py
src/dashboard/apigateway/apigateway/controller/tasks/syncing.py

- 新增发布版本路由
- cli同步设置publish_id为-1,方便后续过滤

feat: dashboard add version router resource and cli sync gateway set publish_id flag 

---

src/dashboard-front/src/components/auth/index.vue

fix: 小窗登录问题url修复

---

src/core-api/pkg/metric/init.go
src/core-api/pkg/middleware/metric_test.go
src/core-api/pkg/middleware/metrics.go
src/core-api/pkg/server/router.go
src/core-api/pkg/service/app_permission.go

feat: fix api  metrics

---

src/dashboard/apigateway/apigateway/editions/ee/data/apidocs/zh/revoke_permissions.md
src/dashboard/apigateway/apigateway/editions/ee/data/apigw-definitions/bk-apigateway-definition.yaml
src/dashboard/bin/post_migrate

- 添加网关 bk-apigateway 网关 API 文档

添加网关 bk-apigateway 网关 API 文档

---

.pre-commit-config.yaml
src/dashboard/apigateway/apigateway/tests/core/management/commands/test_update_jwt_key.py

Fix ruff pre commit

---

src/dashboard/apigateway/apigateway/apps/release/releasers.py
src/dashboard/apigateway/apigateway/apps/release/views.py
src/dashboard/apigateway/apigateway/controller/distributor/etcd.py
src/dashboard/apigateway/apigateway/controller/procedure_logger/release_logger.py
src/dashboard/apigateway/apigateway/controller/tasks/release.py
src/dashboard/apigateway/apigateway/core/managers.py
src/dashboard/apigateway/apigateway/tests/apps/release/test_releasers.py

- 发布历史视图新增发布事件展示
- 发布日志新增publish_id

feat: release history view add publish event and fix release log

---

src/core-api/Dockerfile

chore: build add dlv

---

src/dashboard/apigateway/apigateway/apps/access_log/constants.py
src/dashboard/apigateway/apigateway/apps/access_log/helpers.py
src/dashboard/apigateway/apigateway/apps/monitor/clients/bk_log.py
src/dashboard/apigateway/apigateway/apps/monitor/constants.py
src/dashboard/apigateway/apigateway/apps/monitor/flow/handlers/base.py
src/dashboard/apigateway/apigateway/apps/monitor/flow/handlers/nginx_error.py
src/dashboard/apigateway/apigateway/apps/monitor/models.py
src/dashboard/apigateway/apigateway/common/es_clients.py
src/dashboard/apigateway/apigateway/components/bk_log.py
src/dashboard/apigateway/apigateway/components/bkapi_client/log_search.py
src/dashboard/apigateway/apigateway/conf/default.py
src/dashboard/apigateway/apigateway/editions/ee/apps/esb/status/es_client.py
src/dashboard/apigateway/apigateway/tests/apps/access_log/test_helpers.py
src/dashboard/apigateway/apigateway/tests/apps/access_log/test_views.py
src/dashboard/apigateway/apigateway/tests/apps/monitor/flow/handlers/test_base.py
src/dashboard/apigateway/apigateway/tests/apps/monitor/flow/handlers/test_nginx_error.py
src/dashboard/apigateway/apigateway/tests/common/test_es_clients.py

- 使用 bkog 查询请求日志
- 去除对 bkdata 的依赖

使用 bklog 查询请求日志

---

src/dashboard/apigateway/apigateway/controller/crds/release_data/access_strategy.py
src/dashboard/apigateway/apigateway/tests/controller/crds/release_data/test_access_strategy.py

- 访问策略转换为插件时，bk-cors 插件 allow_origins、allow_origins_by_regex 二选一

访问策略转换为插件时，bk-cors 插件 allow_origins、allow_origins_by_regex 二选一

---

src/dashboard/apigateway/apigateway/conf/default.py
src/esb/esb/components/esb_conf.py
src/esb/esb/dependencies.yaml

- dashboard 使用 esb is_login 组件登录
- 更新 esb confapis=2.14.56

dashboard 使用 esb is_login 组件登录; 更新 esb confapis=2.14.56

---

src/dashboard/apigateway/apigateway/apis/open/support/serializers.py
src/dashboard/apigateway/apigateway/apps/docs/esb/sdk/serializers.py
src/dashboard/apigateway/apigateway/apps/docs/gateway/sdk/serializers.py
src/dashboard/apigateway/apigateway/apps/support/api_sdk/serializers.py
src/dashboard/apigateway/apigateway/apps/support/constants.py
src/dashboard/apigateway/apigateway/apps/support/models.py

修复 sdk 生成失败的问题

---

src/dashboard-front/src/store/index.js
src/dashboard-front/src/store/modules/api-test.js
src/dashboard-front/src/store/modules/label.js
src/dashboard-front/src/store/modules/monitor.js
src/dashboard-front/src/store/modules/permission.js
src/dashboard-front/src/store/modules/report.js

fix: 接口地址调整

---

src/dashboard/apigateway/apigateway/urls.py

refactor(remove): unuse urls

---

src/dashboard/apigateway/apigateway/conf/celery_conf.py
src/dashboard/apigateway/apigateway/editions/ee/apps/esb/component/tasks.py
src/dashboard/apigateway/apigateway/editions/ee/apps/esb/management/commands/split_component_method.py
src/dashboard/apigateway/apigateway/editions/ee/apps/esb/management/commands/sync_to_gateway_and_release.py
src/dashboard/apigateway/apigateway/editions/ee/apps/esb/management/commands/update_esb_gateway_config.py
src/dashboard/apigateway/apigateway/editions/ee/tests/apps/esb/component/test_tasks.py
src/dashboard/bin/post_migrate

- 网关同步 ESB 组件任务，环境第一次部署时，采用同步方法同步，再次部署时，采用异步方法同步

Fix dashboard post migrate

---

src/dashboard/apigateway/apigateway/common/es_clients.py

fix: fix sentive log

---

src/dashboard/bin/post_migrate

feat: migrate header rewrite to post migrate

---

src/dashboard/apigateway/apigateway/controller/tasks/syncing.py

fix: dashboard fix publish_id

---

src/dashboard-front/src/components/auth/index.css
src/dashboard-front/src/components/auth/index.vue

fix：小窗登录尺寸修复

---

src/dashboard-front/src/views/permission/index.vue

fix: 应用权限导出已筛选条件传参问题修复

---

src/dashboard/apigateway/apigateway/apps/plugin/plugin/checker.py
src/dashboard/apigateway/apigateway/apps/plugin/plugin/convertor.py
src/dashboard/apigateway/apigateway/controller/crds/release_data/access_strategy.py
src/dashboard/apigateway/apigateway/controller/crds/release_data/plugin.py
src/dashboard/apigateway/apigateway/tests/apps/plugin/plugin/test_convertor.py
src/dashboard/apigateway/apigateway/tests/controller/crds/release_data/test_access_strategy.py
src/dashboard/apigateway/apigateway/tests/controller/crds/release_data/test_plugin.py

- 修复 allow_orgins 不建议为 None 的问题，将其设置为 "null"，为 None 时，apisix 将使用其默认值 *

修复 allow_orgins 不建议为 None 的问题，为 None 时，apisix 将使用其默认值 *

---

src/dashboard/apigateway/apigateway/apis/web/permission/filters.py
src/dashboard/apigateway/apigateway/apis/web/permission/serializers.py
src/dashboard/apigateway/apigateway/apis/web/permission/views.py

Fix permission

---

src/dashboard/apigateway/apigateway/controller/crds/release_data/access_strategy.py
src/dashboard/apigateway/apigateway/tests/controller/crds/release_data/test_access_strategy.py

修复访问策略 cors 数据转换的问题

---

src/dashboard/Dockerfile
src/esb/Dockerfile

镜像中安装 procps

---

src/dashboard-front/src/components/auth/index.css
src/dashboard-front/src/components/auth/index.vue

fix: te小窗登录显示不全修复

---

src/dashboard-front/src/views/resource/index.vue

fix: 资源管理查看资源无法点击修复

---

src/dashboard-front/src/views/access-log/index.vue
src/dashboard-front/src/views/online-test/index.vue
src/dashboard-front/src/views/permission/index.vue

- 在线调试Body输入框显示异常-修复
- 应用权限 无法导出已筛选应用权限，资源名称限制
- 查询最近1小时提示问题修复

Fix bug 1.12

---

src/dashboard/apigateway/apigateway/editions/ee/data/apigw-definitions/bk-esb-definition.yaml
src/esb/esb/dependencies.yaml

- 更新 confapis to 2.14.57
- bk-esb 网关设置为隐藏

更新 confapis to 2.14.57

---

src/dashboard-front/src/views/component-doc/doc/detail.vue

fix: 双击网关API文档，骨架屏无法关闭问题修复

---

src/dashboard/apigateway/apigateway/editions/ee/data/apigw-definitions/bk-apigateway-definition.yaml
src/dashboard/apigateway/apigateway/editions/ee/data/apigw-definitions/bk-apigateway-inner-definition.yaml
src/dashboard/apigateway/apigateway/editions/ee/data/apigw-definitions/bk-default-definition.yaml
src/dashboard/apigateway/apigateway/editions/ee/data/apigw-definitions/bk-esb-definition.yaml

优化 bk-apigateway 等网关的描述

---

src/dashboard-front/src/views/permission/index.vue

- 资源名称禁止手动输入，readonly状态退格bug修复

fix: 资源名称禁止手动输入，readonly状态退格bug修复

---

src/esb/esb/dependencies.yaml

update confapis to 2.14.58

---

src/dashboard/apigateway/apigateway/components/paasv3.py
src/dashboard/apigateway/apigateway/conf/default.py

- 去除 components paasv3 对 common 模块的依赖

去除 components paasv3 对 common 模块的依赖

---

src/esb/esb/dependencies.yaml

update confapis to 2.14.59

---

src/dashboard/apigateway/apigateway/apis/web/feature/views.py
src/dashboard/apigateway/apigateway/apis/web/gateway/views.py
src/dashboard/apigateway/apigateway/apis/web/label/views.py
src/dashboard/apigateway/apigateway/apis/web/resource/doc/serializers.py
src/dashboard/apigateway/apigateway/apis/web/resource/doc/views.py
src/dashboard/apigateway/apigateway/apis/web/resource/views.py

- 使用 method_decorator 处理网关 apis 的接口文档

use method_decorator to handle swagger doc

---

src/dashboard/apigateway/apigateway/core/management/commands/migrate_backend.py

bugfix: fix migrate backend command

---

src/dashboard/apigateway/apigateway/apis/open/esb/permission/views.py
src/dashboard/apigateway/apigateway/apis/open/permission/views.py
src/dashboard/apigateway/apigateway/apis/open/resource_version/views.py
src/dashboard/apigateway/apigateway/apis/web/backend/views.py
src/dashboard/apigateway/apigateway/apis/web/release/serializers.py
src/dashboard/apigateway/apigateway/apis/web/release/views.py
src/dashboard/apigateway/apigateway/apis/web/resource/views.py
src/dashboard/apigateway/apigateway/apis/web/stage/views.py
src/dashboard/apigateway/apigateway/apis/web/user/urls.py
src/dashboard/apigateway/apigateway/apis/web/user/views.py

fix swagger error

---

src/dashboard/apigateway/apigateway/apis/web/backend/constants.py
src/dashboard/apigateway/apigateway/apis/web/backend/views.py
src/dashboard/apigateway/apigateway/apis/web/stage/serializers.py
src/dashboard/apigateway/apigateway/apis/web/stage/views.py
src/dashboard/apigateway/apigateway/biz/stage.py
src/dashboard/apigateway/apigateway/core/constants.py
src/dashboard/apigateway/apigateway/tests/apis/web/backend/test_views.py
src/dashboard/apigateway/apigateway/tests/apis/web/stage/test_views.py

fix: update stage backend by review

---

src/dashboard/apigateway/apigateway/apis/open/permission/helpers.py
src/dashboard/apigateway/apigateway/apis/open/permission/serializers.py
src/dashboard/apigateway/apigateway/apis/open/permission/views.py
src/dashboard/apigateway/apigateway/apis/open/stage/serializers.py
src/dashboard/apigateway/apigateway/apis/web/permission/filters.py
src/dashboard/apigateway/apigateway/apis/web/permission/serializers.py
src/dashboard/apigateway/apigateway/apis/web/permission/views.py
src/dashboard/apigateway/apigateway/apis/web/stage/serializers.py
src/dashboard/apigateway/apigateway/apps/permission/admin.py
src/dashboard/apigateway/apigateway/apps/permission/management/commands/copy_app_permission.py
src/dashboard/apigateway/apigateway/apps/permission/managers.py
src/dashboard/apigateway/apigateway/apps/permission/models.py
src/dashboard/apigateway/apigateway/biz/permission.py
src/dashboard/apigateway/apigateway/core/management/commands/migrate_backend.py
src/dashboard/apigateway/apigateway/editions/ee/apps/esb/management/commands/add_esb_permissions.py
src/dashboard/apigateway/apigateway/tests/apis/open/permission/test_helpers.py
src/dashboard/apigateway/apigateway/tests/apis/open/permission/test_serializers.py
src/dashboard/apigateway/apigateway/tests/apis/open/permission/test_views.py
src/dashboard/apigateway/apigateway/tests/apis/web/permission/test_serializers.py
src/dashboard/apigateway/apigateway/tests/apis/web/permission/test_views.py
src/dashboard/apigateway/apigateway/tests/apps/permission/test_managers.py
src/dashboard/apigateway/apigateway/tests/biz/test_permission.py

fix: update stage backend permission by cr

---

src/dashboard/apigateway/apigateway/apis/open/stage/serializers.py
src/dashboard/apigateway/apigateway/apis/web/backend/constants.py
src/dashboard/apigateway/apigateway/apis/web/backend/serializers.py
src/dashboard/apigateway/apigateway/apis/web/constants.py
src/dashboard/apigateway/apigateway/apis/web/serializers.py
src/dashboard/apigateway/apigateway/apis/web/stage/serializers.py

fix: backend slz

---

src/core-api/pkg/cacheimpls/init.go
src/core-api/pkg/cacheimpls/publish_event.go
src/core-api/pkg/cacheimpls/publish_event_test.go
src/core-api/pkg/cacheimpls/trace.go
src/core-api/pkg/service/publish_event.go
src/core-api/pkg/service/publish_event_test.go

core api publish event add cache

---

src/core-api/pkg/cacheimpls/init.go
src/core-api/pkg/cacheimpls/publish_event.go
src/core-api/pkg/cacheimpls/publish_event_test.go
src/core-api/pkg/cacheimpls/trace.go
src/core-api/pkg/service/publish_event.go
src/core-api/pkg/service/publish_event_test.go

core api publish event add cache 1.12

---

src/dashboard/apigateway/apigateway/controller/crds/v1beta1/convertors/resource.py

fix: fix version route

---

src/dashboard/apigateway/apigateway/apis/open/permission/serializers.py
src/dashboard/apigateway/apigateway/apis/web/permission/serializers.py
src/dashboard/bin/on_migrate

remove --hosting-type for command sync_gateway in on_migrate

---

src/dashboard/apigateway/apigateway/apis/web/release/serializers.py
src/dashboard/apigateway/apigateway/apis/web/release/views.py
src/dashboard/apigateway/apigateway/apis/web/resource_version/serializers.py
src/dashboard/apigateway/apigateway/apis/web/resource_version/views.py
src/dashboard/apigateway/apigateway/apis/web/sdk/serializers.py
src/dashboard/apigateway/apigateway/apis/web/sdk/views.py

doc(apis/web): some  api add doc

---

src/dashboard/apigateway/apigateway/apis/web/docs/esb/component/doc/views.py
src/dashboard/apigateway/apigateway/apis/web/docs/esb/component/views.py
src/dashboard/apigateway/apigateway/apis/web/docs/esb/sdk/views.py
src/dashboard/apigateway/apigateway/apis/web/docs/esb/system/views.py
src/dashboard/apigateway/apigateway/apis/web/docs/gateway/gateway/views.py
src/dashboard/apigateway/apigateway/apis/web/docs/gateway/gateway_sdk/views.py
src/dashboard/apigateway/apigateway/apis/web/docs/gateway/resource/doc/views.py
src/dashboard/apigateway/apigateway/apis/web/docs/gateway/resource/views.py
src/dashboard/apigateway/apigateway/apis/web/docs/gateway/sdk/views.py
src/dashboard/apigateway/apigateway/apis/web/docs/gateway/stage/views.py
src/dashboard/apigateway/apigateway/apis/web/feature/views.py
src/dashboard/apigateway/apigateway/apis/web/gateway/views.py
src/dashboard/apigateway/apigateway/apis/web/label/views.py
src/dashboard/apigateway/apigateway/apis/web/resource/doc/views.py
src/dashboard/apigateway/apigateway/apis/web/resource/views.py
src/dashboard/apigateway/apigateway/apis/web/resource_doc/views.py

添加 django swagger WebAPI 文档中的方法描述

---

src/dashboard/apigateway/apigateway/apis/open/stage/serializers.py
src/dashboard/apigateway/apigateway/apis/web/backend/serializers.py
src/dashboard/apigateway/apigateway/apis/web/backend/views.py
src/dashboard/apigateway/apigateway/apis/web/permission/serializers.py
src/dashboard/apigateway/apigateway/apis/web/permission/views.py
src/dashboard/apigateway/apigateway/apis/web/serializers.py
src/dashboard/apigateway/apigateway/apis/web/stage/serializers.py
src/dashboard/apigateway/apigateway/apis/web/stage/views.py

feat: add stage backend permission swagger docs description

---

src/dashboard/apigateway/apigateway/apis/web/stage/serializers.py
src/dashboard/apigateway/apigateway/biz/resource_version.py
src/dashboard/apigateway/apigateway/fixtures/plugins.yaml

fix: stage list api

---

src/esb/bin/start.sh

update esb gunicorn param: set keep-alive to 0

---

src/dashboard/apigateway/apigateway/editions/ee/apps/docs/gateway/resource_doc/constants.py

add bk_token to api docs

---

src/dashboard/apigateway/apigateway/apps/plugin/managers.py

Fixes: PluginConfigManager missing method bulk_delete

fix(apps/plugin): PluginConfigManager missing method bulk_delete

---

src/dashboard/apigateway/apigateway/biz/released_resource_doc/constants.py
src/dashboard/apigateway/apigateway/biz/released_resource_doc/generators.py
src/dashboard/apigateway/apigateway/conf/default.py
src/dashboard/apigateway/apigateway/tests/biz/released_resource_doc/test_constants.py

Fix add bk token to doc master

---

src/dashboard/apigateway/apigateway/apis/web/resource_version/serializers.py
src/dashboard/apigateway/apigateway/apis/web/resource_version/views.py
src/dashboard/apigateway/apigateway/biz/backend.py
src/dashboard/apigateway/apigateway/biz/plugin_binding.py
src/dashboard/apigateway/apigateway/tests/apis/web/resource_version/test_serializers.py
src/dashboard/apigateway/apigateway/tests/apis/web/resource_version/test_views.py
src/dashboard/apigateway/apigateway/tests/conftest.py

fix: fix resource version api

---

src/core-api/pkg/middleware/logger.go
src/core-api/pkg/middleware/metrics.go

修复core-api metrics duration metrics and log duration

fix: fix core-api lantency metrics and logs(1.12)

---

src/core-api/pkg/middleware/logger.go
src/core-api/pkg/middleware/metrics.go

修复core-api metrics duration精度问题以及log duration

fix: fix core-api lantency metrics and logs

---

src/dashboard/apigateway/apigateway/tests/drf_yasg/__init__.py
src/dashboard/apigateway/apigateway/tests/drf_yasg/test_urls.py

add test for gateway swagger docs

---

src/dashboard/apigateway/apigateway/common/error_codes.py
src/dashboard/apigateway/apigateway/common/exception_handler.py

fix(exception/csrf): csrf failed error code should not be IAM_NO_PERMISSION

---

src/dashboard/apigateway/apigateway/common/swagger.py
src/dashboard/apigateway/apigateway/urls.py

fix(swagger/schema): support https

---

src/dashboard/apigateway/apigateway/apis/web/plugin/serializers.py

fix(plugin/config): remove description

---

src/dashboard/apigateway/apigateway/biz/resource_version_diff.py
src/dashboard/apigateway/apigateway/tests/biz/test_resource_version_diff.py

fix: fix resource diff

---

src/dashboard/apigateway/apigateway/biz/resource_version_diff.py

resource version diff add allow_apply_permission

fix: resource version diff add allow_apply_permission

---

src/core-api/Makefile

make build use tag as version(cherry-pick)

feat: make build use tag as version(cherry-pick)

---

src/core-api/Dockerfile
src/core-api/Makefile

修改build镜像.git文件缺失导致version命令信息缺失。

fix: fix version get

---

src/core-api/Dockerfile
src/core-api/Makefile

修复 build镜像.git文件缺失导致version命令信息缺失。

fix: fix version get(cherry-pick)

---

src/dashboard/apigateway/apigateway/conf/default.py
src/dashboard/apigateway/apigateway/controller/crds/v1beta1/convertors/stage.py

FIX: 支持某些网关开启 bk-legacy-invalid-params 插件

fix(legacy/plugins): enable bk-legacy-invalid-params for some gateways

---

src/dashboard-front-new/Dockerfile

feat: modify dckerfile

---

src/dashboard-front-new/.bk.production.env
src/dashboard-front-new/index.html

feat: modify index.html

---

src/dashboard-front-new/bk.config.js
src/dashboard-front-new/index.html

fix: 修复根目录路径

---

src/dashboard/apigateway/apigateway/apis/web/release/serializers.py

fix: fix publish support comment

---

src/dashboard-front-new/index.html
src/dashboard-front-new/package.json
src/dashboard-front-new/src/common/menu.ts
src/dashboard-front-new/src/common/util.ts
src/dashboard-front-new/src/components/key-valuer/index.vue
src/dashboard-front-new/src/css/app.css
src/dashboard-front-new/src/hooks/use-query-list.ts
src/dashboard-front-new/src/http/fetch/index.ts
src/dashboard-front-new/src/http/index.ts
src/dashboard-front-new/src/http/online-test.ts
src/dashboard-front-new/src/http/permission.ts
src/dashboard-front-new/src/http/resource.ts
src/dashboard-front-new/src/router/index.ts
src/dashboard-front-new/src/views/backend-service/index.vue
src/dashboard-front-new/src/views/components/plugin-manage/index.vue
src/dashboard-front-new/src/views/components/plugin-manage/plugin-info.vue
src/dashboard-front-new/src/views/online-test/index.vue
src/dashboard-front-new/src/views/operate-data/access-log/detail.vue
src/dashboard-front-new/src/views/operate-data/access-log/index.vue
src/dashboard-front-new/src/views/operate-data/report/index.vue
src/dashboard-front-new/src/views/permission/app/index.vue
src/dashboard-front-new/src/views/permission/apply/index.vue
src/dashboard-front-new/src/views/permission/record/index.vue
src/dashboard-front-new/src/views/resource/setting/import-doc.vue
src/dashboard-front-new/src/views/resource/setting/import.vue
src/dashboard-front-new/src/views/resource/setting/index.vue

feat: 添加导入功能

---

src/dashboard/apigateway/apigateway/apis/web/backend/filters.py

fix: backend list filter

---

.pre-commit-config.yaml
src/dashboard/Makefile
src/dashboard/pyproject.toml

- 修复ruff format 命令缺失的`force-exclude`
- 去除无用的配置

style(ruff): update ruff cli args

---

src/dashboard/apigateway/apigateway/apis/open/resource_version/views.py
src/dashboard/apigateway/apigateway/apis/open/stage/serializers.py
src/dashboard/apigateway/apigateway/apis/open/stage/views.py
src/dashboard/apigateway/apigateway/apis/web/stage/validators.py
src/dashboard/apigateway/apigateway/biz/releaser.py
src/dashboard/apigateway/apigateway/biz/validators.py
src/dashboard/apigateway/apigateway/tests/apis/open/resource_version/test_views.py
src/dashboard/apigateway/apigateway/tests/apis/web/stage/test_validators.py

openapi sync stage 时，允许环境参数不存在

---

src/dashboard/apigateway/apigateway/biz/backend.py
src/dashboard/apigateway/apigateway/biz/plugin/plugin_synchronizers.py
src/dashboard/apigateway/apigateway/biz/resource/savers.py
src/dashboard/apigateway/apigateway/biz/resource_doc/importer/importers.py
src/dashboard/apigateway/apigateway/biz/stage.py
src/dashboard/apigateway/apigateway/common/plugin/header_rewrite.py

bulk_update set updated_time

---

src/dashboard/apigateway/apigateway/apis/web/release/views.py
src/dashboard/apigateway/apigateway/biz/release.py
src/dashboard/apigateway/apigateway/tests/apis/web/release/test_serializers.py

fix: release api

---

src/dashboard/apigateway/apigateway/apis/web/resource_version/serializers.py
src/dashboard/apigateway/apigateway/apis/web/resource_version/views.py

fix: fix resource version list query

---

src/dashboard/apigateway/apigateway/apis/web/resource_version/serializers.py
src/dashboard/apigateway/apigateway/apis/web/resource_version/views.py

fix: fix resource version list

---

src/dashboard/apigateway/apigateway/apis/web/docs/esb/component/serializers.py
src/dashboard/apigateway/apigateway/apis/web/docs/esb/component/views.py
src/dashboard/apigateway/apigateway/apis/web/gateway/serializers.py
src/dashboard/apigateway/apigateway/apis/web/gateway/views.py
src/dashboard/apigateway/apigateway/apis/web/monitor/serializers.py
src/dashboard/apigateway/apigateway/apis/web/monitor/views.py
src/dashboard/apigateway/apigateway/apis/web/permission/filters.py
src/dashboard/apigateway/apigateway/apis/web/permission/serializers.py
src/dashboard/apigateway/apigateway/apis/web/release/serializers.py
src/dashboard/apigateway/apigateway/apis/web/release/views.py
src/dashboard/apigateway/apigateway/apis/web/resource/serializers.py
src/dashboard/apigateway/apigateway/apis/web/resource_doc/serializers.py
src/dashboard/apigateway/apigateway/apps/monitor/managers.py
src/dashboard/apigateway/apigateway/apps/ssl_certificate/serializers.py
src/dashboard/apigateway/apigateway/apps/ssl_certificate/views.py
src/dashboard/apigateway/apigateway/biz/resource/resource.py
src/dashboard/apigateway/apigateway/editions/ee/apps/esb/bkcore/managers.py
src/dashboard/apigateway/apigateway/tests/apis/web/monitor/test_views.py
src/dashboard/apigateway/apigateway/tests/apis/web/release/test_serializers.py
src/dashboard/apigateway/apigateway/tests/apis/web/release/test_views.py
src/dashboard/apigateway/apigateway/tests/apis/web/resource/test_views.py
src/dashboard/apigateway/apigateway/tests/biz/resource/test_resource.py

feat(apis/web): change `query` to `keyword` in list apis

---

src/dashboard/apigateway/apigateway/apis/web/resource_version/views.py
src/dashboard/apigateway/apigateway/apis/web/sdk/serializers.py
src/dashboard/apigateway/apigateway/apis/web/sdk/views.py
src/dashboard/apigateway/apigateway/apps/support/managers.py
src/dashboard/apigateway/apigateway/controller/crds/v1beta1/convertors/resource.py

fix: fix sdk list

---

src/dashboard/apigateway/apigateway/controller/tasks/syncing.py

fix: fix rolling update publish

---

src/dashboard/apigateway/apigateway/apis/web/docs/gateway/gateway/serializers.py
src/dashboard/apigateway/apigateway/apis/web/docs/gateway/gateway/views.py
src/dashboard/apigateway/apigateway/tests/apis/web/docs/gateway/gateway/test_views.py

 API 文档使用的网关列表,切换为分页模式

---

src/dashboard/apigateway/apigateway/apis/web/docs/gateway/gateway/views.py
src/dashboard/apigateway/apigateway/apis/web/docs/gateway/sdk/serializers.py
src/dashboard/apigateway/apigateway/apis/web/docs/gateway/sdk/views.py
src/dashboard/apigateway/apigateway/apis/web/resource/serializers.py
src/dashboard/apigateway/apigateway/tests/apis/web/docs/gateway/gateway/test_views.py
src/dashboard/apigateway/apigateway/tests/apis/web/docs/gateway/sdk/test_views.py

sdk list use page

---

src/dashboard/apigateway/apigateway/apps/metrics/prometheus/statistics.py
src/dashboard/apigateway/apigateway/apps/metrics/statistics.py
src/dashboard/apigateway/apigateway/components/__init__.py
src/dashboard/apigateway/apigateway/components/prometheus.py
src/dashboard/apigateway/apigateway/conf/default.py
src/dashboard/apigateway/apigateway/tests/apps/metrics/test_statistics.py

支持按网关拉取请求量数据

---

src/dashboard/apigateway/apigateway/apis/web/plugin/views.py

fix(apis/web/plugin): fix notes always be en

---

src/dashboard/apigateway/apigateway/apis/web/docs/gateway/resource/doc/views.py
src/dashboard/apigateway/apigateway/biz/released_resource_doc/__init__.py
src/dashboard/apigateway/apigateway/biz/released_resource_doc/generators.py
src/dashboard/apigateway/apigateway/biz/released_resource_doc/released_resource_doc.py
src/dashboard/apigateway/apigateway/tests/apis/web/docs/gateway/resource/doc/test_views.py
src/dashboard/apigateway/apigateway/tests/biz/released_resource_doc/test_generators.py
src/dashboard/apigateway/apigateway/tests/biz/released_resource_doc/test_released_resource_doc.py

修复资源文档不存在的问题

---

src/dashboard/apigateway/apigateway/apis/web/sdk/views.py
src/dashboard/apigateway/apigateway/apps/support/api_sdk/managers/base.py
src/dashboard/apigateway/apigateway/apps/support/api_sdk/models.py
src/dashboard/apigateway/apigateway/tests/apps/support/api_sdk/managers/test_base.py

Optimize the sdk to generate exception messages and remove restrictions on gateway public properties

fix: Optimize the sdk to generate exception messages

---

src/core-api/pkg/cacheimpls/init.go

fix: fix core-api cache expire time (1.13)

---

src/dashboard/apigateway/apigateway/apis/web/backend/filters.py
src/dashboard/apigateway/apigateway/apis/web/backend/views.py
src/dashboard/apigateway/apigateway/apis/web/permission/serializers.py
src/dashboard/apigateway/apigateway/apis/web/permission/views.py
src/dashboard/apigateway/apigateway/apis/web/serializers.py
src/dashboard/apigateway/apigateway/apps/permission/constants.py

1. 权限导出类型改为中文
2. backend list增加排序

fix: update by user experience issue

---

src/esb/esb/dependencies.yaml

update confapis to 2.14.61

---

src/dashboard/apigateway/apigateway/apps/monitor/flow/handlers/app_request.py
src/dashboard/apigateway/apigateway/apps/monitor/flow/handlers/resource_backend.py
src/dashboard/apigateway/apigateway/tests/apps/monitor/flow/handlers/test_app_request.py
src/dashboard/apigateway/apigateway/tests/apps/monitor/flow/handlers/test_resource_backend.py

告警信息中，去掉querystring

---

src/dashboard/apigateway/apigateway/apis/web/access_log/serializers.py

feat(access_log): change the log fields order

---

src/dashboard/apigateway/apigateway/urls.py

fix: fix api url

---

src/dashboard/apigateway/apigateway/apis/web/resource/views.py
src/dashboard/apigateway/apigateway/tests/apis/web/resource/test_views.py

- backend path check 接口，如果后端服务地址为空，报错

backend path check 接口，如果后端服务地址为空，报错

---

src/dashboard/apigateway/apigateway/biz/released_resource.py
src/dashboard/apigateway/apigateway/biz/resource_version.py
src/dashboard/apigateway/apigateway/tests/biz/test_released_resource.py

fix: fix stage release info

---

src/dashboard/apigateway/apigateway/apis/open/permission/helpers.py
src/dashboard/apigateway/apigateway/tests/apis/open/permission/test_helpers.py

查询应用已有权限时，允许展示正在申请中的权限状态

---

src/dashboard/apigateway/apigateway/conf/default.py
src/dashboard/apigateway/apigateway/core/management/commands/delete_celery_task.py
src/dashboard/apigateway/apigateway/core/management/commands/sync_gateway.py

- 添加celery task清理django commond
- 网关同步

feat: add task clean commond and fix gateway sync

---

bkpkg-bk_apigateway.yaml

添加 bkpkg-bk_apigateway.yaml 版本依赖声明文件

build(bkpkg-bk_apigateway.yaml): add bkpkg yaml

---

src/esb/esb/dependencies.yaml

feat(esb/dependencies.yaml): update to 2.14.62

---

src/dashboard/apigateway/apigateway/apis/web/resource_version/serializers.py
src/dashboard/apigateway/apigateway/apis/web/resource_version/views.py
src/dashboard/apigateway/apigateway/tests/apis/web/resource_version/test_views.py

fix resource_version diff without source and target

fix: fix resource_version diff without source and target

---

src/dashboard/apigateway/apigateway/apis/web/resource/serializers.py
src/dashboard/apigateway/apigateway/apis/web/resource_doc/serializers.py
src/dashboard/apigateway/apigateway/biz/resource/resource.py

feat: resource list filter by backend name

---

src/esb/esb/dependencies.yaml

feat: update esb dependencies version 2.14.63

---

src/dashboard/apigateway/apigateway/apps/plugin/plugin/views.py

fix: 1.12 版本隐藏 bk-header-rewrite 插件配置

fix(apps/plugin): hide bk-header-rewrite plugin configs

---

src/esb/esb/dependencies.yaml

feat: update esb version (1.12)

---

src/esb/esb/dependencies.yaml

feat: update esb version

---

src/dashboard/apigateway/apigateway/fixtures/plugins.yaml

fix: header rewrite key pattern

---

src/dashboard/apigateway/apigateway/fixtures/plugins.yaml

fix(fixtures/plugins.yaml): fix to match vue3 ui

---

src/dashboard-front/src/app.vue

fix bugs of menu item missing

---

src/dashboard/apigateway/apigateway/common/release/publish.py

fix: don't sync the gateway/stage never been published

fix(sync/gateways): if no release_list, skip

---

src/dashboard/bin/post_migrate

fix: sync al gateways should not cause the job fail

fix(bin/post_migrate): sync al gateways should not cause the job fail

---

src/dashboard/apigateway/apigateway/apis/web/resource/views.py

fix(backend/checking): empty backend addr tip

---

.github/workflows/dashboard-front.yml

Update dashboard-front.yml， change github action node version to 16

---

src/dashboard/apigateway/apigateway/apis/web/permission/filters.py
src/dashboard/apigateway/apigateway/fixtures/plugins.yaml

- [fix] fixtures/plugins.yaml bk-rate-limit plugin ui
- [fix] apply permission list support applied_by fuzzy search

fix(fixtures/plugins.yaml): plugin ui

---

src/dashboard-front/Dockerfile

feat(dashboard-front/dockerfile): upgrade node from 14 to 16

---

src/dashboard/apigateway/apigateway/conf/default.py

- 更新feature flag配置，去除无用flag，增加注释

feat(conf/default.py): update feature flags

---

src/dashboard-front/src/components/table-empty.vue
src/dashboard-front/src/hooks/use-query-list.ts
src/dashboard-front/src/hooks/use-selection-data.ts
src/dashboard-front/src/store/user.ts
src/dashboard-front/src/types/store.ts
src/dashboard-front/src/views/basic-info/index.vue
src/dashboard-front/src/views/home.vue
src/dashboard-front/src/views/main.vue
src/dashboard-front/src/views/operate-records/index.vue
src/dashboard-front/src/views/permission/app/index.vue
src/dashboard-front/src/views/permission/record/index.vue
src/dashboard-front/src/views/resource/version/components/resourceDetail.vue
src/dashboard-front/src/views/resource/version/edition/index.vue

- 【APIgateway1.13 】导出应用权限时导出的授权类型与实际不符
- 【APIgateway1.13 】资源版本界面会强制刷新
- 【APIgateway1.13 】停用启用网关后前端无提示
- 【APIgateway1.13 】运行数据-统计报表 数据为空时未提示暂无数据
- 【APIgateway1.13 】资源详情搜索不存在的资源未按搜索为空规范
- 【APIgateway1.13 】展开蓝鲸应用ID后无任何数据
- 【APIgateway1.13 】点击SDK版本号后无任何响应
- 【APIgateway1.13 】点击Swagger说明文档无反应
- 【APIgateway1.13 】功能开关存在不生效的 ENABLE_RUN_DATA_METRICS = false 时隐藏 运行数据-统计报表
- 【APIgateway1.13 】应用权限搜索框未按搜索为空规范
- 【APIgateway1.13 】功能开关存在不生效的 ALLOW_CREATE_APPCHAT
- 【APIgateway1.13 】操作对象及操作类型搜索结果为空未按搜索为空规范
- 【APIgateway1.13 】点击SDK数字未跳转到对应的SDK版本
- 【APIgateway1.13 】网关基本信息页面刷新会闪现 当前网关已停用的 提示条
- 【APIgateway1.13 】footer 内外部版本差异
- 【APIgateway1.13 】左侧菜单折叠/展开之后影响到其他菜单
- 【APIgateway1.13 】勾选版本后一段时间未操作，勾选将消失（看起来界面刷新了）

feat: 修复测试前端问题

---

src/dashboard/Dockerfile

Dashboard中支持 `curl` 以及 `python manage.py dbshell`

feat(dockerfile): support curl and python manange.py dbshell

---

src/dashboard-front/package.json
src/dashboard-front/src/http/access-log.ts
src/dashboard-front/src/language/lang.ts
src/dashboard-front/src/router/index.ts
src/dashboard-front/src/views/main.vue
src/dashboard-front/src/views/operate-data/access-log/common/type.ts
src/dashboard-front/src/views/operate-data/access-log/detail.vue
src/dashboard-front/yarn.lock

- 【APIgateway1.13 】复制分享链接使用分享链接地址后内容为空

feat: 【APIgateway1.13 】复制分享链接使用分享链接地址后内容为空

---

src/dashboard-front/package.json
src/dashboard-front/yarn.lock

feat: 修复启用/停用成功提示弹出两次的问题

---

src/dashboard-front/src/views/monitor/alarm-history/index.vue
src/dashboard-front/src/views/monitor/alarm-strategy/index.vue

fix: 告警历史、告警策略增加select筛选、搜索空规范

fix: 告警历史、告警策略增加select筛选、搜索空规范

---

src/dashboard-front/src/views/monitor/alarm-history/index.vue

fix: 去掉log

---

src/dashboard-front/bk.config.js
src/dashboard-front/package.json
src/dashboard-front/yarn.lock

feat: 更新前端构建脚手架

---

src/dashboard-front/src/http/monitor.ts
src/dashboard-front/src/views/components-access/runtime-data/detail.vue
src/dashboard-front/src/views/monitor/alarm-strategy/index.vue

fix: 系统实时概况排序问题修复；告警策略增加提示

---

src/dashboard-front/src/views/main.vue

- feat: 左侧导航菜单可以同时展开,并默认展开选中节点的菜单

feat: 左侧导航菜单可以同时展开,并默认展开选中节点的菜单

---

src/dashboard-front/src/hooks/use-query-list.ts
src/dashboard-front/src/views/home.vue
src/dashboard-front/src/views/resource/version/edition/index.vue

- 首页搜索以及表头吸顶
- 【APIgateway1.13 】告警策略-是否启用可增加提示
- 【APIgateway1.13 】勾选版本后一段时间未操作，勾选将消失（看起来界面刷新了）
- 【APIgateway1.13 】复制分享链接使用分享链接地址后内容为空

feat: 修复前端部分问题

---

src/dashboard/apigateway/apigateway/apps/access_strategy/utils.py
src/dashboard/apigateway/apigateway/apps/plugin/management/commands/migrate_access_strategy.py
src/dashboard/apigateway/apigateway/apps/plugin/management/commands/migrate_access_strategy_user_verified.py
src/dashboard/apigateway/apigateway/core/migrations/0039_auto_update_1_13.py
src/dashboard/apigateway/apigateway/fixtures/plugins.yaml
src/dashboard/apigateway/apigateway/tests/apps/plugin/management/command/test_migrate_access_strategy_user_verified.py

- bk-verified-user-exempted-apps scope change to `stage`
- 单独迁移 bk-verified-user-exempted-apps

fix(fixtures/plugins.yaml): migrate access_strategy for bk-verified-user-exempted-apps

---

src/dashboard/apigateway/apigateway/apis/web/resource/serializers.py
src/dashboard/apigateway/apigateway/apis/web/resource/views.py
src/dashboard/apigateway/apigateway/apps/metrics/prometheus/dimension.py
src/dashboard/apigateway/apigateway/biz/plugin_binding.py
src/dashboard/apigateway/apigateway/biz/releaser.py
src/dashboard/apigateway/apigateway/common/error_codes.py
src/dashboard/apigateway/apigateway/common/exception_handler.py
src/dashboard/apigateway/apigateway/conf/default.py
src/dashboard/apigateway/apigateway/core/management/commands/add_stage.py
src/dashboard/apigateway/apigateway/tests/apps/metrics/prometheus/test_dimension.py
src/dashboard/apigateway/apigateway/tests/biz/test_plugin_binding.py

Fixes
- 审计日志中有 `prod:`
- 校验报错指引的链路不对
- 登录态失效填充 error.data， 包含login_url
- django command `add_stage.py` 去除对 StageSLZ的依赖
- 资源列表增加 `plugin_count` 这一列

fix(bugs): fix dashboard bugs

---

src/dashboard/apigateway/apigateway/apis/web/permission/serializers.py

fix: permission export never expired

---

src/dashboard-front/src/views/main.vue

- feat: 导航收起后 顶部颜色不对，包括顶部的项目选择的选择框是没有边框的

feat: 导航收起后 顶部颜色不对，包括顶部的项目选择的选择框是没有边框的

---

src/dashboard/apigateway/apigateway/apps/plugin/management/commands/migrate_access_strategy_user_verified.py

- 免用户认证应用白名单访问策略迁移时，如果不存在配置则清理已迁移的绑定关系

fix(migrate_access_strategy_user_verified.py): delete bk-verified-user-exempted-apps plugin binding

---

src/dashboard/apigateway/apigateway/apps/plugin/management/commands/check_migrate_access_strategy_user_verified.py
src/dashboard/apigateway/apigateway/apps/plugin/management/commands/check_migrate_plugin_binding.py

feat: add check migrate plugin binding access strategy commond

---

src/dashboard/apigateway/apigateway/apps/plugin/management/commands/check_migrate_header_rewrite.py
src/dashboard/apigateway/apigateway/core/management/commands/check_migrate_backend_config.py

add check backend and header rewrite commond

feat: add check backend and header rewrite commond

---

src/dashboard/apigateway/apigateway/apps/plugin/management/commands/check_migrate_access_strategy_user_verified.py
src/dashboard/apigateway/apigateway/apps/plugin/management/commands/check_migrate_plugin_binding.py
src/dashboard/apigateway/apigateway/core/migrations/0039_auto_update_1_13.py

- fix: 升级过程中django migration失败

fix(migration): fix dependencies of migration

---

src/dashboard-front/src/language/lang.ts
src/dashboard-front/src/views/stage/overview/detail-mode/resource-info.vue

Fixes #(issue)
- key value 的样式不对
- 新建资源校验后勾选框错乱
- 环境未发布样式应该如下
- 资源列表页，资源有更新时需要展示一个标志
- 资源版本-生成SDK：SDK版本号自动继承资源版本，并可手动修改
- 【APIgateway1.13 】查看资源详情时后端服务展示有问题

feat: 修复前端问题

---

src/dashboard/apigateway/apigateway/core/management/commands/migrate_backend.py

fix: migrate gateway backend log print

---

src/dashboard/apigateway/apigateway/core/management/commands/check_migrate_backend_config.py

fix: fix weight key err

---

src/dashboard-front/src/components/auth/index.vue
src/dashboard-front/static/login_success.html

feat: 修复登录框登录后不刷新的问题

---

src/dashboard/apigateway/apigateway/apis/web/resource_version/serializers.py
src/dashboard/apigateway/apigateway/apis/web/resource_version/views.py
src/dashboard/apigateway/apigateway/biz/released_resource.py
src/dashboard/apigateway/apigateway/biz/resource_version_diff.py
src/dashboard/apigateway/apigateway/common/release/publish.py
src/dashboard/apigateway/apigateway/core/models.py

- fix release bug
- fix resource version display

fix: fix bug

---

src/dashboard/apigateway/apigateway/fixtures/plugins.yaml

fix(fixtures/plugins.yaml): update bk-rate-limit ui

---

src/dashboard/apigateway/apigateway/biz/release.py
src/dashboard/apigateway/apigateway/conf/default.py
src/dashboard/apigateway/apigateway/controller/tasks/syncing.py
src/dashboard/apigateway/apigateway/core/management/commands/check_migrate_backend_config.py
src/dashboard/apigateway/apigateway/core/management/commands/delete_celery_task.py
src/dashboard/apigateway/apigateway/core/migrations/0039_auto_update_1_13.py
src/dashboard/apigateway/apigateway/tests/biz/test_release.py

修复1.13自测bug
- 修复历史发布日志查看报错问题
- 修复check脚本对比配置问题
- 修复环境发布状态判断有误

fix: fix 1.13 bug

---

src/dashboard/apigateway/apigateway/apis/web/gateway/serializers.py
src/dashboard/apigateway/apigateway/biz/gateway/gateway.py
src/dashboard/apigateway/apigateway/tests/apis/web/gateway/test_serializers.py
src/dashboard/apigateway/apigateway/tests/biz/gateway/test_gateway.py

fix: fix gateway get doc url

---

src/dashboard/apigateway/apigateway/conf/default.py
src/dashboard/apigateway/apigateway/controller/crds/base.py
src/dashboard/apigateway/apigateway/controller/crds/v1beta1/convertors/service.py
src/dashboard/apigateway/apigateway/tests/conftest.py
src/dashboard/apigateway/apigateway/tests/controller/crds/v1beta1/convertors/test_services.py

refactor(default.py): remove unused DEFAULT_STAGE_RATE_LIMIT_CONFIG and DEFAULT_STAGE_UPSTREAMS

---

src/dashboard/apigateway/apigateway/biz/resource/models.py
src/dashboard/apigateway/apigateway/editions/ee/apps/esb/component/views.py

fix: fix esb component

---

src/dashboard/apigateway/apigateway/apps/esb/component/filters.py
src/dashboard/apigateway/apigateway/editions/ee/apps/esb/component/views.py

esb component list update with limit/offset

fix: add esb component list limit offset

---

src/dashboard-front/src/common/menu.ts
src/dashboard-front/src/components/stage-top-bar.vue
src/dashboard-front/src/router/index.ts
src/dashboard-front/src/views/components-access/runtime-data/chart.vue
src/dashboard-front/src/views/components/plugin-manage/whitelist-table.vue

feat: 修改发布记录入口

---

src/dashboard-front/src/app.vue
src/dashboard-front/src/components/product-info.vue
src/dashboard-front/src/components/user-info.vue
src/dashboard-front/src/views/components-access/manage/index.vue

feat: 退出登陆功能 && 产品反馈

---

src/dashboard/apigateway/apigateway/biz/release.py
src/dashboard/apigateway/apigateway/biz/releaser.py
src/dashboard/apigateway/apigateway/controller/tasks/syncing.py
src/dashboard/apigateway/apigateway/tests/biz/test_releaser.py
src/dashboard/apigateway/apigateway/tests/controller/tasks/test_syncing.py

- 修复并发发布问题
- 修复revoke删除资源发布时更新环境及release状态
- 版本发布新增网关状态校验

fix: fix publishs

---

src/dashboard/apigateway/apigateway/editions/ee/apps/esb/constants.py

fix: componet path validate

---

src/esb/esb/dependencies.yaml

feat(esb/dependencies.yaml): update nodeman apis

---

src/esb/esb/components/constants.py

fix(esb/components): missing systems in constants.py

---

src/dashboard/apigateway/apigateway/apis/open/permission/serializers.py

fix dashboard resource apply validate

fix: fix dashboard resource apply validate

---

src/core-api/go.mod
src/core-api/go.sum

feat: core-api upgrade package(1.13)

feat: core-api upgrade package(1.13)

---

src/dashboard/apigateway/apigateway/biz/resource_version_diff.py
src/dashboard/apigateway/apigateway/tests/biz/test_resource_version_diff.py

fix: fix plugin diff

---

src/dashboard/apigateway/apigateway/apis/web/gateway/views.py
src/dashboard/apigateway/apigateway/common/release/publish.py
src/dashboard/apigateway/apigateway/controller/tasks/syncing.py

fix dashboard gateway active: 网关启用改为自动发布

fix: fix dashboard gateway active

---

src/dashboard/apigateway/apigateway/apps/plugin/admin.py
src/dashboard/apigateway/apigateway/core/management/commands/diff_and_make_new_release.py

fix(commands): diff_and_make_new_release.py

---

src/dashboard/apigateway/apigateway/apis/web/stage/serializers.py

fix: fix stage release status

---

src/dashboard/apigateway/apigateway/core/management/commands/diff_and_make_new_release.py
src/dashboard/apigateway/apigateway/editions/ee/data/apigw-definitions/bk-apigateway-definition.yaml
src/dashboard/apigateway/apigateway/editions/ee/data/apigw-definitions/bk-apigateway-inner-definition.yaml
src/dashboard/apigateway/apigateway/editions/ee/data/apigw-definitions/bk-default-definition.yaml
src/dashboard/apigateway/apigateway/editions/ee/data/apigw-definitions/bk-esb-buffet-definition.yaml

fix upgrade and update inner gateway version

fix: fix upgrade and update inner gateway version

---

src/dashboard/apigateway/apigateway/core/management/commands/diff_and_make_new_release.py
src/dashboard/apigateway/apigateway/core/migrations/0039_auto_update_1_13.py
src/dashboard/bin/post_migrate

fix: fix upgarade script

---

src/dashboard/apigateway/apigateway/core/management/commands/diff_and_make_new_release.py

fix(commonds): fix resource version

fix(commonds): fix resource version

---

src/dashboard/bin/start.sh

fix(dashboard/bin/start.sh): update the start command

---

src/dashboard/apigateway/apigateway/apis/web/label/views.py

fix(apis/web/label): create label return the id and name

---

src/dashboard/apigateway/apigateway/apis/web/label/views.py
src/dashboard/apigateway/apigateway/tests/apis/web/label/test_views.py

Fix create label return

---

src/dashboard/apigateway/apigateway/apis/web/resource/serializers.py
src/dashboard/apigateway/apigateway/tests/apis/web/resource/test_serializers.py

fix(resource): has_update sign true only after released

---

src/dashboard/apigateway/apigateway/apis/web/sdk/views.py
src/dashboard/apigateway/apigateway/apis/web/stage/serializers.py
src/dashboard/apigateway/apigateway/biz/releaser.py
src/dashboard/apigateway/apigateway/biz/validators.py
src/dashboard/apigateway/apigateway/locale/en/LC_MESSAGES/django.po
src/dashboard/apigateway/apigateway/tests/biz/test_releaser.py
src/dashboard/apigateway/apigateway/tests/biz/test_validators.py

- stage列表接口返回是否运行发布字段
- sdk生成失败提示优化

fix(publish): stage list add publish validate

---

src/dashboard/apigateway/apigateway/apis/web/access_log/serializers.py
src/dashboard/apigateway/apigateway/apis/web/access_log/urls.py
src/dashboard/apigateway/apigateway/apis/web/access_log/views.py
src/dashboard/apigateway/apigateway/apis/web/api_test/views.py
src/dashboard/apigateway/apigateway/biz/access_log/constants.py
src/dashboard/apigateway/apigateway/biz/access_log/log_search.py
src/dashboard/apigateway/apigateway/common/es/clients.py
src/dashboard/apigateway/apigateway/tests/common/es/test_clients.py
src/dashboard/apigateway/apigateway/utils/time.py

访问日志：
1. 增加查询条件 resource_id
2. 增加查询条件 include 和 exclude
3. 状态码 200 的时候，提示不记录响应体

refactor access_log

---

src/dashboard/apigateway/apigateway/apps/label/admin.py
src/dashboard/apigateway/apigateway/apps/monitor/admin.py
src/dashboard/apigateway/apigateway/apps/permission/admin.py
src/dashboard/apigateway/apigateway/apps/plugin/admin.py
src/dashboard/apigateway/apigateway/apps/support/admin.py
src/dashboard/apigateway/apigateway/core/admin.py
src/dashboard/apigateway/apigateway/core/models.py
src/dashboard/apigateway/apigateway/iam/admin.py

优化django admin管理后台的filter过滤搜索条件

refactor: refine admin filters

---

src/core-api/cmd/init.go
src/core-api/pkg/logging/init.go
src/core-api/pkg/middleware/logger.go
src/core-api/pkg/sentry/sentry.go

fix core-api sentry

---

src/dashboard/apigateway/apigateway/apis/open/esb/permission/views.py
src/dashboard/apigateway/apigateway/apis/open/esb/system/views.py
src/dashboard/apigateway/apigateway/apis/open/gateway/views.py
src/dashboard/apigateway/apigateway/apis/open/permission/views.py
src/dashboard/apigateway/apigateway/apis/open/released/views.py
src/dashboard/apigateway/apigateway/apis/open/stage/views.py
src/dashboard/apigateway/apigateway/apis/open/support/views.py
src/dashboard/apigateway/apigateway/common/permissions/permissions.py
src/dashboard/apigateway/apigateway/editions/ee/data/apigw-definitions/bk-apigateway-definition.yaml
src/dashboard/apigateway/apigateway/tests/apis/open/esb/permission/test_views.py
src/dashboard/apigateway/apigateway/tests/apis/open/gateway/test_views.py
src/dashboard/apigateway/apigateway/tests/apis/open/permission/test_views.py
src/dashboard/apigateway/apigateway/tests/apis/open/released/test_views.py
src/dashboard/apigateway/apigateway/tests/apis/open/stage/test_views.py
src/dashboard/apigateway/apigateway/tests/apis/open/support/test_views.py

fix(open api): add request_from_gateway_required for all open apis

---

src/dashboard/apigateway/apigateway/apis/web/resource_version/serializers.py
src/dashboard/apigateway/apigateway/apis/web/resource_version/views.py
src/dashboard/apigateway/apigateway/tests/apis/web/resource_version/test_serializers.py

fix get stage resource_version

fix(resource_version): fix get stage resource_version

---

src/dashboard/apigateway/apigateway/apis/web/stage/serializers.py
src/dashboard/apigateway/apigateway/biz/released_resource.py
src/dashboard/apigateway/apigateway/tests/biz/test_released_resource.py

fix(stage): fix upgrade 1.13

---

src/dashboard-front/src/constant/config.ts

feat(fe/constant): add UPGRADE_TO_113_TIP to fe constant/config.ts

---

src/dashboard/apigateway/apigateway/apis/web/resource_version/serializers.py
src/dashboard/apigateway/apigateway/apis/web/resource_version/views.py
src/dashboard/apigateway/apigateway/tests/apis/web/resource_version/test_serializers.py
src/dashboard/apigateway/apigateway/tests/apis/web/resource_version/test_views.py

feat(resource_version): add schema_version

---

src/dashboard-front/src/views/basic-info/common/type.ts
src/dashboard-front/src/views/basic-info/index.vue

- feat: 修复基本信息编辑时,弹框中维护人员不显示的问题

feat: 修复基本信息编辑时,弹框中维护人员不显示的问题

---

src/core-api/pkg/api/microgateway/publish_event.go
src/core-api/pkg/database/dao/publish_event.go
src/core-api/pkg/service/publish_event.go

fix(event): add event ts

---

src/dashboard/apigateway/apigateway/core/migrations/0039_auto_update_1_13.py
src/dashboard/bin/post_migrate

清理无用celery tasks

---

src/dashboard/apigateway/apigateway/biz/resource/resource.py

fix(resource/list): use icontains to query name/path

---

src/dashboard/apigateway/apigateway/apps/permission/tasks.py

fix(permission/tasks.py): fix wrong link in mail

---

src/dashboard/apigateway/apigateway/apis/web/resource/serializers.py

fix(apis/web/resource): max_resource_per_gateway_whitelist not working

---

src/dashboard/apigateway/apigateway/apis/open/stage/serializers.py
src/dashboard/apigateway/apigateway/tests/apis/open/stage/test_views.py

feat(open/stage): support backends

feat(open/stage): support backends

---

src/dashboard/apigateway/.importlinter
src/dashboard/apigateway/apigateway/apis/web/stage/serializers.py
src/dashboard/apigateway/apigateway/biz/release.py
src/dashboard/apigateway/apigateway/biz/releaser.py
src/dashboard/apigateway/apigateway/controller/tasks/__init__.py
src/dashboard/apigateway/apigateway/controller/tasks/release.py
src/dashboard/apigateway/apigateway/core/managers.py
src/dashboard/apigateway/apigateway/tests/biz/test_releaser.py
src/dashboard/apigateway/apigateway/tests/conftest.py

- 修复发布更新相关数据逻辑，确保最终发布成功之后才更新
- 环境列表接口新增正在发布的版本字段

fix release update

---

.github/workflows/dashboard.yml
src/dashboard/Makefile

ci(lint-check): fix lint-check not exit in github action

---

src/dashboard/apigateway/apigateway/biz/backend.py

fix(backend): fix backend trigger publish

---

.github/workflows/dashboard.yml
src/dashboard/Makefile
src/dashboard/apigateway/apigateway/biz/backend.py

backport v1.13.5

---

src/dashboard/apigateway/apigateway/apis/web/resource_version/serializers.py
src/dashboard/apigateway/apigateway/apis/web/resource_version/views.py
src/dashboard/apigateway/apigateway/tests/apis/web/resource_version/test_serializers.py
src/dashboard/apigateway/apigateway/tests/apis/web/resource_version/test_views.py

fix(resource_version):增加创建人名称

---

src/dashboard-front/src/app.vue
src/dashboard/apigateway/apigateway/apis/web/permission/views.py
src/dashboard/apigateway/apigateway/apis/web/resource_version/serializers.py
src/dashboard/apigateway/apigateway/apis/web/resource_version/views.py
src/dashboard/apigateway/apigateway/tests/apis/web/resource_version/test_serializers.py
src/dashboard/apigateway/apigateway/tests/apis/web/resource_version/test_views.py

backport 20240614 for release/1.13

---

src/dashboard/apigateway/apigateway/apis/web/plugin/views.py
src/dashboard/apigateway/apigateway/common/plugin/plugin_checkers.py
src/dashboard/apigateway/apigateway/tests/apis/web/plugin/test_views.py

- [√] 代码风格检查通过 (code style check passed)
-  [√] 本地开发联调环境验证通过 (local development environment verification passed)

ft(plugin/validator):header rewrite check case insensitive repeat

---

src/dashboard-front/src/components/member-select/index.tsx
src/dashboard-front/src/store/staff.ts

feat: 修复编辑基础信息弹框中维护人员不回显的问题

---

src/dashboard/Dockerfile

fix(dockerfile): lock the pip version to 23.0.1

---

src/esb/bin/post_migrate

删除 src/esb/bin/post_migrate (并没有什么用）

feat(esb): remove bin/post_migrate

---

src/dashboard/apigateway/apigateway/apis/web/resource/views.py
src/dashboard/apigateway/apigateway/tests/apis/web/resource/test_views.py

- [√] 代码风格检查通过 (code style check passed)
- [√] 本地开发联调环境验证通过 (local development environment verification passed)

fix(ResourceLabel): mark resource as updated if labels changed

---

src/dashboard/apigateway/apigateway/apis/web/gateway/serializers.py
src/dashboard/apigateway/apigateway/tests/apis/web/gateway/test_serializers.py

feat(api/web/gateway): GatewayRetrieveOutputSLZ add updated_time

---

src/dashboard/apigateway/apigateway/apis/web/resource_version/serializers.py
src/dashboard/apigateway/apigateway/apis/web/resource_version/urls.py
src/dashboard/apigateway/apigateway/apis/web/resource_version/views.py
src/dashboard/apigateway/apigateway/tests/apis/web/resource_version/test_views.py
src/dashboard/apigateway/apigateway/tests/utils/test_version.py
src/dashboard/apigateway/apigateway/utils/version.py

feat(resource_version) add next-version api

---

src/dashboard/apigateway/apigateway/fixtures/plugins.yaml

fix(fixtures/plugins.yaml): update rate-limit form size for app_code

---

src/dashboard/apigateway/apigateway/biz/resource/importer/parser.py
src/dashboard/apigateway/apigateway/biz/resource/importer/schemas/openapi_2.0_schema.json
src/dashboard/apigateway/apigateway/biz/resource/importer/schemas/openapi_3.0_schema.json
src/dashboard/apigateway/apigateway/biz/resource/importer/schemas/openapi_3.1_schema.json

fix(openapi): fix operationID validate

fix(openapi): fix operationID validate

---

src/dashboard/bin/start.sh

去掉 src/dashboard/start.sh 多余的timeout指令

fix:timeout

---

src/dashboard/apigateway/apigateway/editions/ee/apps/esb/component/serializers.py
src/dashboard/apigateway/apigateway/editions/ee/apps/esb/component/tasks.py
src/dashboard/apigateway/apigateway/editions/ee/apps/esb/component/urls.py
src/dashboard/apigateway/apigateway/editions/ee/apps/esb/component/views.py
src/dashboard/apigateway/apigateway/editions/ee/tests/apps/esb/component/test_tasks.py
src/dashboard/apigateway/apigateway/editions/ee/tests/apps/esb/component/test_views.py

feat: esb sync add status query api

---

src/dashboard/apigateway/apigateway/editions/ee/apps/esb/component/urls.py
src/dashboard/apigateway/apigateway/editions/ee/tests/apps/esb/component/test_views.py

fix:(esb_component)url

---

src/dashboard/apigateway/apigateway/conf/celery_conf.py
src/dashboard/apigateway/apigateway/conf/default.py
src/dashboard/apigateway/apigateway/controller/tasks/__init__.py
src/dashboard/apigateway/apigateway/controller/tasks/clean_task.py
src/dashboard/apigateway/apigateway/tests/controller/tasks/test_clean_task.py

add delete resource_version task

feat(task): add delete resource_version task

---

src/dashboard/apigateway/apigateway/apis/web/backend/serializers.py
src/dashboard/apigateway/apigateway/apis/web/backend/views.py
src/dashboard/apigateway/apigateway/biz/backend.py
src/dashboard/apigateway/apigateway/tests/apis/web/backend/test_views.py

backend update api return updated_stages

---

src/dashboard/apigateway/apigateway/apis/web/release/views.py

resource info add name and desc

feat(apis/web/release): resource info add name and desc

---

src/dashboard/apigateway/apigateway/apis/web/access_log/urls.py
src/dashboard/apigateway/apigateway/apis/web/access_log/views.py
src/dashboard/apigateway/apigateway/tests/apis/web/access_log/test_views.py

add log search without permission
- [] PR 中包含单元测试 (include unit test)

feat:add log search via request_id

---

src/dashboard/apigateway/apigateway/apis/web/access_log/urls.py
src/dashboard/apigateway/apigateway/apis/web/access_log/views.py
src/dashboard/apigateway/apigateway/tests/apis/web/access_log/test_views.py

feat:logs export

---

src/dashboard/apigateway/apigateway/apis/open/resource/serializers.py
src/dashboard/apigateway/apigateway/apis/open/resource/views.py
src/dashboard/apigateway/apigateway/apis/web/resource/serializers.py
src/dashboard/apigateway/apigateway/apis/web/resource/views.py
src/dashboard/apigateway/apigateway/biz/resource/importer/schema.py
src/dashboard/apigateway/apigateway/tests/apis/open/resource/test_views.py
src/dashboard/apigateway/apigateway/tests/apis/web/resource/test_serializers.py
src/dashboard/apigateway/apigateway/tests/apis/web/resource/test_views.py
src/dashboard/apigateway/apigateway/tests/conftest.py

fix openapi resource import validate

fix(openapi/resource): fix resource import validate

---

src/core-api/config.yaml.tpl
src/core-api/go.mod
src/core-api/go.sum
src/core-api/pkg/cacheimpls/app_gateway_permission_test.go
src/core-api/pkg/cacheimpls/app_resource_permission_test.go
src/core-api/pkg/cacheimpls/gateway_test.go
src/core-api/pkg/cacheimpls/init.go
src/core-api/pkg/cacheimpls/jwt_public_key_test.go
src/core-api/pkg/cacheimpls/microgateway_credentials_test.go
src/core-api/pkg/cacheimpls/microgateway_test.go
src/core-api/pkg/cacheimpls/release_history_test.go
src/core-api/pkg/cacheimpls/release_test.go
src/core-api/pkg/cacheimpls/resource_version_mapping_test.go
src/core-api/pkg/cacheimpls/stage_test.go
src/core-api/pkg/config/config.go
src/core-api/pkg/database/mysql.go
src/core-api/pkg/database/utils.go
src/core-api/pkg/middleware/logger.go
src/core-api/pkg/middleware/request_id.go

core-api fix cache

---

src/dashboard/apigateway/apigateway/apis/web/api_test/filters.py
src/dashboard/apigateway/apigateway/apis/web/api_test/serializers.py
src/dashboard/apigateway/apigateway/apis/web/api_test/views.py

fix:api_test_history params

---

src/dashboard/apigateway/apigateway/apis/web/api_test/filters.py
src/dashboard/apigateway/apigateway/apis/web/api_test/views.py

fix:api_test_debug history

---

src/core-api/config.yaml.tpl
src/core-api/go.mod
src/core-api/go.sum
src/core-api/pkg/cacheimpls/app_gateway_permission_test.go
src/core-api/pkg/cacheimpls/app_resource_permission_test.go
src/core-api/pkg/cacheimpls/gateway_test.go
src/core-api/pkg/cacheimpls/init.go
src/core-api/pkg/cacheimpls/jwt_public_key_test.go
src/core-api/pkg/cacheimpls/microgateway_credentials_test.go
src/core-api/pkg/cacheimpls/microgateway_test.go
src/core-api/pkg/cacheimpls/release_history_test.go
src/core-api/pkg/cacheimpls/release_test.go
src/core-api/pkg/cacheimpls/resource_version_mapping_test.go
src/core-api/pkg/cacheimpls/stage_test.go
src/core-api/pkg/config/config.go
src/core-api/pkg/database/mysql.go
src/core-api/pkg/database/utils.go
src/core-api/pkg/middleware/logger.go
src/core-api/pkg/middleware/request_id.go

core-api: fix cache

---

src/dashboard/apigateway/apigateway/apis/web/resource/views.py
src/dashboard/apigateway/apigateway/biz/resource_doc/importer/generators.py

refactor:Optimized export file

---

src/dashboard/apigateway/apigateway/apis/web/api_test/views.py

fix:params

---

src/dashboard/apigateway/apigateway/apis/web/access_log/views.py
src/dashboard/apigateway/apigateway/tests/apis/web/access_log/test_views.py

Fix :log_export

---

src/dashboard/apigateway/apigateway/apis/web/release/serializers.py
src/dashboard/apigateway/apigateway/apis/web/release/views.py
src/dashboard/apigateway/apigateway/biz/released_resource.py

fix(api/web/release): fix api test get resource list

fix(api/web/release): fix api test get resource list

---

src/dashboard/apigateway/apigateway/apis/web/resource_version/views.py

fix:serializer_class

---

src/dashboard/apigateway/apigateway/editions/ee/apps/esb/component/tasks.py
src/dashboard/apigateway/apigateway/editions/ee/apps/esb/management/commands/sync_to_gateway_and_release.py

fix:call method params

---

src/dashboard-front/src/language/lang.ts

fix(src/language/lang.ts): logo name en

---

src/dashboard-front/src/views/apigwDocs/components/doc.vue
src/dashboard-front/yarn.lock

修复网关API文档认证文本错误 [TAPD](https://tapd.woa.com/tapd_fe/69995498/story/detail/1069995498119113965)

Hotfix 修复网关API文档认证文本错误

---

src/dashboard-front/src/views/apigwDocs/components/doc.vue

hotfix: 修复网关API文档认证文本错误 [TAPD](https://tapd.woa.com/tapd_fe/69995498/story/detail/1069995498119113965)

hotfix: 修复网关API文档认证文本错误

---

src/dashboard-front/src/views/apigwDocs/components/doc.vue

fix(components/doc.vue): typo

---

src/dashboard/apigateway/apigateway/apis/web/resource/serializers.py
src/dashboard/apigateway/apigateway/apis/web/resource/views.py
src/dashboard/apigateway/apigateway/biz/resource/resource.py
src/dashboard/apigateway/apigateway/tests/apis/web/resource/test_views.py

feat:batch_label

---

src/dashboard/apigateway/apigateway/apis/web/api_test/views.py

fix:api_test curl remove \n

---

src/dashboard/apigateway/apigateway/apis/web/resource_version/serializers.py
src/dashboard/apigateway/apigateway/tests/apis/web/resource_version/test_serializers.py

fix(api/web/resource_verson): fix stage plugin

---

src/dashboard/apigateway/apigateway/biz/resource_doc/importer/parsers.py

fix(biz/resource_doc/parsers): fix ._ file import

---

src/dashboard/apigateway/apigateway/apis/web/constants.py
src/dashboard/apigateway/apigateway/apis/web/resource_version/serializers.py
src/dashboard/apigateway/apigateway/conf/default.py
src/dashboard/apigateway/apigateway/tests/apis/web/resource_version/test_serializers.py
src/dashboard/apigateway/apigateway/tests/conftest.py

feat:plugin merge rules

---

src/dashboard/apigateway/apigateway/apis/web/resource/serializers.py
src/dashboard/apigateway/apigateway/biz/resource/importer/parser.py
src/dashboard/apigateway/apigateway/biz/resource/importer/schema.py
src/dashboard/apigateway/apigateway/biz/resource_doc/importer/parsers.py
src/dashboard/apigateway/apigateway/tests/biz/resource/importer/test_schema.py

fix(resource/import): fix doc import

---

src/dashboard/apigateway/apigateway/apis/open/esb/permission/views.py
src/dashboard/apigateway/apigateway/tests/apis/open/esb/permission/test_views.py

feat:esb apply permission response return record id

---

src/dashboard-front/src/views/components-access/runtime-data/detail.vue

fix(esb/runtime-data): fix column display

---

src/dashboard/apigateway/apigateway/apis/web/permission/serializers.py
src/dashboard/apigateway/apigateway/apis/web/permission/urls.py
src/dashboard/apigateway/apigateway/apis/web/permission/views.py
src/dashboard/apigateway/apigateway/apps/permission/managers.py
src/dashboard/apigateway/apigateway/tests/apis/web/permission/test_serializers.py
src/dashboard/apigateway/apigateway/tests/apis/web/permission/test_views.py

opt(api/web/permissions): permission display and batch apply

---

src/dashboard/apigateway/apigateway/apis/web/sdk/views.py
src/dashboard/apigateway/apigateway/apps/support/api_sdk/distributors/bkrepo.py
src/dashboard/apigateway/apigateway/apps/support/api_sdk/distributors/maven.py
src/dashboard/apigateway/apigateway/apps/support/api_sdk/distributors/pypi.py
src/dashboard/apigateway/apigateway/apps/support/api_sdk/exceptions.py
src/dashboard/apigateway/apigateway/apps/support/api_sdk/managers/base.py
src/dashboard/apigateway/apigateway/apps/support/api_sdk/models.py

feat(sdk/create): fix config validate

feat(sdk/create): fix config validate

---

src/dashboard/apigateway/apigateway/apis/open/permission/serializers.py
src/dashboard/apigateway/apigateway/apis/open/permission/urls.py
src/dashboard/apigateway/apigateway/apis/open/permission/views.py
src/dashboard/apigateway/apigateway/data/apigw-definitions/bk-apigateway-inner-resources.yaml

open api add batch apply permisson api

feat(apis/open): add batch apply permission  api

---

src/dashboard-front/src/components/ag-editor.vue
src/dashboard-front/src/views/online-debug/components/request-record.vue
src/dashboard-front/src/views/operate-data/access-log/index.vue

- 【APIgateway1.14 】全屏功能存在异常的情况
- 【APIgateway1.14 】请求记录中根据资源名称搜索功能失效
- 【APIgateway1.14 】光标功能存在失效的情况

fix: 1.14问题修复

---

src/dashboard-front/.eslintignore
src/dashboard-front/src/views/resource/setting/import.vue

fix：1.14问题修复 && eslint

---

src/dashboard/apigateway/apigateway/apis/web/metrics/serializers.py
src/dashboard/apigateway/apigateway/apis/web/metrics/views.py
src/dashboard/apigateway/apigateway/apps/metrics/constants.py
src/dashboard/apigateway/apigateway/apps/metrics/prometheus/dimension.py
src/dashboard/apigateway/apigateway/tests/apis/web/metrics/test_serializers.py
src/dashboard/apigateway/apigateway/tests/apis/web/metrics/test_views.py
src/dashboard/apigateway/apigateway/tests/apps/metrics/prometheus/test_dimension.py
src/dashboard/apigateway/apigateway/tests/apps/metrics/prometheus/test_statistics.py

feat: 1.15  new metrics apis

---

src/dashboard/apigateway/apigateway/apis/web/docs/gateway/resource/serializers.py

fix(api/web): fix doc get release resources

fix(api/web): fix doc get release resources

---

src/dashboard/apigateway/apigateway/apis/web/docs/gateway/resource/serializers.py

fix(1.14/api/web): fix doc get release resources

fix(1.14/api/web): fix doc get release resources

---

src/dashboard/apigateway/apigateway/apis/open/resource/views.py
src/dashboard/apigateway/apigateway/apis/web/resource/views.py
src/dashboard/apigateway/apigateway/biz/resource/importer/schemas/openapi_3.0_schema.json

 fix(1.14/api/web):fix openapi schema

---

src/dashboard/apigateway/apigateway/apis/web/docs/gateway/resource/views.py
src/dashboard/apigateway/apigateway/apis/web/release/views.py
src/dashboard/apigateway/apigateway/biz/released_resource.py
src/dashboard/apigateway/apigateway/biz/resource_label.py
src/dashboard/apigateway/apigateway/tests/biz/test_resource_label.py

fix get release resoruce labels

fix(web/api): fix get release resources labels

---

src/dashboard/apigateway/apigateway/apis/open/resource/views.py
src/dashboard/apigateway/apigateway/apis/web/resource/views.py
src/dashboard/apigateway/apigateway/biz/resource/importer/schemas/openapi_3.0_schema.json

fix(api/web): fix openapi schema

---

src/dashboard-front/src/components/resource-detail/index.vue
src/dashboard-front/src/css/common.css
src/dashboard-front/src/language/lang.ts
src/dashboard-front/src/views/resource/setting/comps/front-config.vue
src/dashboard-front/src/views/resource/setting/detail.vue
src/dashboard-front/src/views/stage/overview/detail-mode/resource-details.vue

feat: 资源新增 enable_websocket 字段

---

src/dashboard-front/src/views/apigwDocs/components/doc.vue

fix: 修复网关文档“是否需申请权限”文本

---

src/dashboard-front/src/views/resource/setting/comps/table-res-to-action.vue
src/dashboard-front/src/views/resource/setting/import.vue

更改资源配置确认页表格空状态 [TAPD](https://tapd.woa.com/tapd_fe/69995498/bug/detail/1069995498130084473)

fix: 更改资源配置确认页表格空状态

---

src/dashboard/apigateway/apigateway/biz/resource_version_diff.py
src/dashboard/apigateway/apigateway/tests/apis/web/resource_version/test_views.py

fix(api/web): fix diff add websocket

fix(api/web): fix diff add websocket

---

src/dashboard-front/src/components/ag-editor.vue
src/dashboard-front/src/views/resource/setting/import.vue

feat: 新增编辑器错误添加下划波浪线的功能

---

src/dashboard-front/src/language/lang.ts
src/dashboard-front/src/views/resource/setting/comps/select-check-box.vue
src/dashboard-front/src/views/resource/setting/index.vue

fix: 修复修改标签名后资源列表不刷新数据的问题

---

src/dashboard/apigateway/apigateway/apis/web/permission/views.py
src/dashboard/apigateway/apigateway/tests/apis/web/permission/test_serializers.py

fix(web/api): fix permissions id

fix(web/api): fix permissions id

---

src/dashboard/apigateway/apigateway/apis/web/permission/serializers.py
src/dashboard/apigateway/apigateway/apis/web/permission/views.py

fix(web/api): fix permission export

---

src/dashboard/Dockerfile

build(dockerfile): use kona jdk

---

src/dashboard-front/src/views/resource/setting/import.vue

fix: 去掉导入结果页多余按钮

---

src/dashboard/apigateway/apigateway/apis/open/permission/views.py
src/dashboard/apigateway/apigateway/apis/web/permission/serializers.py
src/dashboard/apigateway/apigateway/apis/web/permission/views.py

fix permission apply and export

fix(permission): fix permission apply and export

---

src/dashboard/apigateway/apigateway/controller/tasks/release.py

fix(release): fix release doc update

fix(1.14/release): fix release doc update

---

src/dashboard/apigateway/apigateway/controller/tasks/release.py

fix(release): fix release doc update

fix(release): fix release doc update

---

src/dashboard/apigateway/apigateway/templates/api_sdk/zh-hans/java_sdk_doc.md

fix(sdk/doc): fix java sdk doc

fix(sdk/doc): fix java sdk doc

---

src/dashboard-front/src/language/lang.ts
src/dashboard-front/src/views/stage/overview/comps/edit-stage-sideslider.vue
src/dashboard-front/src/views/stage/overview/detail-mode/resource-info.vue

feat: 增加环境资源信息slider的查看态

---

src/dashboard/apigateway/apigateway/apps/permission/managers.py
src/dashboard/apigateway/apigateway/tests/apps/permission/test_managers.py

fix(api/open): fix paas permission renew

fix(api/open): fix paas permission renew

---

src/dashboard/apigateway/apigateway/biz/resource/importer/schemas/openapi_2.0_schema.json
src/dashboard/apigateway/apigateway/biz/resource/importer/schemas/openapi_3.0_schema.json
src/dashboard/apigateway/apigateway/biz/resource/importer/schemas/openapi_3.1_schema.json
src/dashboard/apigateway/apigateway/tests/biz/resource/importer/test_openapi.py

fix(api/web/resource): fix openapi import support websocket

fix(api/web/resource): fix openapi import support websocket

---

src/dashboard/apigateway/apigateway/biz/releaser.py
src/dashboard/apigateway/apigateway/controller/tasks/release.py
src/dashboard/apigateway/apigateway/core/managers.py
src/dashboard/apigateway/apigateway/tests/biz/test_releaser.py
src/dashboard/apigateway/apigateway/tests/controller/conftest.py
src/dashboard/apigateway/apigateway/tests/controller/tasks/test_release.py
src/dashboard/apigateway/apigateway/tests/core/test_managers.py

fix(publish): fix publish release

fix(publish): fix publish release

---

src/dashboard/apigateway/apigateway/biz/releaser.py
src/dashboard/apigateway/apigateway/controller/tasks/release.py
src/dashboard/apigateway/apigateway/core/managers.py
src/dashboard/apigateway/apigateway/tests/biz/test_releaser.py
src/dashboard/apigateway/apigateway/tests/controller/conftest.py
src/dashboard/apigateway/apigateway/tests/controller/tasks/test_release.py
src/dashboard/apigateway/apigateway/tests/core/test_managers.py

fix(1.14/publish): fix publish release

fix(1.14/publish): fix publish release

---

src/dashboard/apigateway/apigateway/fixtures/plugins.yaml

fix:mock plugin name

---

src/dashboard/apigateway/apigateway/data/version_log/CHANGELOG_en.md

fix(version_log): 1.14 tag date (#846)

---

src/dashboard/apigateway/apigateway/data/version_log/CHANGELOG_en.md

fix(version_log): update change log en

---

src/dashboard/apigateway/apigateway/apis/web/docs/gateway/resource/views.py
src/dashboard/apigateway/apigateway/apis/web/release/views.py
src/dashboard/apigateway/apigateway/biz/released_resource.py
src/dashboard/apigateway/apigateway/biz/resource_label.py
src/dashboard/apigateway/apigateway/tests/biz/test_resource_label.py

fix(1.14/api/web): fix get release resource labels

---

src/dashboard-front/src/views/online-debug/index.vue

fix: 在线调试环境切换问题修复

---

src/dashboard-front/package.json
src/dashboard-front/yarn.lock

deps(release-note): 更新版本日志组件

---

src/dashboard-front/src/language/lang.ts
src/dashboard-front/src/views/apiDocs/components/component-searcher.vue
src/dashboard-front/src/views/apiDocs/index.vue
src/dashboard-front/src/views/resource/version/components/createSdk.vue

fix: 修复组件sdk不能下载和golang选项缺失的问题

---

src/dashboard-front/src/views/resource/setting/import.vue

fix: 修复导入资源的文档生成传参问题

---

src/dashboard-front/src/http/stage.ts
src/dashboard-front/src/views/stage/overview/comps/edit-stage-sideslider.vue
src/dashboard-front/src/views/stage/overview/detail-mode/resource-info.vue

feat: 增加被查看的后端服务高亮功能；修复请求url错误；

---

src/dashboard-front/src/views/online-debug/components/response-content.vue

feat: 在线调试展示 Headers

---

src/dashboard-front/src/components/ag-editor.vue
src/dashboard-front/src/views/online-debug/components/doc.vue

fix: 全屏状态下复制功能修复&资源文档取值字段修改

---

src/dashboard-front/src/views/backend-service/add.vue
src/dashboard-front/src/views/resource/setting/index.vue
src/dashboard-front/src/views/stage/overview/comps/edit-stage-sideslider.vue

fix: 资源配置批操作修改&加权轮询控件调整

---

src/dashboard/apigateway/apigateway/apis/web/docs/gateway/resource/doc/views.py
src/dashboard/apigateway/apigateway/tests/apis/web/docs/gateway/resource/doc/test_views.py

fix(1.14/api/web): fix get resource doc

fix(1.14/api/web): fix get resource doc

---

src/dashboard/apigateway/apigateway/apis/web/docs/gateway/resource/doc/views.py
src/dashboard/apigateway/apigateway/tests/apis/web/docs/gateway/resource/doc/test_views.py

fix(api/web): fix get resource doc

fix(api/web): fix get resource doc

---

src/dashboard/apigateway/apigateway/apps/plugin/constants.py
src/dashboard/apigateway/apigateway/fixtures/plugins.yaml

feat:api-breaker plugin

---

src/dashboard/apigateway/apigateway/apis/web/resource_version/serializers.py

fix(1.14/api/web): fix get stage plugins

fix(1.14/api/web): fix get stage plugins

---

src/dashboard-front/src/language/lang.ts
src/dashboard-front/src/views/components/plugin-manage/config-display-table-generic.vue
src/dashboard-front/src/views/components/plugin-manage/config-display-table-header-rewrite.vue
src/dashboard-front/src/views/components/plugin-manage/config-display-table-ip-restriction.vue
src/dashboard-front/src/views/components/plugin-manage/config-display-table-rate-limit.vue
src/dashboard-front/src/views/components/plugin-manage/config-display-table.vue
src/dashboard-front/src/views/components/plugin-manage/index.vue
src/dashboard-front/src/views/components/plugin-manage/plugin-info.vue
src/dashboard-front/src/views/components/plugin-manage/types.ts
src/dashboard-front/src/views/resource/setting/index.vue
src/dashboard-front/src/views/stage/overview/detail-mode/resource-details.vue

feat: 插件使用示例&切换样式&展示态优化

---

src/dashboard-front/index.html
src/dashboard-front/src/constant/config.ts

feat: 规范化文档中心跳转链接

---

src/dashboard-front/src/views/components/plugin-manage/plugin-info.vue

fix: 修复插件示例换行符展示问题

---

src/dashboard-front/src/components/resource-detail/index.vue
src/dashboard-front/src/language/lang.ts
src/dashboard-front/src/views/components/plugin-manage/config-display-table-generic.vue
src/dashboard-front/src/views/components/plugin-manage/config-display-table-header-rewrite.vue
src/dashboard-front/src/views/components/plugin-manage/config-display-table-ip-restriction.vue
src/dashboard-front/src/views/components/plugin-manage/config-display-table-rate-limit.vue
src/dashboard-front/src/views/components/plugin-manage/config-display-table.vue
src/dashboard-front/src/views/resource/version/components/resourceDetail.vue

feat: 应用展示表格到资源版本对比&修复插件配置展示表格中键名对应翻译缺失的问题

---

src/dashboard-front/src/views/resource/setting/index.vue

fix: 修复编辑标签后表格宽度自动复原的问题

---

src/dashboard-front/src/views/home.vue

[tapd](https://tapd.woa.com/tapd_fe/69995498/story/detail/1069995498117183056)

fix: 修复窄屏下主页按钮样式错误的问题

---

src/dashboard-front/src/components/language-toggle.vue
src/dashboard-front/src/components/product-info.vue
src/dashboard-front/src/components/user-info.vue

[TAPD](https://tapd.woa.com/tapd_fe/69995498/story/detail/1069995498119747426)

fix: 修复顶栏下拉菜单在点击图标后消失的问题

---

src/dashboard-front/src/app.vue
src/dashboard-front/src/components/online-test-top.vue
src/dashboard-front/src/components/stage-top-bar.vue
src/dashboard-front/src/views/permission/record/index.vue
src/dashboard-front/src/views/resource/setting/comps/resource-setting-top-bar.vue
src/dashboard-front/src/views/resource/setting/index.vue

fix: 修复1366宽度下部分页面出现横向滚动条及样式错乱的问题

---

src/dashboard-front/index.html
src/dashboard-front/src/app.vue
src/dashboard-front/types/global.d.ts

fix: 修复文档中心链接

---

src/dashboard-front/src/views/components/plugin-manage/index.vue

fix: 修复插件首字母取值

---

src/dashboard/apigateway/apigateway/fixtures/plugins.yaml

fix(fixtures/plugins.yaml): update plugin notes and examples

---

src/dashboard-front/src/views/components/plugin-manage/config-display-table-rate-limit.vue

fix: 修复频率控制插件展示问题

---

src/dashboard-front/src/views/permission/app/index.vue

fix: 规范化主动授权抽屉离开提示

---

src/dashboard-front/src/views/components/plugin-manage/config-display-table-header-rewrite.vue

fix: 修复header-rewrite插件展示问题

---

src/dashboard/apigateway/apigateway/templates/api_sdk/en/golang_sdk_doc.md
src/dashboard/apigateway/apigateway/templates/api_sdk/en/golang_sdk_usage_example.md
src/dashboard/apigateway/apigateway/templates/api_sdk/en/golang_sdk_usage_example_bkapi.md
src/dashboard/apigateway/apigateway/templates/api_sdk/zh-hans/golang_sdk_doc.md
src/dashboard/apigateway/apigateway/templates/api_sdk/zh-hans/golang_sdk_usage_example.md
src/dashboard/apigateway/apigateway/templates/api_sdk/zh-hans/golang_sdk_usage_example_bkapi.md

feat(api/web): add golang sdk use doc

feat(api/web): add golang sdk use doc

---

src/dashboard/apigateway/apigateway/biz/validators.py
src/dashboard/apigateway/apigateway/common/release/publish.py
src/dashboard/apigateway/apigateway/tests/common/release/test_publish.py
src/dashboard/apigateway/apigateway/tests/conftest.py

feat(publish): resource_verison v1 can't be publish

feat(publish): resource_verison v1 can't be publish

---

src/dashboard/apigateway/apigateway/apis/web/plugin/convertor.py
src/dashboard/apigateway/apigateway/apps/plugin/constants.py
src/dashboard/apigateway/apigateway/common/plugin/plugin_checkers.py
src/dashboard/apigateway/apigateway/fixtures/plugins.yaml
src/dashboard/apigateway/apigateway/tests/apis/web/plugin/test_convertor.py
src/dashboard/apigateway/apigateway/tests/common/plugin/test_plugin_checkers.py

feat:request_validation

---

src/dashboard-front/package.json
src/dashboard-front/src/views/permission/app/index.vue
src/dashboard-front/src/views/permission/app/types.ts
src/dashboard-front/yarn.lock

deps(bkui-vue): 更新bkui到2.0.1-beta.70.search.1修复SearchSelect组件bug

---

src/dashboard-front/src/views/apiDocs/components/lang-selector.vue
src/dashboard-front/src/views/apiDocs/components/sdk-instruction-content.vue
src/dashboard-front/src/views/apiDocs/types.d.ts

feat: 添加golang的sdk使用说明

---

src/dashboard-front/src/language/lang.ts
src/dashboard-front/src/views/stage/overview/comps/release-sideslider.vue

feat: 禁止选中并发布v1资源版本

---

src/dashboard-front/src/hooks/sidebar.ts

fix(hooks/sidebar.ts): 修复确认离开已编辑表单的页面后仍出现提示弹窗的问题

---

src/dashboard-front/src/views/resource/setting/comps/back-config.vue
src/dashboard-front/src/views/resource/setting/edit.vue

fix: 修复编辑资源时没修改表单再离开时仍弹出提示的问题

---

src/dashboard-front/src/constant/config.ts

fix(fe/config.ts): fix doc urls

---

src/esb/esb/conf/default.py

fix(esb): make pymysql as mysqldb

---

src/dashboard-front/src/components/resource-detail/index.vue

fix: 修复版本对比中插件差异高亮问题

---

src/dashboard/apigateway/apigateway/apis/open/resource/serializers.py
src/dashboard/apigateway/apigateway/apis/open/resource/views.py
src/dashboard/apigateway/apigateway/biz/resource/importer/openapi.py
src/dashboard/apigateway/apigateway/tests/apis/open/resource/test_views.py
src/dashboard/apigateway/apigateway/tests/conftest.py

fix(api/open): fix resource sync

fix(1.14/api/open): fix resource sync

---

src/dashboard-front/src/views/components/plugin-manage/config-display-table-generic.vue
src/dashboard-front/src/views/components/plugin-manage/config-display-table-header-rewrite.vue
src/dashboard-front/src/views/components/plugin-manage/config-display-table-status-rewrite.vue
src/dashboard-front/src/views/components/plugin-manage/config-display-table.vue
src/dashboard-front/src/views/components/plugin-manage/types.ts

fix: StatusRewrite插件表格&配置多行文本展示

---

src/dashboard-front/src/components/version-diff/index.vue

fix: 修复资源版本对比显示异常的问题

---

src/dashboard-front/src/views/components/plugin-manage/plugin-info.vue

fix: 修复编辑插件时说明消失的问题

---

src/dashboard/apigateway/apigateway/apis/open/stage/serializers.py
src/dashboard/apigateway/apigateway/biz/releaser.py
src/dashboard/apigateway/apigateway/biz/stage.py
src/dashboard/apigateway/apigateway/controller/tasks/release.py
src/dashboard/apigateway/apigateway/core/admin.py
src/dashboard/apigateway/apigateway/core/managers.py
src/dashboard/apigateway/apigateway/core/models.py
src/dashboard/apigateway/apigateway/tests/biz/test_releaser.py
src/dashboard/apigateway/apigateway/tests/biz/test_stage.py
src/dashboard/apigateway/apigateway/tests/controller/tasks/test_release.py

refactor(micro_gateawy_released_history): remove it

---

src/dashboard/apigateway/apigateway/apis/web/plugin/convertor.py
src/dashboard/apigateway/apigateway/apps/plugin/constants.py
src/dashboard/apigateway/apigateway/common/plugin/plugin_checkers.py
src/dashboard/apigateway/apigateway/fixtures/plugins.yaml
src/dashboard/apigateway/apigateway/tests/apis/web/plugin/test_convertor.py
src/dashboard/apigateway/apigateway/tests/common/plugin/test_plugin_checkers.py

feat: fault-injection plugin

---

src/dashboard-front/src/views/apiDocs/components/doc-detail-main-content.vue

fix: 修复文档详情页在1366宽度下样式错误的问题

---

src/dashboard-front/src/components/version-diff/index.vue
src/dashboard-front/src/views/components/plugin-manage/index.vue

fix: 修复在输入法按enter时传入的搜索关键字不正确的问题

---

src/dashboard-front/src/components/resource-detail/index.vue

fix: 修复版本差异对比中新增插件不高亮的问题

---

src/dashboard-front/src/language/lang.ts
src/dashboard-front/src/views/resource/setting/import-doc.vue

feat: 文档zip上传失败提示

---

src/dashboard-front/package.json
src/dashboard-front/src/components/version-diff/index.vue
src/dashboard-front/src/main.ts
src/dashboard-front/src/views/apigwDocs/components/detail.vue
src/dashboard-front/src/views/apigwDocs/components/doc.vue
src/dashboard-front/src/views/basic-info/index.vue
src/dashboard-front/src/views/component-doc/components/detail.vue
src/dashboard-front/src/views/component-doc/components/doc.vue
src/dashboard-front/src/views/component-doc/components/searcher/index.vue
src/dashboard-front/src/views/components-access/manage/components/render-system.vue
src/dashboard-front/src/views/components-access/manage/components/sync-access.vue
src/dashboard-front/src/views/components-access/system/index.vue
src/dashboard-front/src/views/components/resources-doc/index.vue
src/dashboard-front/src/views/home.vue
src/dashboard-front/src/views/operate-data/access-log/detail.vue
src/dashboard-front/src/views/resource/version/components/resourceDetail.vue
src/dashboard-front/src/views/sdk/components/sdk-detail.vue
src/dashboard-front/yarn.lock

refactor(v-html): 过滤v-html内容防范XSS攻击

---

src/dashboard-front/src/components/resource-detail/index.vue
src/dashboard-front/src/components/version-diff/index.vue

feat: 增加版本对比中的新增/删除插件的背景色

---

src/dashboard-front/src/views/online-debug/components/edit-table.vue

fix：在线调试取消校验

---

src/dashboard-front/src/views/resource/setting/import-doc.vue

fix: 修复资源文档上传失败的问题

---

src/dashboard-front/package.json
src/dashboard-front/yarn.lock

deps(bkui-vue): 更新bkui以修复xss漏洞

---

src/dashboard/apigateway/apigateway/apis/web/metrics/serializers.py
src/dashboard/apigateway/apigateway/apis/web/metrics/urls.py
src/dashboard/apigateway/apigateway/apis/web/metrics/views.py
src/dashboard/apigateway/apigateway/apps/metrics/constants.py
src/dashboard/apigateway/apigateway/apps/metrics/prometheus/dimension.py
src/dashboard/apigateway/apigateway/tests/apis/web/metrics/test_serializers.py
src/dashboard/apigateway/apigateway/tests/apis/web/metrics/test_views.py
src/dashboard/apigateway/apigateway/tests/apps/metrics/prometheus/test_dimension.py

feat:query_instant

---

src/dashboard-front/src/hooks/use-query-list.ts
src/dashboard-front/src/views/apiDocs/index.vue
src/dashboard-front/src/views/resource/setting/index.vue

fix: 修复资源配置页搜索后页码错误的问题

---

src/dashboard-front/src/views/apiDocs/index.vue
src/dashboard-front/yarn.lock

fix: 修复文档页导航collapse不自动展开的问题

---

src/dashboard-front/src/components/log-details/index.vue
src/dashboard-front/src/http/logs.ts

feat: 优化发布时的时间展示

---

src/dashboard-front/src/views/online-debug/components/response-content.vue

fix: 在线调试响应状态码颜色细分

---

src/dashboard-front/src/http/report.ts
src/dashboard-front/src/language/lang.ts
src/dashboard-front/src/views/operate-data/statistics-report/components/line-chart.vue
src/dashboard-front/src/views/operate-data/statistics-report/components/top.vue
src/dashboard-front/src/views/operate-data/statistics-report/index.vue
src/dashboard-front/src/views/operate-data/statistics-report/type.ts

feat: 统计报表剩余功能开发

---

src/dashboard-front/src/hooks/use-query-list.ts
src/dashboard-front/src/types/common.ts
src/dashboard-front/src/views/resource/setting/index.vue

fix: 修复改变每页条数时请求的数据不正确的问题

---

src/dashboard-front/src/components/log-details/index.vue

fix: 修复资源发布时icon显示不正确的问题

---

src/dashboard-front/src/http/permission.ts
src/dashboard-front/src/views/permission/app/index.vue

refactor(frontend): 主动授权的默认有效时间改为永久

---

src/dashboard-front/src/language/lang.ts
src/dashboard-front/src/views/basic-info/common/type.ts
src/dashboard-front/src/views/basic-info/index.vue

feat(frontend): 网关编辑新增管理网关的应用列表项

---

src/dashboard-front/src/views/components/plugin-manage/plugin-info.vue

refactor: 插件简介图标改用svg引入

---

src/dashboard-front/src/views/resource/version/edition/index.vue

refactor(resource/version): 优化资源版本对比展示

---

src/dashboard-front/src/components/gateways-edit/member-selector.vue

feat(member-selector): 维护人员文本的tooltips

---

src/dashboard-front/.commitlintrc.js
src/dashboard-front/package.json
src/dashboard-front/src/views/online-debug/components/edit-table.vue

feat: 在线调试表格选择功能

---

src/dashboard-front/src/views/resource/setting/index.vue

fix(resource/setting): 修复资源配置表格高度问题

---

src/dashboard-front/src/views/online-debug/components/response-content.vue

fix(online)：修复在线调试headers切换重置问题

---

src/dashboard/apigateway/apigateway/apis/web/stage/serializers.py
src/dashboard/apigateway/apigateway/biz/release.py
src/dashboard/apigateway/apigateway/biz/resource_version.py
src/dashboard/apigateway/apigateway/biz/validators.py

fix(api/web): fix stage list api

---

src/dashboard/apigateway/apigateway/apis/web/stage/serializers.py
src/dashboard/apigateway/apigateway/biz/release.py
src/dashboard/apigateway/apigateway/biz/resource_version.py
src/dashboard/apigateway/apigateway/biz/validators.py

feat(api/web): fix get stage list

feat(api/web): fix get stage list

---

src/dashboard/apigateway/apigateway/fixtures/plugins.yaml

fix(fixtures/plugins.yaml): update desc

---

src/dashboard-front/src/views/operate-data/access-log/components/search-input.vue
src/dashboard-front/src/views/operate-data/access-log/index.vue

feat(access-log): 新增日志查询的搜索历史

---

src/dashboard/apigateway/apigateway/conf/default.py

fix(sdk): fix maven config

---

src/dashboard/apigateway/apigateway/biz/resource/importer/openapi.py
src/dashboard/apigateway/apigateway/biz/resource/importer/parser.py
src/dashboard/apigateway/apigateway/tests/apis/web/resource/test_views.py

fix(web/api): fix openapi import

---

src/dashboard/apigateway/apigateway/apps/support/managers.py
src/dashboard/apigateway/apigateway/core/managers.py

fix(publish): fix concurrent publish update release resources

fix(publish): fix concurrent publish update release resources

---

src/dashboard/apigateway/apigateway/biz/access_log/log_search.py

fix(biz/access_log/log_search)：修复esc查询语法报错问题

fix(biz/access_log/log_search)：修复日志查询语法报错问题

---

src/dashboard/apigateway/apigateway/apis/web/access_log/views.py
src/dashboard/apigateway/apigateway/biz/access_log/log_search.py

fix(biz/access_log/log_search)：修复导出数据为空问题

fix(biz/access_log/log_search)：修复导出数据为空问题

---

src/dashboard/apigateway/apigateway/apis/web/access_log/views.py

fix(biz/access_log/log_search)：修复导出数据为空问题

fix(biz/access_log/log_search)：修复流水日志导出数据为空问题

---

src/dashboard-front/src/views/apiDocs/doc-detail.vue

feat(doc-detail.vue): ESB详情页的快捷跳转会显示系统名和系统ID

---

src/dashboard-front/src/views/operate-data/statistics-report/components/top.vue

fix(statistics-report): 修复统计报表页1366宽度下出现横向滚动条的问题

---

src/dashboard/apigateway/apigateway/apis/web/metrics/views.py
src/dashboard/apigateway/apigateway/apps/metrics/prometheus/dimension.py
src/dashboard/apigateway/apigateway/tests/apps/metrics/prometheus/test_dimension.py

fix(web/api): fix metrics

---

src/dashboard/apigateway/apigateway/apis/web/resource_version/views.py
src/dashboard/apigateway/apigateway/tests/apis/web/resource_version/test_views.py

feat(apis/web/resource_version/views)：资源版本号添加初始值

feat(apis/web/resource_version/views)：资源版本号添加初始值

---

src/dashboard-front/src/views/apiDocs/components/doc-detail-main-content.vue
src/dashboard-front/src/views/apiDocs/components/doc-detail-side-nav.vue
src/dashboard-front/src/views/apiDocs/doc-detail.vue
src/dashboard-front/src/views/apiDocs/types.d.ts
src/dashboard-front/yarn.lock

feat(apiDocs/doc-detail.vue): api 文档滚动时自动高亮对应目录项

---

src/dashboard-front/src/views/permission/app/index.vue

fix(permission/app): 取消续期后重置授权期限选择器

---

src/dashboard-front/src/views/permission/app/index.vue

fix(permission/app): 修改应用授权表格列名

---

src/dashboard-front/src/views/operate-data/access-log/components/search-input.vue
src/dashboard-front/src/views/operate-data/access-log/index.vue
src/dashboard-front/yarn.lock

fix(access-log): 查询语句输入空字符串后不写入搜索历史

---

src/dashboard-front/src/main.ts
src/dashboard-front/src/views/apiDocs/components/sdk-instruction-content.vue
src/dashboard-front/src/views/apiDocs/doc-detail.vue

fix(doc-detail): 修复API文档代码块没有高亮的问题

---

src/dashboard-front/src/language/lang.ts
src/dashboard-front/src/views/permission/app/index.vue

feat(permission/app): 权限导出默认导出全部记录

---

src/dashboard-front/src/views/permission/app/index.vue

fix(permission/app): 修复期限为永久的授权记录的显示文本

---

src/dashboard/apigateway/apigateway/apis/web/release/serializers.py
src/dashboard/apigateway/apigateway/tests/apis/web/release/test_views.py

fix(apis/web/release/serializers): 修复接口未返回is_public字段问题

fix(apis/web/release/serializers): 修复接口未返回is_public字段问题

---

src/dashboard-front/src/views/permission/app/index.vue

fix(permission/app): 修复搜索栏显示文本

---

src/dashboard/apigateway/apigateway/editions/ee/legacy_esb/management/commands/export_buffet_to_resources.py
src/dashboard/apigateway/apigateway/editions/ee/legacy_esb/models.py

fix(legacy_esb/sync): fix bk-esb-buffet sync

---

src/dashboard-front/src/components/version-diff/index.vue
src/dashboard-front/src/views/resource/setting/index.vue
src/dashboard-front/src/views/stage/overview/comps/release-sideslider.vue

fix(version-diff): 修复版本对比不能正确显示新网关第一个版本的资源差异的问题

---

src/dashboard-front/src/components/ag-editor.vue
src/dashboard-front/src/language/lang.ts
src/dashboard-front/src/views/online-debug/components/edit-table.vue
src/dashboard-front/src/views/online-debug/components/request-record.vue
src/dashboard-front/src/views/online-debug/index.vue

fix(online-debug): 在线调试体验问题修复

---

src/dashboard/apigateway/apigateway/apis/web/resource_version/views.py

fix(1.14/api/web): fix resource diff

fix(1.14/api/web): fix resource diff

---

src/dashboard-front/src/language/lang.ts
src/dashboard-front/src/views/permission/app/index.vue
src/dashboard-front/src/views/resource/setting/detail.vue
src/dashboard-front/src/views/resource/setting/index.vue

feat(permission/app): 应用权限页的表头过滤

---

src/dashboard-front/src/views/apiDocs/components/doc-detail-main-content.vue
src/dashboard-front/src/views/apiDocs/doc-detail.vue

fix(doc-detail): 修复文档详情页折叠右区时的样式问题

---

src/dashboard-front/src/views/stage/overview/comps/release-sideslider.vue

fix(release-sideslider): 修复发布版本时被禁用的option仍可被选中的问题

---

src/dashboard/apigateway/apigateway/biz/validators.py
src/dashboard/apigateway/apigateway/tests/biz/test_validators.py

fix(biz/validators): 修复发布环境校验的后端配置问题

fix(biz/validators): 修复发布环境校验的后端配置问题

---

src/dashboard/apigateway/apigateway/apis/web/docs/gateway/gateway/serializers.py
src/dashboard/apigateway/apigateway/apis/web/docs/gateway/gateway/views.py
src/dashboard/apigateway/apigateway/biz/validators.py
src/dashboard/apigateway/apigateway/tests/apis/web/docs/gateway/gateway/test_views.py
src/dashboard/apigateway/apigateway/tests/biz/test_backend.py
src/dashboard/apigateway/apigateway/tests/biz/test_validators.py

feat(api/web): gateway doc api add sdk

feat(api/web): gateway doc api add sdk

---

src/dashboard-front/src/language/lang.ts
src/dashboard-front/src/views/apiDocs/components/doc-detail-side-content.vue
src/dashboard-front/src/views/apiDocs/components/sdk-detail-dialog.vue
src/dashboard-front/src/views/apiDocs/doc-detail.vue

feat(doc-detail): 新增文档详情页网关SDK展示

---

src/dashboard/apigateway/apigateway/apis/web/metrics/views.py
src/dashboard/apigateway/apigateway/tests/apis/web/metrics/test_views.py

fix(apis/web/metrics): 修复网关资源宽带占用标签显示问题

fix(apis/web/metrics): 修复网关资源宽带占用标签显示问题

---

src/dashboard-front/src/views/operate-data/access-log/index.vue

fix(access-log):修复流水日志图表缩放问题

---

src/dashboard/apigateway/apigateway/biz/access_log/constants.py

fix(biz/access_log): 修复流水日志接口未返回response_size问题

fix(biz/access_log): 修复流水日志接口未返回response_size问题

---

src/dashboard-front/src/language/lang.ts
src/dashboard-front/src/views/stage/published/index.vue

feat(stage/published): 修改版本发布文本

---

src/dashboard/apigateway/apigateway/biz/validators.py
src/dashboard/apigateway/apigateway/tests/biz/test_validators.py

BackendConfig 缺少 stage 查询条件，导致将其他 stage 下的 backend 也查询出来校验

fix(biz/validators): 修复缺少stage查询条件问题

---

src/dashboard/apigateway/apigateway/apis/web/resource/views.py
src/dashboard/apigateway/apigateway/biz/resource/savers.py
src/dashboard/apigateway/apigateway/tests/apis/web/resource/test_views.py

fix(apis/web/resource/view): 修复资源未修改但触发更新问题

fix(apis/web/resource/view): 修复资源未修改但触发更新问题

---

src/dashboard/apigateway/apigateway/apis/web/metrics/views.py
src/dashboard/apigateway/apigateway/apis/web/resource/views.py
src/dashboard/apigateway/apigateway/biz/resource_version_diff.py
src/dashboard/apigateway/apigateway/tests/apis/web/metrics/test_views.py
src/dashboard/apigateway/apigateway/tests/apis/web/resource/test_views.py

fix(biz/resource_version): fix labels diff

fix(biz/resource_version): fix labels diff

---

src/dashboard-front/src/views/operate-data/statistics-report/components/line-chart.vue
src/dashboard-front/src/views/operate-data/statistics-report/components/top.vue

fix(statistics-report): 运营图表优化

---

src/dashboard/apigateway/apigateway/apis/web/permission/serializers.py

fix(apis/web/permission): 修复应用权限导出的授权类型显示问题

---

src/dashboard-front/src/views/resource/setting/import-doc.vue

fix(import-doc): 修复资源 Yaml 文档匹配逻辑错误问题

---

src/dashboard-front/src/language/lang.ts
src/dashboard-front/src/views/components/plugin-manage/index.vue
src/dashboard-front/src/views/permission/app/index.vue

fix(permission/app): 修复授权记录搜索过滤问题&修复插件配置按钮难点击的问题

---

src/dashboard/apigateway/apigateway/apis/web/permission/views.py
src/dashboard/apigateway/apigateway/biz/resource/importer/parser.py
src/dashboard/apigateway/apigateway/tests/apis/web/permission/test_views.py

fix(resource): 修复导出json 中文编码问题

fix(resource): fix export json

---

src/dashboard-front/src/language/lang.ts
src/dashboard-front/src/views/components/plugin-manage/plugin-info.vue

fix(plugin-info.vue): 修复故障注入插件提交失败问题

---

src/dashboard/apigateway/apigateway/common/plugin/checker.py

fix(fault-injection): validate error if vars empty

---

src/dashboard-front/src/views/resource/setting/index.vue

fix(resource): 资源配置数据导出限制

---

src/dashboard/apigateway/apigateway/apis/web/resource_version/views.py

fix(resource_version): fix resource_version diff when first publish

fix(resource_version): fix resource_version diff when first publish

---

src/dashboard/apigateway/apigateway/conf/default.py
src/dashboard/apigateway/apigateway/conf/utils.py

fix(default.py): patch django 4.2 to support mysql 5.7

---

src/dashboard/apigateway/apigateway/apis/open/resource/serializers.py
src/dashboard/apigateway/apigateway/tests/apis/open/resource/test_views.py

fix(openapi/1.15): fix resource sync validate

---

src/dashboard/apigateway/apigateway/apis/web/resource_version/views.py
src/dashboard/apigateway/apigateway/tests/apis/web/resource_version/test_views.py

fix(resource_version): fix diff

fix(resource_version): fix diff

---

src/dashboard/apigateway/apigateway/apis/web/resource_version/views.py
src/dashboard/apigateway/apigateway/tests/apis/web/resource_version/test_views.py

fix(resource_version): fix diff

 fix(resource_version): fix diff

---

src/dashboard-front/.bk.development.env
src/dashboard-front/.gitignore
src/dashboard-front/bk.config.js
src/dashboard-front/src/app.vue
src/dashboard-front/src/components/user-info.vue
src/dashboard-front/src/css/common.css
src/dashboard-front/src/language/lang.ts
src/dashboard-front/src/store/user.ts
src/dashboard-front/src/types/store.ts
src/dashboard-front/src/views/apiDocs/components/doc-detail-side-content.vue
src/dashboard-front/src/views/apiDocs/index.vue
src/dashboard-front/src/views/apiDocs/types.d.ts
src/dashboard-front/src/views/basic-info/common/type.ts
src/dashboard-front/src/views/basic-info/index.vue
src/dashboard-front/src/views/home.vue

feat: 多租户前端逻辑

---

src/dashboard-front/.bk.development.env
src/dashboard-front/.gitignore
src/dashboard-front/bk.config.js
src/dashboard-front/src/app.vue
src/dashboard-front/src/components/user-info.vue
src/dashboard-front/src/css/common.css
src/dashboard-front/src/language/lang.ts
src/dashboard-front/src/store/user.ts
src/dashboard-front/src/types/store.ts
src/dashboard-front/src/views/apiDocs/components/doc-detail-side-content.vue
src/dashboard-front/src/views/apiDocs/index.vue
src/dashboard-front/src/views/apiDocs/types.d.ts
src/dashboard-front/src/views/basic-info/common/type.ts
src/dashboard-front/src/views/basic-info/index.vue
src/dashboard-front/src/views/home.vue

feat: 多租户前端逻辑 (#1145)

---

src/dashboard-front/.bk.development.env
src/dashboard-front/.gitignore
src/dashboard-front/bk.config.js
src/dashboard-front/src/enums/index.ts
src/dashboard-front/src/views/apiDocs/components/doc-detail-side-content.vue
src/dashboard-front/src/views/apiDocs/index.vue
src/dashboard-front/src/views/basic-info/index.vue
src/dashboard-front/src/views/home.vue

fix: 修复多租户相关文本展示

---

src/dashboard/apigateway/apigateway/apis/web/gateway/views.py
src/dashboard/apigateway/apigateway/components/bkuser.py
src/dashboard/apigateway/apigateway/conf/default.py
src/dashboard/apigateway/apigateway/core/admin.py
src/dashboard/apigateway/apigateway/core/management/commands/sync_gateway.py

fix(tenant): fix ft_tenant

---

src/dashboard-front/src/views/components/plugin-manage/index.vue

fix: 修复插件配置的回显错误问题

---

src/dashboard-front/src/views/main.vue
src/dashboard-front/src/views/resource/setting/index.vue

fix: 修复发布通知出现时页面高度错误的问题

---

src/dashboard-front/src/views/apiDocs/components/lang-selector.vue
src/dashboard-front/src/views/apiDocs/index.vue

fix: 补充查看 sdk 时的 Golang 选项

---

src/dashboard-front/src/router/index.ts
src/dashboard-front/src/views/apiDocs/components/component-searcher.vue
src/dashboard-front/src/views/apiDocs/doc-detail.vue
src/dashboard-front/src/views/apiDocs/index.vue

fix: 修复多系统组件api文档搜索框样式和文档详情数据错误问题

---

src/dashboard-front/src/views/apiDocs/components/component-searcher.vue

fix: 修复组件api文档搜索框样式和参数传递问题

---

src/dashboard-front/src/views/apiDocs/doc-detail.vue

feat: API文档详情支持从URL查询参数展示指定API文档

---

src/dashboard-front/src/components/log-details/index.vue

fix: 修复版本发布的图标和时间展示错误问题

---

src/dashboard-front/src/language/lang.ts
src/dashboard-front/src/views/stage/overview/comps/release-sideslider.vue

fix: 修复资源版本过旧时仍可被发布的问题

---

src/dashboard-front/src/views/components/resources-doc/index.vue
src/dashboard-front/src/views/resource/setting/detail.vue

fix: 修复资源配置抽屉高度

---

src/dashboard/apigateway/apigateway/apis/web/resource/serializers.py
src/dashboard/apigateway/apigateway/apis/web/resource/validators.py
src/dashboard/apigateway/apigateway/biz/resource/importer/validate.py
src/dashboard/apigateway/apigateway/tests/apis/web/resource/test_validators.py
src/dashboard/apigateway/apigateway/tests/biz/resource/importer/test_validate.py

fix(apis/web/resource): 修复网关资源名称重复校验问题

fix(apis/web/resource): 修复网关资源名称重复校验问题

---

src/dashboard-front/src/language/lang.ts

feat: 补充 i18n 条目

---

src/dashboard-front/src/router/index.ts
src/dashboard-front/src/views/apiDocs/components/doc-detail-main-content.vue
src/dashboard-front/src/views/apiDocs/components/doc-detail-side-content.vue
src/dashboard-front/src/views/apiDocs/components/sdk-instruction-content.vue
src/dashboard-front/src/views/apiDocs/doc-detail.vue
src/dashboard-front/src/views/apiDocs/index.vue
src/dashboard-front/src/views/apiDocs/types.d.ts
src/dashboard-front/src/views/online-debug/index.vue

feat: api文档url可查询环境

---

src/dashboard/apigateway/apigateway/biz/resource/importer/validate.py
src/dashboard/apigateway/apigateway/tests/biz/resource/importer/test_validate.py

fix: 修复导入同名资源的lower_name校验问题

---

src/dashboard-front/src/router/index.ts
src/dashboard-front/src/views/apiDocs/components/doc-detail-main-content.vue
src/dashboard-front/src/views/apiDocs/components/doc-detail-side-content.vue
src/dashboard-front/src/views/apiDocs/components/sdk-instruction-content.vue
src/dashboard-front/src/views/apiDocs/doc-detail.vue
src/dashboard-front/src/views/apiDocs/index.vue
src/dashboard-front/src/views/apiDocs/types.d.ts
src/dashboard-front/src/views/components/plugin-manage/index.vue
src/dashboard-front/src/views/online-debug/index.vue
src/dashboard-front/src/views/resource/setting/index.vue
src/dashboard/apigateway/apigateway/biz/resource/importer/validate.py
src/dashboard/apigateway/apigateway/common/renderers.py
src/dashboard/apigateway/apigateway/tests/biz/resource/importer/test_validate.py

fix 1.15.2-alpha.1 bugs

---

src/dashboard-front/src/app.vue

performance: 减少多余的 userInfo & featureFlags 请求

---

src/dashboard-front/src/views/resource/setting/index.vue

fix: 修复编辑资源插件时展示的插件配置错误的问题

---

src/dashboard-front/src/app.vue
src/dashboard-front/src/views/resource/setting/index.vue

1.15.2 bugfix

---

src/dashboard-front/src/views/resource/setting/index.vue

fix: 修复后端服务关联资源查询错误

---

src/dashboard-front/src/views/apiDocs/index.vue

fix: 修复多租户环境下API文档页展示异常的问题

---

src/dashboard-front/src/components/chat/index.vue

fix: 修复一键拉群的人员 tooltips 内容错误

---

src/dashboard-front/src/views/resource/setting/comps/version-sideslider.vue

fix: 修复生成版本时资源变化数量展示错误

---

src/dashboard-front/src/app.vue
src/dashboard-front/src/views/resource/setting/index.vue

backport: 修复 1.15 上线后用户反馈问题

---

src/dashboard-front/src/app.vue
src/dashboard-front/src/views/resource/setting/index.vue

backport: ft_tenant sync with master, fix bugs

---

src/dashboard-front/src/app.vue
src/dashboard-front/src/common/menu.ts
src/dashboard-front/src/router/index.ts
src/dashboard-front/src/views/platform-tools/automatedGateway/index.vue
src/dashboard-front/src/views/platform-tools/index.vue
src/dashboard-front/src/views/platform-tools/toolbox/index.vue

feat: 平台工具路由和基础页面

---

src/dashboard/apigateway/apigateway/apps/metrics/constants.py
src/dashboard/apigateway/apigateway/apps/metrics/prometheus/dimension.py
src/dashboard/apigateway/apigateway/tests/apps/metrics/prometheus/test_dimension.py

fix(apps/metrics/prometheus): 修复统计报表过滤非 20x 请求问题

fix(apps/metrics/prometheus): 修复统计报表过滤非 20x 请求问题

---

src/dashboard/apigateway/apigateway/conf/celery_conf.py
src/dashboard/apigateway/apigateway/controller/tasks/__init__.py
src/dashboard/apigateway/apigateway/controller/tasks/clean_task.py
src/dashboard/apigateway/apigateway/tests/conftest.py
src/dashboard/apigateway/apigateway/tests/controller/tasks/test_clean_task.py

feat(apigateway/controller/tasks): add delete debug history task

feat(apigateway/controller/tasks): add delete debug history task

---

src/dashboard-front/src/views/operate-data/access-log/index.vue

feat: 日志详情表头可配置

---

src/dashboard-front/src/language/lang.ts
src/dashboard-front/src/views/platform-tools/automatedGateway/index.vue

feat: 自动化网关介绍页

---

src/dashboard-front/src/language/lang.ts
src/dashboard-front/src/views/resource/version/components/createSdk.vue

fix: 修复生成SDK时说明不正确的问题

---

src/dashboard-front/src/views/resource/setting/comps/back-config.vue

fix: 修复资源的后端配置在恢复初始值时赋值错误的问题

---

src/dashboard/apigateway/apigateway/apis/open/esb/permission/serializers.py
src/dashboard/apigateway/apigateway/tests/apis/open/esb/permission/test_serializers.py

fix(api/open): fix esb permission renew

fix(api/open): fix esb permission renew

---

src/dashboard/apigateway/apigateway/apis/web/access_log/urls.py
src/dashboard/apigateway/apigateway/apis/web/access_log/views.py
src/dashboard/apigateway/apigateway/urls.py

fix(api/web): fix access log query

fix(api/web): fix access log query

---

src/dashboard-front/src/css/app-doc.css
src/dashboard-front/src/main.ts
src/dashboard-front/src/views/apiDocs/components/doc-detail-main-content.vue
src/dashboard-front/src/views/apiDocs/components/sdk-instruction-content.vue
src/dashboard-front/src/views/apigwDocs/components/doc.vue
src/dashboard-front/src/views/component-doc/components/doc.vue
src/dashboard-front/src/views/components/resource-doc-slider/index.vue
src/dashboard-front/src/views/components/resources-doc/index.vue
src/dashboard-front/src/views/online-debug/components/doc.vue
src/dashboard-front/src/views/sdk/components/sdk-detail.vue

style: 统一代码块风格为 vs2015

---

src/dashboard-front/src/views/platform-tools/toolbox/components/json-format.vue

fix: json 格式化 API 接口回退

---

src/dashboard-front/src/css/app-doc.css
src/dashboard-front/src/views/apiDocs/components/doc-detail-main-content.vue
src/dashboard-front/src/views/apiDocs/components/sdk-instruction-content.vue
src/dashboard-front/src/views/components/resource-doc-slider/index.vue
src/dashboard-front/src/views/resource/setting/index.vue

feat: 资源文档代码块复制功能 & 代码块样式、换行修复

---

src/dashboard-front/src/language/lang.ts
src/dashboard-front/src/views/apiDocs/components/lang-selector.vue
src/dashboard-front/src/views/apiDocs/components/sdk-detail-dialog.vue
src/dashboard-front/src/views/apiDocs/index.vue

feat: sdk 详情弹窗 tooltips 展示网关负责人

---

src/dashboard-front/.bk.production.env
src/dashboard-front/.eslintignore
src/dashboard-front/.eslintrc.js
src/dashboard-front/bk.config.js
src/dashboard-front/index.html
src/dashboard-front/package.json
src/dashboard-front/src/app.vue
src/dashboard-front/src/components/gateways-edit/tenant-user-selector.vue
src/dashboard-front/src/main.ts
src/dashboard-front/src/store/user.ts
src/dashboard-front/src/views/apiDocs/components/doc-detail-side-content.vue
src/dashboard-front/src/views/apiDocs/index.vue
src/dashboard-front/src/views/basic-info/common/type.ts
src/dashboard-front/src/views/basic-info/index.vue
src/dashboard-front/src/views/home.vue
src/dashboard-front/src/views/operate-records/index.vue
src/dashboard-front/src/views/permission/apply/index.vue
src/dashboard-front/src/views/permission/record/index.vue
src/dashboard-front/src/views/resource/version/edition/index.vue
src/dashboard-front/src/views/resource/version/sdk/index.vue
src/dashboard-front/src/views/stage/overview/comps/stage-card-list.vue
src/dashboard-front/src/views/stage/overview/detail-mode/index.vue
src/dashboard-front/types/global.d.ts
src/dashboard-front/yarn.lock

feat: 多租户人员选择器 & 多租户人名展示适配

---

src/dashboard-front/.bk.production.env
src/dashboard-front/bk.config.js

chore: 去掉多余配置

---

src/dashboard-front/src/views/platform-tools/toolbox/components/json-format.vue

fix: json 文本超长问题修复

---

src/dashboard-front/src/app.vue

fix: 修复css引起的构建错误

---

src/dashboard-front/package.json
src/dashboard-front/src/app.vue
src/dashboard-front/yarn.lock

deps: 更新人员选择器 & 修复focus边框样式

---

src/dashboard-front/src/views/operate-data/access-log/index.vue

feat: 日志详情表头设置

---

src/dashboard/apigateway/apigateway/biz/resource/importer/validate.py
src/dashboard/apigateway/apigateway/tests/biz/resource/importer/test_validate.py

fix(biz/resource/importer): fix label name case check

fix(biz/resource/importer): fix label name case check

---

src/dashboard/apigateway/apigateway/core/admin.py

fix(core/admin.py): fix django admin search of Context model

fix(core/admin.py): fix django admin search of Context model

---

src/dashboard-front/src/components/resource-detail/index.vue

fix: 资源差异展示“匹配所有子路径”变化

---

src/dashboard-front/src/views/operate-data/access-log/index.vue

fix：日志详情表头列

---

src/dashboard-front/src/store/index.ts
src/dashboard-front/src/store/resourceSetting.ts
src/dashboard-front/src/views/resource/setting/edit.vue
src/dashboard-front/src/views/resource/setting/index.vue

feat: 从资源编辑页返回资源配置页时会自动翻到离开前的页码

---

src/dashboard/apigateway/apigateway/controller/crds/v1beta1/convertors/service.py

fix(publish/service): fix publish service default backend host empty

fix(publish/service): fix publish service default backend host empty

---

src/dashboard/apigateway/apigateway/biz/validators.py
src/dashboard/apigateway/apigateway/tests/biz/test_validators.py
src/dashboard/apigateway/apigateway/tests/conftest.py

fix(publish): fix default backend config validate

fix(publish): fix default backend config validate

---

src/dashboard/apigateway/apigateway/biz/resource/resource.py
src/dashboard/apigateway/apigateway/biz/resource_version.py

fix(resource): fix resource stage vars get

fix(resource): fix resource stage vars get

---

src/dashboard/apigateway/apigateway/apps/feature/admin.py
src/dashboard/apigateway/apigateway/apps/gateway/admin.py
src/dashboard/apigateway/apigateway/apps/monitor/admin.py
src/dashboard/apigateway/apigateway/apps/support/admin.py
src/dashboard/apigateway/apigateway/core/admin.py
src/dashboard/apigateway/apigateway/editions/ee/apps/esb/bkcore/admin.py
src/dashboard/apigateway/apigateway/schema/admin.py

fix(admin.py): 补充其他 admin 的 djangoql 配置

fix(admin.py): 补充其他 admin 的 djangoql 配置

---

src/dashboard-front/src/views/online-debug/components/request-record.vue

feat: 调用历史详情开发

---

src/dashboard-front/src/language/lang.ts
src/dashboard-front/src/views/backend-service/index.vue
src/dashboard-front/src/views/components/plugin-manage/index.vue
src/dashboard-front/src/views/stage/overview/comps/stage-card-list.vue
src/dashboard-front/src/views/stage/overview/detail-mode/index.vue
src/dashboard-front/src/views/stage/overview/detail-mode/variable-manage.vue

fix: 修复有版本正在发布时允许修改相关联配置的问题

---

src/dashboard-front/src/views/permission/record/index.vue
src/dashboard-front/src/views/stage/published/index.vue

fix: 修复租户 display name 展示

---

src/dashboard-front/src/views/online-debug/components/edit-table.vue

feat: 在线调试 headers select 支持输入

---

src/dashboard-front/src/app.vue
src/dashboard-front/src/common/menu.ts
src/dashboard-front/src/components/stage-top-bar.vue
src/dashboard-front/src/language/lang.ts
src/dashboard-front/src/router/index.ts
src/dashboard-front/src/store/common.ts
src/dashboard-front/src/types/common.ts
src/dashboard-front/src/types/gateway.ts
src/dashboard-front/src/views/404.vue
src/dashboard-front/src/views/backend-service/add.vue
src/dashboard-front/src/views/backend-service/index.vue
src/dashboard-front/src/views/components/plugin-manage/index.vue
src/dashboard-front/src/views/home.vue
src/dashboard-front/src/views/main.vue
src/dashboard-front/src/views/resource/setting/index.vue
src/dashboard-front/src/views/resource/version/edition/index.vue
src/dashboard-front/src/views/stage/overview/comps/stage-card-list.vue
src/dashboard-front/src/views/stage/overview/detail-mode/index.vue
src/dashboard-front/src/views/stage/overview/detail-mode/variable-manage.vue
src/dashboard-front/src/views/stage/overview/index.vue

feat: 可编程网关视图适配 & 404页

---

src/dashboard/apigateway/apigateway/apis/web/docs/gateway/gateway/serializers.py
src/dashboard/apigateway/apigateway/tests/apis/web/docs/gateway/gateway/test_serializers.py

fix(apis/web/docs): 修复网关文档接口缺少 doc_maintainers 字段

fix(apis/web/docs): 修复网关文档接口缺少 doc_maintainers 字段

---

src/dashboard-front/src/views/backend-service/index.vue

fix: 可编程网关后端列表

---

src/dashboard-front/src/views/online-debug/components/payload-headers.vue

fix: 在线调试预设重复数据处理

---

src/dashboard/apigateway/apigateway/apis/web/metrics/serializers.py
src/dashboard/apigateway/apigateway/apis/web/metrics/urls.py
src/dashboard/apigateway/apigateway/apis/web/metrics/views.py
src/dashboard/apigateway/apigateway/apps/metrics/constants.py
src/dashboard/apigateway/apigateway/apps/metrics/prometheus/dimension.py
src/dashboard/apigateway/apigateway/tests/apis/web/metrics/test_serializers.py
src/dashboard/apigateway/apigateway/tests/apis/web/metrics/test_views.py

feat(apis/web/metrics): 新增历史请求统计接口

feat(apis/web/metrics): 新增历史请求统计接口

---

src/dashboard/apigateway/apigateway/apis/open/resource_version/views.py

fix(apis/open/resource_version): remove dropped fields from api response

---

src/dashboard/apigateway/apigateway/apis/web/resource_version/serializers.py
src/dashboard/apigateway/apigateway/apis/web/stage/serializers.py

fix(api/web): fix stage get

---

src/dashboard/apigateway/apigateway/apis/web/release/serializers.py
src/dashboard/apigateway/apigateway/apis/web/release/views.py
src/dashboard/apigateway/apigateway/apis/web/stage/serializers.py
src/dashboard/apigateway/apigateway/apis/web/stage/views.py
src/dashboard/apigateway/apigateway/components/paas.py

fix(api/web): fix deploy events get

---

src/dashboard-front/src/language/lang.ts
src/dashboard-front/src/views/basic-info/index.vue

fix: 开发指引 eslint 修复

---

src/dashboard/apigateway/apigateway/apis/web/stage/serializers.py
src/dashboard/apigateway/apigateway/apis/web/stage/views.py
src/dashboard/apigateway/apigateway/biz/releaser.py
src/dashboard/apigateway/apigateway/components/paas.py

fix(api/web): fix deploy

---

src/dashboard/apigateway/apigateway/apis/web/gateway/views.py

fix(apis/web/gateways): fix kind filter not ok

---

src/dashboard-front/src/css/common.css
src/dashboard-front/src/http/programmable.ts
src/dashboard-front/src/views/stage/overview/comps/release-programmable-slider.vue

feat: 可编程网关资源部署提交人&提交时间

---

src/dashboard-front/src/views/basic-info/common/type.ts
src/dashboard-front/src/views/basic-info/index.vue

feat: 操作指引链接

---

src/dashboard-front/src/components/programmable-deploy-events-slider/index.vue
src/dashboard-front/src/views/stage/overview/comps/release-programmable-slider.vue
src/dashboard-front/src/views/stage/published/index.vue

fix: 修复可编程网关部署日志

---

src/dashboard-front/src/components/language-toggle.vue
src/dashboard-front/src/http/user.ts
src/dashboard-front/src/store/user.ts

feat: 多租户语言切换

---

src/dashboard-front/src/views/operate-data/access-log/index.vue
src/dashboard-front/src/views/operate-data/statistics-report/components/resource-searcher.vue
src/dashboard-front/src/views/operate-data/statistics-report/components/top.vue

feat: 流水日志 & 统计报表资源选择器

---

src/dashboard/apigateway/apigateway/apis/web/api_test/views.py

fix(apps/api_debug): 修复在线调试发起 post 请求时 body 解析问题

fix(apps/api_debug): 修复在线调试发起 post 请求时 body 解析问题

---

src/dashboard/apigateway/apigateway/apis/v2/inner/urls.py
src/dashboard/apigateway/apigateway/data/apidocs/zh/v2_inner_renew_resource_permission.md
src/dashboard/apigateway/apigateway/data/apigw-definitions/bk-apigateway-resources.yaml

fix(data/apigw-definitions): fix bk-apigateway-resources.yaml

fix(data/apigw-definitions): fix bk-apigateway-resources.yaml

---

src/dashboard-front/src/components/create-gateway.vue
src/dashboard-front/src/language/lang.ts
src/dashboard-front/src/views/basic-info/index.vue
src/dashboard-front/src/views/home.vue

feat: 创建网关指引

---

src/dashboard-front/src/components/create-gateway.vue

fix: 创建编程网关提示

---

src/dashboard/apigateway/apigateway/apis/web/release/urls.py
src/dashboard/apigateway/apigateway/apis/web/release/views.py

fix(api/web): fix programable gateway history

fix(api/web): fix programable gateway history

---

src/dashboard-front/src/components/gateways-edit/member-selector.vue
src/dashboard-front/src/components/gateways-edit/tenant-user-selector.vue
src/dashboard-front/src/views/apiDocs/components/doc-detail-side-content.vue
src/dashboard-front/src/views/apiDocs/index.vue
src/dashboard-front/src/views/basic-info/index.vue
src/dashboard-front/src/views/home.vue
src/dashboard-front/src/views/operate-records/index.vue
src/dashboard-front/src/views/permission/apply/index.vue
src/dashboard-front/src/views/permission/record/index.vue
src/dashboard-front/src/views/resource/version/edition/index.vue
src/dashboard-front/src/views/resource/version/sdk/index.vue
src/dashboard-front/src/views/stage/overview/comps/stage-card-list.vue
src/dashboard-front/src/views/stage/overview/detail-mode/index.vue

fix: 修复非多租户下的 display name 展示问题 & tenant_mode 展示原始值

---

src/dashboard/apigateway/apigateway/apis/web/release/serializers.py
src/dashboard/apigateway/apigateway/apis/web/release/views.py
src/dashboard/apigateway/apigateway/apis/web/stage/serializers.py
src/dashboard/apigateway/apigateway/apis/web/stage/views.py
src/dashboard/apigateway/apigateway/biz/releaser.py
src/dashboard/apigateway/apigateway/components/paas.py

fix(api/web): fix some api with paas

fix(api/web): fix some api with paas

---

src/dashboard/apigateway/apigateway/apps/permission/managers.py
src/dashboard/apigateway/apigateway/apps/permission/utils.py
src/dashboard/apigateway/apigateway/tests/apis/web/permission/test_views.py
src/dashboard/apigateway/apigateway/tests/apps/permission/test_managers.py
src/dashboard/apigateway/apigateway/tests/apps/permission/test_utils.py

1. 续期规则修改：
- 未过期：续期后的过期时间 = 续期前的过期时间 + 授权期限
- 已过期：续期后的过期时间 = 当前时间 + 授权期限
2. 影响接口：
- web api 应用权限续期接口
- open api 权限续期接口

fix(apps/permission): 修复权限续期问题

---

src/dashboard/apigateway/apigateway/components/paas.py

fix(api/web): fix branch get

---

src/dashboard-front/src/common/menu.ts
src/dashboard-front/src/router/index.ts
src/dashboard-front/src/views/main.vue
src/dashboard-front/src/views/permission/apply/components/custom-header.vue
src/dashboard-front/src/views/permission/apply/index.vue

feat: 权限审批页新交互

---

src/dashboard-front/src/views/home.vue

fix: 网关列表样式修复

---

src/dashboard/apigateway/apigateway/apis/web/gateway/views.py
src/dashboard/apigateway/apigateway/apis/web/stage/views.py
src/dashboard/apigateway/apigateway/biz/releaser.py
src/dashboard/apigateway/apigateway/components/http.py
src/dashboard/apigateway/apigateway/templates/dev_guideline/zh-hans/programmable_gateway.md

fix(api/web): fix paas deploy

---

src/dashboard/apigateway/apigateway/apis/web/stage/serializers.py
src/dashboard/apigateway/apigateway/apis/web/stage/views.py
src/dashboard/apigateway/apigateway/biz/release.py

fix(api/web): fix deploy status

fix(api/web): fix deploy status

---

src/dashboard/apigateway/apigateway/apis/web/plugin/views.py
src/dashboard/apigateway/apigateway/apis/web/resource_version/serializers.py
src/dashboard/apigateway/apigateway/apis/web/resource_version/views.py
src/dashboard/apigateway/apigateway/tests/apis/web/resource_version/test_serializers.py

fix(plugins): 修复插件排序

---

src/dashboard-front/src/language/lang.ts
src/dashboard-front/src/views/apiDocs/components/doc-detail-side-content.vue
src/dashboard-front/src/views/apiDocs/index.vue
src/dashboard-front/src/views/basic-info/index.vue
src/dashboard-front/src/views/home.vue

feat(frontend): 租户模式中英文翻译

---

src/dashboard-front/bk.config.js
src/dashboard-front/src/common/util.ts
src/dashboard-front/src/components/programmable-deploy-events-slider/index.vue
src/dashboard-front/src/http/programmable.ts
src/dashboard-front/src/language/lang.ts
src/dashboard-front/src/store/common.ts
src/dashboard-front/src/views/backend-service/index.vue
src/dashboard-front/src/views/main.vue
src/dashboard-front/src/views/resource/setting/index.vue
src/dashboard-front/src/views/resource/version/edition/index.vue
src/dashboard-front/src/views/stage/overview/comps/release-programmable-slider.vue
src/dashboard-front/src/views/stage/overview/comps/stage-card-item.vue
src/dashboard-front/src/views/stage/overview/comps/stage-card-line-chart.vue
src/dashboard-front/src/views/stage/overview/comps/stage-card-list.vue
src/dashboard-front/src/views/stage/overview/detail-mode/index.vue
src/dashboard-front/src/views/stage/overview/index.vue
src/dashboard-front/src/views/stage/published/index.vue

feat: 可编程网关资源部署日志 & 环境缩略模式统计图

---

src/dashboard-front/src/app.vue

fix(frontend): 修复非租户模式下的 display_name 配置

---

src/dashboard-front/src/components/programmable-deploy-events-slider/index.vue
src/dashboard-front/src/views/online-debug/index.vue
src/dashboard-front/src/views/stage/overview/comps/stage-card-item.vue

fix(frontend): 修复可编程网关的部署调试跳转和样式问题

---

src/dashboard-front/src/views/permission/app/index.vue

fix(frontend): 权限续期交互优化

---

src/core-api/pkg/database/dao/publish_event.go

fix: fix fmt

---

src/dashboard-front/src/components/programmable-deploy-events-slider/index.vue
src/dashboard-front/src/views/stage/overview/comps/stage-card-item.vue
src/dashboard-front/src/views/stage/overview/comps/stage-card-list.vue

fix(frontend): 修复可编程网关部署 status 判断 & 错误重试 & loading 态

---

src/dashboard-front/src/components/custom-table-header-filter/index.tsx
src/dashboard-front/src/components/member-select/index.tsx
src/dashboard-front/src/store/accessLog.ts

chore(frontend): 补充注释

---

src/dashboard-front/src/views/component-doc/components/doc.vue
src/dashboard-front/src/views/stage/overview/comps/stage-card-item.vue
src/dashboard-front/src/views/stage/overview/comps/stage-card-list.vue

fix(frontend): 修复环境预览状态

---

src/dashboard-front/src/views/main.vue

fix(frontend): 修复 eslint 提示

---

src/dashboard-front/src/views/permission/apply/index.vue

feat(permission/apply): 权限审批默认不按维度获取

---

src/dashboard/apigateway/apigateway/apps/metrics/prometheus/dimension.py

1. 本地部署环境数据库（mysql）缺少时区表，导致查询结果的日期无法被正确解析
2. 单测时使用 sqlite 不受影响
3. 统计改为 Func 自定义，不处理时区

fix(apps/metrics/dimension): 修复统计表查询不同数据库的时区处理和兼容问题

---

src/dashboard-front/src/views/permission/app/index.vue

fix(permission/app): 去掉应用权限 checkbox tooltips

---

src/dashboard-front/src/css/common.css
src/dashboard-front/src/language/lang.ts
src/dashboard-front/src/views/components/plugin-manage/index.vue

feat(plugin-manage): 新增插件优先级 alert

---

src/dashboard/apigateway/apigateway/apis/web/stage/views.py

fix(api/web): fix stage status

fix(api/web): fix stage status

---

src/dashboard/apigateway/apigateway/apps/plugin/constants.py
src/dashboard/apigateway/apigateway/common/plugin/checker.py
src/dashboard/apigateway/apigateway/common/plugin/convertor.py
src/dashboard/apigateway/apigateway/fixtures/plugins.yaml
src/dashboard/apigateway/apigateway/tests/common/plugin/test_checkers.py
src/dashboard/apigateway/apigateway/tests/common/plugin/test_convertors.py

feat(common/plugin): 新增插件 response-rewrite

feat(common/plugin): 新增插件 response-rewrite

---

src/dashboard-front/src/views/operate-data/dashboard/components/resource-searcher.vue

fix(components/resource-searcher): 资源筛选重复请求

---

src/dashboard-front/src/views/monitor/alarm-history/index.vue

feat(alarm-history): 告警忽略原因 tooltips

---

src/dashboard/apigateway/apigateway/apis/web/metrics/views.py
src/dashboard/apigateway/apigateway/apps/metrics/admin.py
src/dashboard/apigateway/apigateway/apps/metrics/prometheus/dimension.py

fix(apis/web/metrics): 修复请求量统计接口缺少网关过滤问题

fix(apis/web/metrics): 修复请求量统计接口缺少网关过滤问题

---

src/dashboard-front/src/language/lang.ts
src/dashboard-front/src/views/monitor/alarm-strategy/index.vue

feat(alarm-strategy): 告警策略可配置生效环境

---

src/dashboard/apigateway/apigateway/apis/web/gateway/serializers.py
src/dashboard/apigateway/apigateway/tests/apis/web/gateway/test_serializers.py

fix(api/web/gateway): 修复服务号链接格式校验问题

fix(api/web/gateway): 修复服务号链接格式校验问题

---

src/dashboard-front/src/hooks/use-selection-data.ts
src/dashboard-front/src/language/lang.ts
src/dashboard-front/src/views/permission/app/index.vue

fix(permission/app): 修复续期的 tooltips 内容

---

src/dashboard/apigateway/apigateway/apps/plugin/constants.py
src/dashboard/apigateway/apigateway/common/plugin/checker.py
src/dashboard/apigateway/apigateway/common/plugin/convertor.py
src/dashboard/apigateway/apigateway/fixtures/plugins.yaml
src/dashboard/apigateway/apigateway/tests/common/plugin/test_checkers.py
src/dashboard/apigateway/apigateway/tests/common/plugin/test_convertors.py

feat(common/plugin): add redirect plugin

feat(common/plugin): add redirect plugin

---

src/dashboard-front/src/hooks/use-selection-data.ts

fix(use-selection): 修复 selection hook

---

src/dashboard-front/.eslintignore
src/dashboard-front/src/views/permission/app/index.vue

fix(permission/app): 修复行选择 checkbox tooltips

---

src/dashboard/apigateway/apigateway/apis/web/gateway/views.py
src/dashboard/apigateway/apigateway/templates/dev_guideline/en/programmable_gateway.md
src/dashboard/apigateway/apigateway/templates/dev_guideline/zh-hans/programmable_gateway.md

fix(api/web): fix gateway dev-guide get

fix(api/web): fix gateway dev-guide get

---

src/dashboard-front/src/views/stage/overview/comps/stage-card-item.vue
src/dashboard-front/src/views/stage/overview/comps/stage-card-line-chart.vue

feat(stage/overview): 对接环境概览图表接口

---

src/dashboard-front/src/views/components-access/manage/components/sync-history.vue
src/dashboard-front/src/views/monitor/alarm-history/index.vue
src/dashboard-front/src/views/online-debug/components/request-record.vue
src/dashboard-front/src/views/operate-data/access-log/index.vue
src/dashboard-front/src/views/operate-records/index.vue
src/dashboard-front/src/views/permission/record/index.vue
src/dashboard-front/src/views/stage/published/index.vue
src/dashboard-front/yarn.lock

fix(date-picker): 修复时间选择器错误提示

---

src/dashboard/apigateway/apigateway/apis/web/plugin/views.py
src/dashboard/apigateway/apigateway/apps/plugin/constants.py
src/dashboard/apigateway/apigateway/tests/apis/web/plugin/test_views.py

fix(apis/web/plugin): 修复插件配置更新后 source 变更为 user_update

fix(apis/web/plugin): 修复插件配置更新后 source 变更为 user_update

---

src/dashboard/apigateway/apigateway/apis/web/gateway/views.py

fix(apis/web/gateway): 修复可编程网关停用失败问题

fix(apis/web/gateway): 修复可编程网关停用失败问题

---

src/dashboard-front/src/views/operate-data/dashboard/components/top.vue
src/dashboard-front/src/views/operate-data/report/index.vue
src/dashboard-front/src/views/stage/overview/comps/stage-card-item.vue
src/dashboard-front/src/views/stage/overview/comps/stage-card-line-chart.vue
src/dashboard-front/src/views/stage/overview/comps/stage-card-list.vue

fix(stage): 修复环境概览图表跳转和展示问题

---

src/dashboard-front/src/views/components/plugin-manage/config-display-table.vue

fix(stage): 修复插件值为 boolean 类型时展示文本错误的问题

---

src/dashboard-front/src/views/stage/overview/comps/stage-card-item.vue

feat(stage): 环境未发布时禁用下架按钮

---

src/dashboard-front/src/views/online-debug/index.vue

fix(online-debug): 在线调试默认选择已经发布的环境

---

src/dashboard-front/.eslintignore
src/dashboard-front/src/hooks/use-query-list.ts
src/dashboard-front/src/http/programmable.ts
src/dashboard-front/src/views/stage/published/index.vue

feat(stage/published): 可编程网关发布记录

---

src/dashboard/apigateway/apigateway/apis/web/release/serializers.py

fix(api/web): fix deploy list api

fix(api/web): fix deploy list api

---

src/dashboard-front/src/components/gateways-edit/tenant-user-selector.vue

fix(basic-info/maintainers): 修复维护人员 tooltips 过宽问题

---

src/dashboard-front/src/language/lang.ts
src/dashboard-front/src/views/backend-service/add.vue
src/dashboard-front/src/views/stage/overview/detail-mode/index.vue

feat(readonly-alert): 可编程网关的环境概览/后端服务只读说明

---

src/dashboard-front/src/views/stage/overview/comps/stage-card-item.vue
src/dashboard-front/src/views/stage/overview/comps/stage-card-list.vue
src/dashboard-front/yarn.lock

feat(stage): 优化环境预览 loading 状态

---

src/dashboard-front/src/language/lang.ts
src/dashboard-front/src/views/stage/overview/comps/stage-card-item.vue

fix(stage): 修复无数值状态的环境预览样式

---

src/dashboard-front/src/components/log-details/index.vue
src/dashboard-front/src/views/stage/overview/comps/release-sideslider.vue
src/dashboard-front/src/views/stage/overview/comps/stage-card-item.vue
src/dashboard-front/src/views/stage/overview/comps/stage-card-list.vue

fix(stage): 修复非编程网关的发布版本展示 & 状态更新逻辑

---

src/dashboard/apigateway/apigateway/common/plugin/convertor.py
src/dashboard/apigateway/apigateway/tests/common/plugin/test_convertors.py

fix(common/plugin): 修复 response-rewrite 插件 headers.add 转换问题

fix(common/plugin): 修复 response-rewrite 插件 headers.add 转换问题

---

src/dashboard-front/src/views/main.vue

feat(icon): 新增网关选择器可编程网关icon

---

src/dashboard-front/src/components/programmable-deploy-events-slider/index.vue
src/dashboard-front/src/http/programmable.ts
src/dashboard-front/src/language/lang.ts
src/dashboard-front/src/views/stage/overview/comps/stage-card-item.vue

fix(stage): 修复环境概览状态判断逻辑 & 版本号 & paas 部署日志展示

---

src/dashboard/apigateway/apigateway/common/plugin/convertor.py
src/dashboard/apigateway/apigateway/common/plugin/normalizer.py
src/dashboard/apigateway/apigateway/tests/common/plugin/test_convertors.py
src/dashboard/apigateway/apigateway/tests/common/plugin/test_normalizer.py

fix(common/plugin): 修复 response-rewrite 插件 body 为空问题

fix(common/plugin): 修复 response-rewrite 插件 body 为空问题

---

src/dashboard/apigateway/apigateway/apis/web/mcp_server/serializers.py
src/dashboard/apigateway/apigateway/apis/web/mcp_server/urls.py
src/dashboard/apigateway/apigateway/apis/web/mcp_server/views.py
src/dashboard/apigateway/apigateway/apps/mcp_server/admin.py
src/dashboard/apigateway/apigateway/apps/mcp_server/constants.py
src/dashboard/apigateway/apigateway/apps/mcp_server/managers.py
src/dashboard/apigateway/apigateway/apps/mcp_server/models.py

feat(apis/web/mcp_server): add mcp_server permission web api

feat(apis/web/mcp_server): add mcp_server permission web api

---

src/dashboard-front/src/language/lang.ts
src/dashboard-front/src/views/operate-data/access-log/components/search-input.vue
src/dashboard-front/src/views/operate-data/access-log/index.vue
src/dashboard-front/src/views/operate-data/dashboard/components/top.vue
src/dashboard-front/src/views/operate-data/dashboard/index.vue

feat(operate-data): 统一运行数据页的查询栏样式

---

src/dashboard/apigateway/apigateway/apis/web/ai_completion/serializers.py
src/dashboard/apigateway/apigateway/apis/web/ai_completion/views.py

fix(api/ai_completion): fix input

fix(api/ai_completion): fix input

---

src/dashboard-front/src/views/operate-data/access-log/index.vue
src/dashboard-front/src/views/operate-data/dashboard/index.vue
src/dashboard-front/src/views/operate-data/report/index.vue

fix(operate-data): 修复运行数据查询组件布局

---

src/dashboard/apigateway/apigateway/common/mcp/mcp_server.py
src/dashboard/apigateway/apigateway/tests/apis/web/mcp_server/__init__.py
src/dashboard/apigateway/apigateway/tests/apis/web/mcp_server/test_utils.py
src/dashboard/apigateway/apigateway/tests/apps/mcp_server/test_models.py
src/dashboard/apigateway/apigateway/tests/apps/mcp_server/test_utils.py
src/dashboard/apigateway/apigateway/tests/biz/test_mcp_server.py
src/dashboard/apigateway/apigateway/tests/common/mcp/__init__.py
src/dashboard/apigateway/apigateway/tests/common/mcp/test_mcp_server.py

test(mcp_server): add unittests

---

src/dashboard-front/src/views/operate-data/access-log/index.vue

fix(operate-data): 修复时间控件内容展示不全的问题

---

src/dashboard-front/src/views/online-debug/components/edit-table.vue
src/dashboard-front/src/views/online-debug/components/payload-headers.vue

feat(debug): 在线调试 Headers 参数名支持输入后失焦保存

---

src/dashboard/apigateway/apigateway/apis/v2/inner/serializers.py
src/dashboard/apigateway/apigateway/apis/v2/inner/urls.py
src/dashboard/apigateway/apigateway/apis/v2/inner/views.py
src/dashboard/apigateway/apigateway/apps/mcp_server/constants.py
src/dashboard/apigateway/apigateway/biz/mcp_server.py
src/dashboard/apigateway/apigateway/data/apidocs/zh/v2_inner_apply_mcp_server_permission.md
src/dashboard/apigateway/apigateway/data/apidocs/zh/v2_inner_list_mcp_server_app_permissions.md
src/dashboard/apigateway/apigateway/data/apidocs/zh/v2_inner_list_mcp_server_permission_apply_records.md
src/dashboard/apigateway/apigateway/data/apidocs/zh/v2_inner_list_mcp_server_permissions.md
src/dashboard/apigateway/apigateway/data/apidocs/zh/v2_inner_retrieve_mcp_server_permission_apply_record.md
src/dashboard/apigateway/apigateway/data/apigw-definitions/bk-apigateway-definition.yaml
src/dashboard/apigateway/apigateway/data/apigw-definitions/bk-apigateway-resources.yaml

新增：
1. mcp_server 申请权限列表接口
2. 权限申请/批量申请接口
3. 已申请权限列表接口
4. 申请记录接口
5. 申请记录详情接口

feat(apis/v2/inner): add mcp_server inner api

---

src/dashboard/apigateway/apigateway/apps/support/api_sdk/distributors/bkrepo.py
src/dashboard/apigateway/apigateway/apps/support/api_sdk/distributors/pypi.py
src/dashboard/apigateway/apigateway/apps/support/api_sdk/managers/base.py
src/dashboard/apigateway/apigateway/apps/support/api_sdk/packagers/pypi.py

fix(apps/support/api_sdk): 修复 sdk 日志输出问题

fix(apps/support/api_sdk): 修复 sdk 日志输出问题

---

src/dashboard/apigateway/apigateway/apis/open/gateway/serializers.py
src/dashboard/apigateway/apigateway/apis/web/mcp_server/views.py
src/dashboard/apigateway/apigateway/apis/web/stage/serializers.py
src/dashboard/apigateway/apigateway/apis/web/stage/views.py
src/dashboard/apigateway/apigateway/biz/release.py
src/dashboard/apigateway/apigateway/conf/default.py
src/dashboard/apigateway/apigateway/templates/mcp_server/zh-hans/guideline.md
src/mcp-proxy/pkg/middleware/bk_gateway_jwt.go

fix(mcp): fix mcp guide and fix stage status

fix(mcp): fix mcp guide and fix stage status

---

src/dashboard/apigateway/apigateway/apis/web/mcp_marketplace/views.py
src/dashboard/apigateway/apigateway/apis/web/stage/serializers.py
src/dashboard/apigateway/apigateway/apis/web/stage/views.py
src/mcp-proxy/pkg/cacheimpls/mcp_server_permission.go

fix(api/web): fix stage list and fix mcp server permission

---

src/dashboard-front/src/http/mcp-market.ts
src/dashboard-front/src/language/lang.ts
src/dashboard-front/src/views/stage/overview/comps/release-sideslider.vue

feat(release-sideslider): 删除 mcp server 资源确认

---

src/dashboard-front/src/app.vue
src/dashboard-front/src/http/mcp-server.ts
src/dashboard-front/src/language/lang.ts
src/dashboard-front/src/views/mcp-market/components/details.vue
src/dashboard-front/src/views/mcp-market/index.vue
src/dashboard-front/src/views/mcp-server/components/AuthApplications.vue
src/dashboard-front/src/views/mcp-server/components/CustomTop.vue
src/dashboard-front/src/views/mcp-server/components/ServerTools.vue
src/dashboard-front/src/views/mcp-server/detail/index.vue

feat(mcp-server): mcp 功能完善

---

src/dashboard-front/src/components/ai-chat-slider.vue
src/dashboard-front/src/views/online-debug/components/response-content.vue
src/dashboard-front/src/views/operate-data/access-log/index.vue

fix(ai): 优化AI对话输出样式 & markdown 解析

---

src/dashboard-front/src/components/create-gateway.vue
src/dashboard-front/src/views/basic-info/index.vue

fix(basic-info): 修复网关维护人员编辑问题

---

src/dashboard-front/src/views/permission/apply/index.vue

fix(permission): 修复应用权限不能部分通过审批的问题

---

src/dashboard-front/src/views/mcp-server/components/ServerTools.vue

fix(mcp): 修复 mcp 工具列表不展示的问题 & 空文档状态

---

src/dashboard-front/src/views/mcp-server/components/CreateSlider.vue
src/dashboard-front/src/views/mcp-server/components/ServerItemCard.vue
src/dashboard-front/src/views/mcp-server/detail/index.vue

fix(mcp/tools): 修复 mcp 工具 openapi schema 判断 & url复制问题

---

src/dashboard-front/src/language/lang.ts
src/dashboard-front/src/views/mcp-server/components/CreateSlider.vue
src/dashboard-front/src/views/mcp-server/components/ServerItemCard.vue

feat(mcp/tools): mcp 工具跳转到对应资源 & tooltips

---

src/dashboard-front/src/views/stage/overview/comps/stage-card-item.vue
src/dashboard-front/src/views/stage/overview/comps/stage-card-list.vue

fix(programmable/stage): 优化可编程网关环境更新逻辑

---

src/dashboard-front/src/language/lang.ts
src/dashboard-front/src/views/mcp-market/components/details.vue
src/dashboard-front/src/views/mcp-market/index.vue
src/dashboard-front/src/views/platform-tools/toolbox/components/query-log.vue

fix(query-log): 查询日志调整

---

src/dashboard-front/src/views/online-debug/components/edit-table.vue

fix(online-debug): 修复请求headers选择器

---

src/dashboard-front/src/views/mcp-market/components/details.vue
src/dashboard-front/src/views/mcp-market/index.vue

fix(mcp-market): mcp 市场列表样式调整

---

src/dashboard-front/src/components/create-gateway.vue
src/dashboard-front/src/views/monitor/alarm-strategy/index.vue
src/dashboard-front/src/views/stage/overview/comps/release-sideslider.vue

fix(frontend): 完善抽屉规范

---

src/dashboard-front/src/views/mcp-market/index.vue

fix(mcp-market): mcp 市场名称超长问题
fix(mcp-market): mcp banner问题修复

fix(mcp-market): mcp 市场样式问题

---

src/dashboard/apigateway/apigateway/apps/gateway/management/__init__.py
src/dashboard/apigateway/apigateway/apps/gateway/management/commands/__init__.py
src/dashboard/apigateway/apigateway/apps/gateway/management/commands/export_inactive_gateway.py
src/dashboard/apigateway/apigateway/apps/gateway/management/commands/export_inactive_gateways.py

feat(apps/gateway/commands): add export_inactive_gateway command

feat(apps/gateway/commands): add export_inactive_gateways command

---

src/dashboard-front/src/components/create-gateway.vue
src/dashboard-front/src/http/basic-info.ts
src/dashboard-front/src/views/basic-info/common/type.ts
src/dashboard-front/src/views/basic-info/index.vue
src/dashboard-front/src/views/home.vue

fix(frontend): 首页&基础信息&创建网关 合并冲突

---

src/dashboard-front/src/views/permission/apply/index.vue

fix(permission/apply): 修复资源审批勾选异常问题

---

src/dashboard-front/src/views/mcp-server/components/CreateSlider.vue

fix(mcp-server): 修复 mcp server “是否公开”设置无效的问题

---

src/dashboard-front/src/components/chat/index.vue

feat(chat): 禁止修改“一键拉群”人员ID

---

src/dashboard-front/src/views/mcp-server/components/McpPermission.vue

fix(mcp-permission): 修复MCP Server名称存在显示与实际不符的情况

---

src/dashboard-front/src/language/lang.ts
src/dashboard-front/src/views/mcp-server/components/CreateSlider.vue
src/dashboard-front/src/views/mcp-server/components/ServerTools.vue

fix(mcp): 修复 mcp server 相关体验问题

---

src/dashboard/apigateway/apigateway/biz/resource/importer/parser.py

fix(openapi): fix gen doc

---

src/dashboard/apigateway/apigateway/biz/resource/resource.py

fix(biz/resource): 修复资源列表默认排序问题

fix(biz/resource): 修复资源列表默认排序问题

---

src/dashboard-front/src/views/resource/setting/comps/response-params-table.vue
src/dashboard-front/src/views/resource/setting/edit.vue

fix(resource): 修复资源响应参数编辑 & 状态码校验 & 请求参数设置判断

---

src/dashboard-front/src/language/lang.ts
src/dashboard-front/src/views/mcp-server/components/CreateSlider.vue

feat(mcp): 没有可用环境时不能创建 mcp server

---

src/dashboard-front/src/language/lang.ts
src/dashboard-front/src/views/mcp-market/index.vue
src/dashboard-front/src/views/mcp-server/components/CustomTop.vue
src/dashboard-front/src/views/mcp-server/components/McpPermission.vue

fix(mcp-permission): 审批申请人接口对接

---

src/dashboard-front/src/views/mcp-server/components/CreateSlider.vue

feat(mcp-server): 从新 tab 打开 mcp 工具 & 刷新时保留工具选中状态

---

src/dashboard-front/src/views/mcp-server/components/CreateSlider.vue

feat(mcp-server): 编辑 mcp server 时优先展示可选中的工具

---

src/dashboard-front/src/http/mcp-market.ts
src/dashboard-front/src/views/mcp-market/components/details.vue
src/dashboard-front/src/views/mcp-market/index.vue
src/dashboard-front/src/views/mcp-server/components/CreateSlider.vue
src/dashboard-front/src/views/mcp-server/components/McpPermission.vue
src/dashboard-front/src/views/mcp-server/components/ServerItemCard.vue

fix(mcp-server): 修复 mcp server 样式问题 & 修复市场详情滚动问题

---

src/dashboard/apigateway/apigateway/apis/web/release/serializers.py
src/dashboard/apigateway/apigateway/apis/web/resource_version/views.py
src/dashboard/apigateway/apigateway/tests/utils/test_version.py
src/dashboard/apigateway/apigateway/utils/version.py

fix(apis/web/resource_version): fix programmable gateway deploy version

fix(apis/web/resource_version): fix programmable gateway deploy version

---

src/dashboard-front/src/views/resource/setting/comps/request-params-table.vue
src/dashboard-front/src/views/resource/setting/comps/request-params.vue

fix(resource): 修复资源请求、响应参数表格样式

---

src/dashboard-front/src/views/mcp-server/components/ServerTools.vue

fix(mcp-tools): 修复 mcp server 详情样式

---

src/dashboard/apigateway/apigateway/apis/web/resource_version/views.py

fix(apis/web/resource_version): fix programmable gateway next deploy version

fix(apis/web/resource_version): fix programmable gateway next deploy version

---

src/dashboard/apigateway/apigateway/apis/web/gateway/views.py
src/dashboard/apigateway/apigateway/components/paas.py

fix(apis/web/gateway): update paas app maintainers for programmable gateway

fix(apis/web/gateway): update paas app maintainers for programmable gateway

---

src/mcp-proxy/pkg/middleware/bk_gateway_jwt.go

fix(middleware): fix jwt user verify

fix(middleware): fix jwt user verify

---

src/dashboard/apigateway/apigateway/data/apigw-definitions/bk-apigateway-resources.yaml
src/mcp-proxy/go.mod
src/mcp-proxy/go.sum
src/mcp-proxy/pkg/config/config.go
src/mcp-proxy/pkg/server/router.go

feat(router): add app mcp proxy

feat(router): add app mcp proxy

---

src/mcp-proxy/pkg/constant/system.go
src/mcp-proxy/pkg/infra/proxy/proxy.go
src/mcp-proxy/pkg/middleware/request_id.go

fix(mcp-proxy): fix mcp response

fix(mcp-proxy): fix mcp response

---

src/dashboard-front/src/components/export-resource-dialog/index.vue
src/dashboard-front/src/http/resource.ts
src/dashboard-front/src/language/lang.ts
src/dashboard-front/src/types/common.ts
src/dashboard-front/src/types/gateway.ts
src/dashboard-front/src/types/index.ts
src/dashboard-front/src/views/resource/setting/index.vue
src/dashboard-front/src/views/resource/version/edition/index.vue

feature: 资源版本添加导出功能 --story=123767167

feature: 资源版本添加导出功能  --story=123767167

---

src/dashboard-front/src/views/basic-info/index.vue
src/dashboard-front/src/views/mcp-market/components/details.vue
src/dashboard-front/src/views/mcp-market/index.vue

fix(mcp-market): 修复 mcp 市场为空规范 & 基础信息样式调整

---

src/dashboard-front/src/components/export-resource-dialog/index.vue
src/dashboard-front/src/views/resource/version/edition/index.vue

fix: 修改资源版本导出排版样式

---

src/mcp-proxy/pkg/config/config.go
src/mcp-proxy/pkg/infra/proxy/proxy.go
src/mcp-proxy/pkg/mcp/mcp.go

fix(mcp-proxy): fix reload

---

src/dashboard/apigateway/apigateway/apis/web/gateway/views.py
src/dashboard/apigateway/apigateway/components/paas.py

该接口为应用认证，所以去掉 user_credentials

fix(components/paas): 去除 update_app_maintainers 接口的用户认证

---

src/dashboard-front/src/app.vue
src/dashboard-front/src/hooks/index.ts
src/dashboard-front/src/hooks/use-bk-user-display-name.ts
src/dashboard-front/src/views/apiDocs/components/doc-detail-side-content.vue

feat(bk-user-display-name): API 文档按网关租户模式查询 display_name

---

src/dashboard-front/src/app.vue
src/dashboard-front/src/hooks/index.ts
src/dashboard-front/src/hooks/use-bk-user-display-name.ts
src/dashboard-front/src/views/apiDocs/components/doc-detail-side-content.vue

feat(bk-user-display-name): API 文档按网关租户模式查询 display_name (#1562)

---

src/dashboard-front/src/components/gateways-edit/tenant-user-selector.vue
src/dashboard-front/src/views/apiDocs/index.vue

fix(bk-user-display-name): 修复 display name popover 显示 & 隐藏 api 文档网关负责人列

---

src/dashboard-front/src/components/create-gateway.vue
src/dashboard-front/src/views/basic-info/index.vue
src/dashboard-front/src/views/mcp-market/components/details.vue
src/dashboard-front/src/views/mcp-market/index.vue

fix(frontend): 编程网关使用指引的 markdown 渲染主题色修改 & mcp 市场和详情的页面自适应完善

---

src/dashboard/apigateway/apigateway/apis/v2/open/views.py

fix(apis/v2/open): 修复 bk_app_code 参数问题

fix(apis/v2/open): 修复 bk_app_code 参数问题

---

src/dashboard-front/src/views/mcp-server/components/ServerTools.vue
src/dashboard-front/src/views/resource/setting/comps/response-params-sub-table.vue

feat(mcp): mcp server 文档展示请求响应参数

---

src/dashboard-front/src/views/resource/setting/comps/request-params-table.vue

fix(resource): 修复请求参数表格样式

---

src/dashboard-front/bk.config.js
src/dashboard-front/src/components/create-gateway.vue
src/dashboard-front/src/components/gateways-edit/member-selector.vue
src/dashboard-front/src/language/lang.ts
src/dashboard-front/src/store/user.ts
src/dashboard-front/src/views/basic-info/index.vue
src/dashboard-front/src/views/home.vue
src/dashboard-front/src/views/operate-records/index.vue
src/dashboard-front/src/views/permission/record/index.vue
src/dashboard-front/src/views/resource/version/edition/index.vue
src/dashboard-front/src/views/stage/overview/comps/stage-card-list.vue
src/dashboard-front/src/views/stage/overview/detail-mode/index.vue
src/dashboard-front/src/views/stage/published/index.vue
src/dashboard-front/yarn.lock

fix(tenant): fix 1.17 conflicts & lint errors

---

src/dashboard-front/src/views/resource/setting/comps/request-params.vue

fix(resource): 修复资源请求参数默认值回显

---

.github/workflows/dashboard.yml
src/dashboard/Dockerfile

fix(dockerfile): upgrade python version to 3.10.15

---

src/dashboard-front/src/hooks/index.ts
src/dashboard-front/src/hooks/use-pop-info-box.tsx
src/dashboard-front/src/main.ts

feature: 公共infobox组件hooks

---

src/dashboard/apigateway/apigateway/apis/web/permission/views.py
src/dashboard/apigateway/apigateway/apps/permission/constants.py

fix(apis/web/permission): 修复权限列表过滤 v_mcp_ 开头记录问题

fix(apis/web/permission): 修复权限列表过滤 v_mcp_ 开头记录问题

---

src/dashboard-front/.commitlintrc.cjs
src/dashboard-front/bun.lock
src/dashboard-front/package.json

add commit-lint

---

src/core-api/.golangci.yaml
src/core-api/cmd/init.go
src/core-api/cmd/root.go
src/core-api/cmd/version.go
src/core-api/main.go
src/core-api/pkg/api/microgateway/permissions.go
src/core-api/pkg/api/microgateway/public_key.go
src/core-api/pkg/api/microgateway/publish_event.go
src/core-api/pkg/api/open/public_key.go
src/core-api/pkg/cacheimpls/app_gateway_permission.go
src/core-api/pkg/constant/event.go
src/core-api/pkg/database/dao/app_gateway_permission.go
src/core-api/pkg/database/dbmock.go
src/core-api/pkg/logging/init.go
src/core-api/pkg/logging/writer.go
src/core-api/pkg/metric/init.go
src/core-api/pkg/middleware/bk_gateway_jwt.go
src/core-api/pkg/server/server.go
src/core-api/pkg/service/app_permission.go
src/core-api/pkg/trace/init.go
src/core-api/pkg/util/request.go
src/core-api/pkg/util/response.go
src/core-api/pkg/util/string.go

fix: fix lint

---

src/dashboard/apigateway/apigateway/controller/publisher/publish.py
src/dashboard/apigateway/apigateway/tests/controller/publisher/test_publish.py

fix(controller/publisher): 修复发布校验问题

fix(controller/publisher): 修复发布校验问题

---

src/dashboard/apigateway/apigateway/apis/v2/open/serializers.py
src/dashboard/apigateway/apigateway/apis/v2/open/views.py
src/dashboard/apigateway/apigateway/biz/mcp_server/permission.py
src/dashboard/apigateway/apigateway/data/apidocs/zh/v2_open_mcp_server_app_permissions_apply.md

fix(apis/v2/open): 修复权限申请接口的响应结果

fix(apis/v2/open): 修复权限申请接口的响应结果

---

src/dashboard/apigateway/apigateway/core/models.py
src/dashboard/apigateway/apigateway/tests/apis/web/gateway/test_serializers.py

fix(core/model): 修复网关负责人额外字符问题

fix(core/model): 修复网关负责人额外字符问题

---

src/dashboard-front/src/components/ag-sideslider/Index.vue
src/dashboard-front/src/components/ai-seek/AiChatSlider.vue
src/dashboard-front/src/hooks/index.ts
src/dashboard-front/src/hooks/use-sidebar.ts
src/dashboard-front/src/views/backend-services/components/AddBackendService.vue
src/dashboard-front/src/views/online-debugging/Index.vue
src/dashboard-front/src/views/online-debugging/components/RequestRecord.vue

feat(sideslider_component): 侧拉抽屉组件封装

---

src/dashboard/Dockerfile

build(dockerfile): update source

---

src/dashboard-front/package.json
src/dashboard-front/src/components/ag-ring/Index.vue
src/dashboard-front/src/enums/index.ts
src/dashboard-front/src/hooks/use-max-table-limit.ts
src/dashboard-front/src/hooks/use-query-list.ts
src/dashboard-front/src/layout/component-management/Index.vue
src/dashboard-front/src/services/source/category.ts
src/dashboard-front/src/services/source/componentManagement.ts
src/dashboard-front/src/services/source/runTime.ts
src/dashboard-front/src/services/source/system.ts
src/dashboard-front/src/styles/base.scss
src/dashboard-front/src/views/component-management/category/Index.vue
src/dashboard-front/src/views/component-management/intro/Index.vue
src/dashboard-front/src/views/component-management/manage/Index.vue
src/dashboard-front/src/views/component-management/manage/components/AddComponent.vue
src/dashboard-front/src/views/component-management/manage/components/RenderConfig.vue
src/dashboard-front/src/views/component-management/manage/components/RenderSystem.vue
src/dashboard-front/src/views/component-management/manage/components/SyncAccess.vue
src/dashboard-front/src/views/component-management/manage/components/SyncHistory.vue
src/dashboard-front/src/views/component-management/manage/components/SyncVersion.vue
src/dashboard-front/src/views/component-management/route.ts
src/dashboard-front/src/views/component-management/runtime-data/Chart.vue
src/dashboard-front/src/views/component-management/runtime-data/Detail.vue
src/dashboard-front/src/views/component-management/runtime-data/Index.vue
src/dashboard-front/src/views/component-management/system/Index.vue
src/dashboard-front/src/views/component-management/system/components/AddSystemSlider.vue
src/dashboard-front/src/views/monitor-alarm/alarm-history/Index.vue
src/dashboard-front/src/views/monitor-alarm/alarm-strategy/components/AddAlarmStrategy.vue
src/dashboard-front/src/views/permission/record/Index.vue

feature: 组件管理模块重构 --stroy=125692400

---

src/dashboard-front/package-lock.json
src/dashboard-front/src/services/source/mcp-market.ts

fix(mcp-market): mcp 接口文件冲突解决

---

src/mcp-proxy/go.mod
src/mcp-proxy/go.sum

fix: fix mcp protocol version validate

fix: fix mcp protocol version validate

---

src/dashboard/apigateway/apigateway/components/paas.py

fix(components): fix paas create app

fix(components): fix paas create app

---

src/dashboard/apigateway/apigateway/components/bkpaas.py

fix(components): fix create paas app

fix(components): fix create paas app

---

src/dashboard/apigateway/apigateway/apis/v2/inner/views.py
src/dashboard/apigateway/apigateway/data/apidocs/zh/v2_inner_list_mcp_server_app_permissions.md
src/dashboard/apigateway/apigateway/data/apidocs/zh/v2_inner_list_mcp_server_permission_apply_records.md
src/dashboard/apigateway/apigateway/data/apidocs/zh/v2_inner_list_mcp_server_permissions.md
src/dashboard/apigateway/apigateway/data/apidocs/zh/v2_inner_list_resource_permission_apply_records.md
src/dashboard/apigateway/apigateway/data/apigw-definitions/bk-apigateway-definition.yaml

fix(apis/v2/inner): fix mcp-server permission api

fix(apis/v2/inner): fix mcp-server permission api

---

src/dashboard-front/src/layout/mcp-market/Index.vue
src/dashboard-front/src/views/operate-data/access-log/Index.vue
src/dashboard-front/src/views/operate-data/dashboard/components/LineChart.vue
src/dashboard-front/src/views/operate-data/report/components/Chart.vue
src/dashboard-front/src/views/platform-tools/toolbox/components/QueryLog.vue

fix(table_empty_text): 空状态修复

---

src/dashboard-front/package.json
src/dashboard-front/src/App.vue
src/dashboard-front/src/hooks/use-max-table-limit.ts
src/dashboard-front/src/layout/component-management/Index.vue
src/dashboard-front/src/layout/my-gateway/Index.vue
src/dashboard-front/src/stores/useFeatureFlag.ts
src/dashboard-front/src/styles/base.scss
src/dashboard-front/src/views/component-management/manage/components/RenderSystem.vue
src/dashboard-front/src/views/component-management/manage/components/SyncAccess.vue
src/dashboard-front/src/views/component-management/runtime-data/Chart.vue
src/dashboard-front/src/views/component-management/system/Index.vue
src/dashboard-front/src/views/operate-data/access-log/Index.vue
src/dashboard-front/src/views/operate-data/dashboard/components/LineChart.vue
src/dashboard-front/src/views/operate-data/report/components/Chart.vue
src/dashboard-front/src/views/resource-management/settings/import-doc/Index.vue

feature 增加消息通知组件

---

src/dashboard/apigateway/apigateway/apis/v2/inner/serializers.py
src/dashboard/apigateway/apigateway/apis/v2/inner/views.py
src/dashboard/apigateway/apigateway/data/apidocs/zh/v2_inner_list_mcp_server_permission_apply_records.md
src/dashboard/apigateway/apigateway/data/apidocs/zh/v2_inner_retrieve_mcp_server_permission_apply_record.md

fix(apis/v2/inner): 修复 mcp-server 权限记录缺少id问题

fix(apis/v2/inner): 修复 mcp-server 权限记录缺少id问题

---

src/dashboard-front/bun.lock
src/dashboard-front/package.json
src/dashboard-front/vite.config.ts

build(frontend): add missing json-schema dependency

---

src/dashboard-front/src/views/operate-data/access-log/index.vue

fix(frontend): 替换 v-html 指令修复XSS漏洞

---

src/dashboard-front/src/components/ag-sideslider/Index.vue
src/dashboard-front/src/components/custom-table-header-filter/index.tsx
src/dashboard-front/src/services/source/backendServices.ts
src/dashboard-front/src/views/backend-services/components/AddBackendService.vue
src/dashboard-front/src/views/monitor-alarm/alarm-strategy/Index.vue
src/dashboard-front/src/views/monitor-alarm/alarm-strategy/components/AddAlarmStrategy.vue
src/dashboard-front/src/views/permission/app/Index.vue
src/dashboard-front/src/views/permission/app/components/ProactiveAuthorization.vue
src/dashboard-front/src/views/permission/apply/Index.vue

feature: 修复告警策略模块体验问题

---

src/dashboard/apigateway/apigateway/components/paas.py
src/dashboard/apigateway/apigateway/conf/default.py

fix paas time out

---

src/mcp-proxy/pkg/infra/proxy/proxy.go

fix: mcp proxy body param 1.16

---

src/dashboard-front/src/components/guide/Index.vue
src/dashboard-front/src/components/version-diff/Index.vue
src/dashboard-front/src/services/http/middleware/response.ts
src/dashboard-front/src/services/source/gateway.ts
src/dashboard-front/src/views/api-docs/components/DocDetailSideContent.vue
src/dashboard-front/src/views/mcp-server/components/AuthApplications.vue
src/dashboard-front/src/views/mcp-server/detail/Index.vue
src/dashboard-front/src/views/resource-management/components/BackConfig.vue
src/dashboard-front/src/views/resource-management/components/FrontConfig.vue
src/dashboard-front/src/views/resource-management/components/request-params/Index.vue
src/dashboard-front/src/views/resource-management/route.ts
src/dashboard-front/src/views/resource-management/settings/Index.vue
src/dashboard-front/src/views/resource-management/settings/components/ResourceDetail.vue
src/dashboard-front/src/views/resource-management/settings/components/ResourceDocViewer.vue
src/dashboard-front/src/views/resource-management/settings/components/VersionSlider.vue
src/dashboard-front/src/views/resource-management/settings/edit/Index.vue
src/dashboard-front/src/views/resource-management/versions/components/ResourceDetail.vue
src/dashboard-front/src/views/resource-management/versions/components/VersionList.vue
src/dashboard-front/src/views/stage-management/overview/detail-mode/components/ResourceDetails.vue
src/dashboard-front/src/views/stage-management/overview/detail-mode/components/ResourceInfo.vue
src/dashboard-front/src/views/stage-management/release-record/Index.vue

fix(frontend): 修复部分体验问题

---

src/dashboard-front/package-lock.json

fix(frontend): fix package-lock.json

---

src/dashboard/apigateway/apigateway/apis/open/stage/serializers.py
src/dashboard/apigateway/apigateway/apis/v2/sync/serializers.py
src/dashboard/apigateway/apigateway/apis/web/backend/serializers.py
src/dashboard/apigateway/apigateway/apis/web/stage/serializers.py
src/dashboard/apigateway/apigateway/biz/validators.py
src/dashboard/apigateway/apigateway/common/security.py
src/dashboard/apigateway/apigateway/conf/default.py
src/dashboard/apigateway/apigateway/tests/biz/test_validators.py
src/dashboard/apigateway/apigateway/tests/common/test_security.py

1. openapi 和 webapi 获取后端服务 scheme/host 的方式不同，所以修改了 openapi 的校验
2. webapi 的 scheme 校验无改动

fix(backend): 修复后端服务 host 校验问题

---

src/dashboard-front/src/hooks/index.ts
src/dashboard-front/src/hooks/use-max-table-limit.ts
src/dashboard-front/src/hooks/use-sticky-bottom.ts
src/dashboard-front/src/hooks/use-table-setting.tsx
src/dashboard-front/src/views/api-docs/detail/Index.vue
src/dashboard-front/src/views/backend-services/components/AddBackendService.vue
src/dashboard-front/src/views/monitor-alarm/alarm-strategy/components/AddAlarmStrategy.vue
src/dashboard-front/src/views/permission/app/Index.vue
src/dashboard-front/src/views/permission/apply/Index.vue
src/dashboard-front/src/views/resource-management/components/response-params/Index.vue
src/dashboard-front/src/views/resource-management/settings/Index.vue
src/dashboard-front/src/views/resource-management/settings/components/ResourceDetail.vue
src/dashboard-front/src/views/resource-management/settings/components/ResourceDocViewer.vue
src/dashboard-front/src/views/stage-management/overview/components/CreateStage.vue

(cherry picked from commit a9b2dbb977af0b8ae2ea80d5c7585d9aea799bf6)

fix: 修复1.17版本重构后遗留问题

---

src/dashboard-front/src/views/online-debugging/components/ResponseContent.vue
src/dashboard-front/src/views/operate-data/access-log/Index.vue
src/dashboard-front/src/views/resource-management/settings/components/SelectCheckBox.vue

fix(frontend): 修复部分体验单据

---

src/dashboard-front/src/components/create-gateway/Index.vue
src/dashboard-front/src/hooks/use-bk-user-display-name.ts
src/dashboard-front/src/services/http/middleware/response.ts
src/dashboard-front/src/services/source/resource.ts
src/dashboard-front/src/stores/useEnv.ts
src/dashboard-front/src/views/resource-management/settings/Index.vue

fix(frontend): 修复部分高优先级体验问题

---

src/dashboard-front/src/App.vue
src/dashboard-front/src/layout/my-gateway/Index.vue
src/dashboard-front/src/views/home/Index.vue
src/dashboard-front/src/views/operate-data/access-log/Index.vue

fix(frontend): 样式修复

---

src/dashboard-front/src/views/resource-management/components/request-params/Index.vue
src/dashboard-front/src/views/resource-management/components/request-params/RequestParamsTable.vue

fix(resource): 修复请求参数类型为 array 时 schema 缺少 items 字段的问题

---

src/dashboard/apigateway/apigateway/apis/v2/inner/serializers.py

fix(apis/v2/inner): 补充 mcp-server 文档地址

fix(apis/v2/inner): 补充 mcp-server 文档地址

---

src/dashboard/apigateway/apigateway/apps/plugin/constants.py
src/dashboard/apigateway/apigateway/fixtures/plugins.yaml
src/dashboard/apigateway/apigateway/service/plugin/checker.py
src/dashboard/apigateway/apigateway/service/plugin/convertor.py
src/dashboard/apigateway/apigateway/tests/service/plugin/test_checkers.py
src/dashboard/apigateway/apigateway/tests/service/plugin/test_convertors.py

feat(service/plugin): add bk-access-token-source plugin

feat(service/plugin): add bk-access-token-source plugin

---

src/dashboard-front/src/services/source/resource.ts
src/dashboard-front/src/views/resource-management/versions/components/ResourceDetail.vue
src/dashboard-front/src/views/resource-management/versions/components/VersionList.vue

fix(frontend): 修复资源版本标签样式 & 导出报错

---

src/dashboard-front/src/App.vue
src/dashboard-front/src/components/plugin-manage/Index.vue
src/dashboard-front/src/components/plugin-manage/PluginInfo.vue
src/dashboard-front/src/views/online-debugging/Index.vue
src/dashboard-front/src/views/resource-management/settings/Index.vue
src/dashboard-front/src/views/resource-management/settings/components/SelectCheckBox.vue
src/dashboard-front/src/views/resource-management/settings/components/TopBar.vue

fix(plugin): 修复切换插件失效

---

src/mcp-proxy/pkg/infra/proxy/proxy.go
src/mcp-proxy/pkg/infra/proxy/types.go

fix: fix mcp proxy timeout

---

src/dashboard-front/src/views/resource-management/settings/Index.vue

fix(resource): 修复资源侧栏展示错误问题

---

src/dashboard-front/src/views/basic-info/Index.vue
src/dashboard-front/src/views/basic-info/components/EditAPIDoc.vue
src/dashboard-front/src/views/mcp-server/permission/Index.vue
src/dashboard-front/src/views/stage-management/release-record/Index.vue

fix(display_name): 渲染display_name

---

src/dashboard/apigateway/apigateway/apis/web/resource/serializers.py
src/dashboard/apigateway/apigateway/tests/utils/test_openapi.py
src/dashboard/apigateway/apigateway/utils/openapi.py

fix(openapi): fix resource schema update

fix(openapi): fix resource schema update

---

src/dashboard/apigateway/apigateway/biz/resource/importer/schema.py
src/dashboard/apigateway/apigateway/tests/apis/web/resource/test_views.py

fix(openapi): fix schema get

---

src/dashboard-front/src/services/http/middleware/response.ts

fix(frontend): 修复登录弹窗跳转逻辑

---

src/dashboard-front/src/components/plugin-manage/Index.vue
src/dashboard-front/src/components/plugin-manage/PluginInfo.vue

fix(plugin-info): 修复插件示例出现时排版混乱的问题

---

src/dashboard-front/src/services/source/stage.ts
src/dashboard-front/src/views/stage-management/overview/detail-mode/Index.vue

fix(stage): 修复无法编辑环境的问题

---

src/dashboard-front/src/components/plugin-manage/Index.vue
src/dashboard-front/src/components/plugin-manage/WhitelistTable.vue
src/dashboard-front/src/components/version-diff/Index.vue
src/dashboard-front/src/views/mcp-server/components/AuthApplications.vue
src/dashboard-front/src/views/mcp-server/permission/Index.vue
src/dashboard-front/src/views/resource-management/versions/components/SDKList.vue
src/dashboard-front/src/views/resource-management/versions/components/VersionList.vue
src/dashboard-front/src/views/stage-management/overview/detail-mode/components/ResourceInfo.vue
src/dashboard-front/src/views/stage-management/release-record/Index.vue

fix(data_empty): 筛选空状态修复

---

src/dashboard-front/src/views/stage-management/overview/card-mode/components/StageCardItem.vue
src/dashboard-front/src/views/stage-management/overview/card-mode/components/StageCardLineChart.vue
src/dashboard-front/src/views/stage-management/route.ts

fix(stage): 修复环境卡片不能正确渲染的问题

---

src/dashboard-front/src/views/backend-services/components/AddBackendService.vue

fix: 新建后端服务-后端服务地址为空未跳转并提示 --stroy=146625044

---

src/dashboard-front/src/components/ag-table/Index.vue
src/dashboard-front/src/views/resource-management/settings/Index.vue
src/dashboard-front/src/views/stage-management/overview/detail-mode/components/ResourceInfo.vue

fix(stage): 环境详情的资源信息表格迁移

---

src/dashboard-front/src/views/home/Index.vue
src/dashboard-front/src/views/mcp-server/components/ServerTools.vue
src/dashboard-front/src/views/resource-management/settings/Index.vue
src/dashboard-front/src/views/stage-management/overview/card-mode/Index.vue
src/dashboard-front/src/views/stage-management/overview/card-mode/components/StageCardItem.vue

fix(frontend): 修复部分单据

---

src/dashboard-front/src/components/ag-table/Index.vue
src/dashboard-front/src/components/render-tag-overflow/Index.vue
src/dashboard-front/src/hooks/use-date-picker.ts
src/dashboard-front/src/services/source/stage.ts
src/dashboard-front/src/views/api-docs/components/DocDetailSideContent.vue
src/dashboard-front/src/views/backend-services/components/AddBackendService.vue
src/dashboard-front/src/views/home/Index.vue
src/dashboard-front/src/views/mcp-server/components/ServerTools.vue
src/dashboard-front/src/views/mcp-server/detail/Index.vue
src/dashboard-front/src/views/mcp-server/route.ts
src/dashboard-front/src/views/online-debugging/Index.vue
src/dashboard-front/src/views/online-debugging/components/RequestRecord.vue
src/dashboard-front/src/views/operate-data/access-log/Index.vue
src/dashboard-front/src/views/resource-management/settings/Index.vue
src/dashboard-front/src/views/resource-management/versions/components/VersionList.vue
src/dashboard-front/src/views/stage-management/overview/detail-mode/components/ResourceInfo.vue
src/dashboard-front/src/views/stage-management/release-record/Index.vue

fix(frontend): 修复测试、体验单据

---

src/dashboard-front/src/components/plugin-manage/ConfigDisplayTableGeneric.vue
src/dashboard-front/src/components/plugin-manage/ConfigDisplayTableHeaderRewrite.vue
src/dashboard-front/src/components/plugin-manage/ConfigDisplayTableIpRestriction.vue
src/dashboard-front/src/components/plugin-manage/ConfigDisplayTableRateLimit.vue
src/dashboard-front/src/components/plugin-manage/ConfigDisplayTableStatusRewrite.vue
src/dashboard-front/src/components/plugin-manage/CustomTable.vue
src/dashboard-front/src/components/plugin-manage/Index.vue
src/dashboard-front/src/components/plugin-manage/types.ts
src/dashboard-front/src/hooks/use-date-picker.ts
src/dashboard-front/src/views/audit-log/Index.vue
src/dashboard-front/src/views/basic-info/Index.vue
src/dashboard-front/src/views/basic-info/components/EditAPIDoc.vue
src/dashboard-front/src/views/component-management/manage/components/SyncHistory.vue
src/dashboard-front/src/views/monitor-alarm/alarm-history/Index.vue
src/dashboard-front/src/views/online-debugging/Index.vue
src/dashboard-front/src/views/online-debugging/components/Doc.vue
src/dashboard-front/src/views/online-debugging/components/RequestRecord.vue
src/dashboard-front/src/views/operate-data/access-log/Index.vue
src/dashboard-front/src/views/permission/record/Index.vue
src/dashboard-front/src/views/stage-management/overview/components/TopBar.vue

fix(frontend): 修复测试单据

---

src/dashboard/apigateway/apigateway/tests/utils/test_openapi.py
src/dashboard/apigateway/apigateway/utils/openapi.py

fix(openapi): fix schema example(修复字典参数类型example生成示例)

fix(openapi): fix schema example

---

src/dashboard-front/src/components/create-gateway/Index.vue
src/dashboard-front/src/main.ts
src/dashboard-front/src/views/permission/apply/Index.vue

fix: 修复开启多租户后无法创建网关 --story=147018578

---

src/dashboard-front/src/App.vue
src/dashboard-front/src/layout/platform-tools/Index.vue
src/dashboard-front/src/views/api-docs/Index.vue
src/dashboard-front/src/views/platform-tools/toolbox/Index.vue
src/dashboard-front/src/views/platform-tools/toolbox/components/JsonFormat.vue
src/dashboard-front/src/views/platform-tools/toolbox/components/JwtDecoder.vue

fix: 无法点击技术支持/社区论坛/产品官网 --story=146833299

---

src/dashboard/apigateway/apigateway/apps/mcp_server/managers.py

fix(apis/web): 修复 mcp server 授权应用问题

fix(apis/web): 修复 mcp server 授权应用问题

---

src/dashboard/apigateway/apigateway/components/bkpaas.py

fix(components): fix paas header

fix(components): fix paas header

---

src/dashboard/apigateway/apigateway/apps/permission/constants.py

fix(apps/permission): 修复权限到期天数的国际化问题

fix(apps/permission): 修复权限到期天数的国际化问题

---

src/dashboard-front/src/views/component-management/manage/Index.vue
src/dashboard-front/src/views/operate-data/access-log/Index.vue
src/dashboard-front/src/views/stage-management/overview/card-mode/components/StageCardItem.vue
src/dashboard-front/src/views/stage-management/overview/detail-mode/Index.vue

fix: 无法保存组件send_mail --stroy=146996325

---

src/dashboard-front/package.json
src/dashboard-front/src/App.vue
src/dashboard-front/src/components/create-gateway/Index.vue
src/dashboard-front/src/components/user-info/Index.vue
src/dashboard-front/src/hooks/use-date-picker.ts
src/dashboard-front/src/stores/useEnv.ts
src/dashboard-front/src/stores/useUserInfo.ts
src/dashboard-front/src/views/audit-log/Index.vue
src/dashboard-front/src/views/component-management/manage/components/SyncHistory.vue
src/dashboard-front/src/views/monitor-alarm/alarm-history/Index.vue
src/dashboard-front/src/views/online-debugging/components/RequestRecord.vue
src/dashboard-front/src/views/operate-data/access-log/Index.vue
src/dashboard-front/src/views/permission/app/Index.vue
src/dashboard-front/src/views/permission/record/Index.vue
src/dashboard-front/src/views/stage-management/overview/detail-mode/Index.vue
src/dashboard-front/src/views/stage-management/overview/detail-mode/components/ResourceInfo.vue
src/dashboard-front/src/views/stage-management/release-record/Index.vue

fix: 单租户登录名显示错误  --stroy=147178977
fix: 【APIgateway合并多租户】维护人员已填写 提示仍存在 --stroy=147312087
feature: 【APIgateway合并多租户】发布记录/操作记录选择时间后默认选择00:00:00  --stroy=146577014

feature: 【APIgateway合并多租户】发布记录/操作记录选择时间后默认选择00:00:00  --stroy=146577014

---

src/dashboard-front/src/components/create-gateway/Index.vue
src/dashboard-front/src/views/permission/apply/Index.vue

fix: 创建网关多租户/非多租户人员选择器自定义错误样式

---

src/dashboard-front/src/views/basic-info/components/EditMember.vue

fix: 【APIgateway合并多租户】人员显示不一致 --stroy=147178977

---

src/dashboard/apigateway/apigateway/tracing/otel.py
src/dashboard/pyproject.toml
src/dashboard/uv.lock

修复：
- otel 升级后 import 失败  https://github.com/open-telemetry/opentelemetry-python/commit/3497e6662984edb345eaac4c4d3ac4872d438a55

fix(tracing/otel.py): fix import fail after upgrade otel

---

src/dashboard-front/src/hooks/use-max-table-limit.ts

fix: 添加漏缺的toValue导入

---

src/dashboard/apigateway/apigateway/biz/mcp_server.py

fix(apis/v2/open): 权限申请接口打开 publish 限制

fix(apis/v2/open): 权限申请接口打开 publish 限制

---

src/dashboard/apigateway/apigateway/core/models.py
src/dashboard/apigateway/apigateway/tests/core/test_models.py

fix(apis/web): 修复网关 extra_info 字段的返回值

fix(apis/web): 修复网关 extra_info 字段的返回值

---

src/dashboard-front/Dockerfile

build(frontend): Dockerfile

---

src/dashboard/apigateway/apigateway/biz/resource/importer/openapi.py

fix(api/web): resource version export

---

src/dashboard/apigateway/apigateway/biz/resource/importer/openapi.py

fix(api/web): fix resource-verison export

fix(api/web): fix resource-verison export

---

src/dashboard/apigateway/apigateway/common/pypi/registry.py

fix(common/pypi): 修复 python sdk 生成时的异常捕获

fix(common/pypi): 修复 python sdk 生成时的异常捕获
